### ISSUE TITLE
Please add a README

### ISSUE THREAD

**Issue by mmikulicic** [google/mtail#1]
A oneliner explaining what this thing is doing would be fine; it's been >2 minutes and I still don't have a clue what this thing is about.

**Comment by ian-kent** [comment]
:+1: readme would be good

Looks like a metric collector which compiles the analysis "programs" and runs them in a purpose built VM and tails arbitrary log files, which then makes the metrics available over HTTP

the [examples](https://github.com/google/mtail/tree/master/examples) and [testdata](https://github.com/google/mtail/tree/master/testdata) directories demonstrate how it works

looks awesome!
