### ISSUE TITLE
Add support for arbitrary string processing of matched fields

### ISSUE THREAD

**Issue by freznicek** [google/mtail#102]
Dear all,
I'm using latest mtail (https://github.com/google/mtail/releases/tag/v3.0.0-rc4) for legacy applications prometheus.io style metric reporting.

I believe mtail is good tool but there are plenty of areas to perform better.

I currently want to combine two matched logfile line fields concatenate them and use product as metric's label `errors_total{type=...}`. Is there a way how to achieve it?

Let's look at my mtail rule snippets:
 * option A (preferred)
```
counter errors_total by app, type

# 5xx requests highlighted as application error
/sortserver '([^\(]+)\(.+ status=(5[0-9]+)/ {
    errors_total["sortserver"][sprintf("%s %s",$1,$2)]++
}
```
 * option B
```
counter errors_total by app, type

# 5xx requests highlighted as application error
/sortserver '([^\(]+)\(.+ status=(5[0-9]+)/ {
    errors_total["sortserver"][$1+" "+$2]++
}
```

I'm basically proposing to add another builtin function `sprintf(...)` wired to golang's `fmt.Sprintf(...)` or at least allow string concatenation with `+` operators.

Thanks in advance for your reply.

**Comment by jaqx0r** [comment]
I think this is a good idea, sure.  But in the meantime, you could achieve
this by exporting the two matches as separate labels here and doing the
work in the collector (e.g. prometheus):

counter errors_total by app, type, code

... {
  errors_total["sortserver"][$1][$2]++
}

**Comment by freznicek** [comment]
I understand, but unfortunately in my case I do not want to put it in separate metric labels.

There is easy solution to my problem with existing PR https://github.com/google/mtail/pull/104.

How high is the chance to get it in as rc5 in week or so?

**Comment by jaqx0r** [comment]
Change was slim.  I don't like the idea of adding a general purpose sprintf builtin.  I am OK with adding plain string concatenation as the language already has support for concatenating patterns and pattern constants, extending this to all string objects is the right thing to do and will unblock the grammar to allow patterns to appear in more complex conditional expressions ( #88 and #103 and even #100) as well.

mtail isn't supposed to do complex processing, it's supposed to do the minimal necessary to get raw data out of a log and into a collection system like Prometheus.  If you like, consider that mtail turns logs back into structured events (split up into individual metric streams); it is not in the business of turning the raw event back into a cooked log, which is what sprintf would allow.

PR 104 wants to add a new builtin concat(), but I want to make the additino operator do the familiar action -- especially as I said above, the pattern concatenation form already uses it.

**Comment by freznicek** [comment]
Thanks for an update! Looking forward in seeing change merged in.

Although I don't like you do not support sprintf() way I understand that changes to get it in would be much bigger (not fixed number of arguments vs current code base) than proposed concat (PR https://github.com/google/mtail/pull/104).
