### ISSUE TITLE
Add support for =~ (alternatively just ~) and !~ operators

### ISSUE THREAD

**Issue by mjf** [google/mtail#103]
Hello,

it would be really nice if the `=~` (alternatively just `~` for compatibility with `awk(1)`, the `=~` is for compatibility with *PromQL* most people are used to here) and `!~` operators vere supported (may need some support for contatenation as well). Examples (probably not all of possible combinations):

    # string
    $foo ~ "bar" {
        # ...
    }

    # regex
    $foo !~ /bar/ {
        # ...
    }

    # const
    const BAR /bar/

    $foo =~ BAR {
        # ...
    }

    # var (obscure but why not)
    /(?P<bar>bar)/ {
        $foo ~ $bar {
            # ...
        }
    }

I would also suggest the `=~` (`~`) and `!~` operators automatically converted *r-values* to type *regex*, if there's any (not sure) otherwise some of the above exmaples would not work. If not acceptable at least manual "casting" should be allowed for *non-regex* or *unknown* types (as it already works for simple matching). Examples:

    $foo ~ // + "bar"
    $foo ~ // + BAR
    $foo ~ // + $bar

Whether to allow "casting" of numerical types is a question.

-----

**Real-world use case**

I use `mtail(1)` to count misc. metrices from mail server log files. I would like to count

1. total count of relays and
2. count of IPv6 relays,

so that I knew how many percent of relays are on IPv6. Example (simplified):

    /,\s+relay=[^[]+\[(?P<relay_ip>[^]]+)\]:/ {
        $relay_ip ~ /:/ {
            counter ipv6_relays_count
            ipv6_relays_count++
        }
    }

Of course workaround exists but it's very ugly. Having the `~` and `!~` operators would make code
maintainable and simpler.

**Comment by jaqx0r** [comment]
This is a good idea. I tried to do something similar with conditional
expressions last week, e.g. /(?P<var>.*)/ && $var == "foo" but the parser
doesn't allow that yet, as I have an error in the way regular expressions
are used as conditionals.  Fixing both will make this work.

Thanks for the report!

**Comment by mjf** [comment]
@jaqx0r For this and I am looking forward to it. (I also hope you could raise priority for this. `mtail(1)` is evolving and this is kind of language design pattern...) Thanks for you great work too!

**Comment by Kelvin-Chu** [comment]
+1 on this.  Having this would be extremely useful.

**Comment by jaqx0r** [comment]
There's some more code required to make this work but I'm whittling it down.

**Comment by jaqx0r** [comment]
I'm certain that this has been working for a line while now.
