### ISSUE TITLE
Allow "non-conditional" block

### ISSUE THREAD

**Issue by mjf** [google/mtail#105]
Hello,

in *AWK* block may not have condition at all. I would like to see for *MTail* too, i.e.

    {
        counter foo
        foo++
    }

Of course one can write something like

    /.+/ {
        counter foo
        foo++
    }

But that's just a "hack" while the *MTail*'s language does not support the feature. What's really important - it's not just about having block without a condition at all...

The main point is that in *AWK* the "non-conditional" block are "merged" (or evaluated) based on flow runtime conditions which is something I would like *MTail* allowed one day too, i.e.

    {
        counter foo
        foo++
    }

    $foo <= 10 {
        next
    }

    {
        counter bar
        bar++
    }

Does it make sense to extend the *MTail*'s syntax with this? (Although I feel that to add the feature wouldn't be easy.)

-----

To illustrate it more further try the following `awk(1)` script doing basically the same thing as I expect to do *MTail* with the example code above:

    $ seq 1 20 |awk '{foo++}foo<=10{next}{bar++}END{print"foo",foo,"bar",bar}'
    foo 20 bar 10

Such feature will extend `mtail(1)`'s powers even more!

**Comment by jaqx0r** [comment]
I can't visualise what you're trying to do with this construct.  What do you mean by "merged" ?  How is `next` behaving in this code?  ... I think you're saying that the `foo <= 10` block causes the program to terminate and skip to the next line of input? 

`next` means "jump to the decorated block" already, so we'd have to find a new keyword.

But, I don't understand why you wouldn't just invert the sense of the condition:

```
counter foo
counter bar
// {
foo++
}
$foo > 10 {
 bar++
}
```
