### ISSUE TITLE
regression handling float type between rc2..master

### ISSUE THREAD

**Issue by lksv** [google/mtail#106]
Hi,

following mtail program fail.

```
gauge metric

/(\d+\.\d+)/ {
  metric += $1
}
```

by parsing simple log:
```
1.1
```

Traceback (on the master branch): ...ufff, it was raising an error a minute ago.

But now I simple do not count the metric without the traceback...
I will try to generate the traceback tomorrow.

**Comment by jaqx0r** [comment]
There should be a runtime error in the log.  If you can paste all of it,
then we can figure out what it's doing.

**Comment by FuFikCZ** [comment]
Hi,

log is here: [mtail.log](https://github.com/google/mtail/files/1382283/mtail.log)

I used @lksv mtail program and then run
```
# no error
$ echo 1 >> log/log.log

# mtail tracebacks
$ echo 1.1 >> log/log.log
```

**Comment by jaqx0r** [comment]
This error is a simple matter of a facepalm.  The add-assign operator "+=" doesn't do any type checking and assumes int.    A simple fix but I uncovered some mess in the VM error reporting that I want to fix to make this easier to see in the example tests.
