### ISSUE TITLE
simple counter stops working after commit: 25d6549... Merge branch 'oneshot-tail'

### ISSUE THREAD

**Issue by benhansenslc** [google/mtail#107]
Attempting to use the simple counter sample in README.md

    counter line_count
    /$/ {
      line_count++
    }

Silently fails to count updates to the log. I look at ":3903/json" and the count does not increase even after using `echo` to add more lines to the log file.

The command I ran is:

    ~/go/bin/mtail -progs progs/ -logs test_log.txt -v=3 -logtostderr

After some debugging it looks like this works fine on commit `5e6d389... Only show coverage on the master branch` but starts to have issues on `25d6549... Merge branch 'oneshot-tail'`

Tested on both go-1.7.4 and go-1.9.1 and Ubuntu 14.04 and Ubuntu 16.04.

Let me know if you have any troubles reproducing.

## Logs when working

```
root@ubuntu-512mb-nyc3-01:~/lt# ~/go/bin/mtail -progs progs/ -logs test_log.txt -v=3 -logtostderr
I1013 23:33:56.826788   20144 main.go:101] mtail version v3.0.0-rc1-175-g55dded9 git revision 55dded93268bb25caac9d98c812df948b159d2c4 go version go1.7.4
I1013 23:33:56.827669   20144 main.go:102] Commandline: ["/root/go/bin/mtail" "-progs" "progs/" "-logs" "test_log.txt" "-v=3" "-logtostderr"]
I1013 23:33:56.829078   20144 loader.go:196] Loaded program myprog.mtail
I1013 23:33:56.829802   20144 loader.go:215] Program myprog.mtail has goroutine marker 0x6d797072
I1013 23:33:56.830230   20144 loader.go:218] Started myprog.mtail
I1013 23:33:56.830768   20144 mtail.go:103] Tail pattern "test_log.txt"
I1013 23:33:56.831386   20144 tail.go:125] glob matches: [test_log.txt]
I1013 23:33:56.833640   20144 tail.go:349] Tailing /root/lt/test_log.txt
I1013 23:33:56.830596   20144 vm.go:715] Starting program myprog.mtail
I1013 23:33:56.834183   20144 mtail.go:290] Listening on port :3903
```

## Logs when not working

```
root@ubuntu-512mb-nyc3-01:~/lt# ~/go/bin/mtail -progs progs/ -logs test_log.txt -v=3 -logtostderr
I1013 23:32:11.513628   19336 main.go:101] mtail version v3.0.0-rc2-19-g25d6549 git revision 25d65497f9b4c5c7b36d9bdc105d6cb2e9ae1ef6 go version go1.7.4
I1013 23:32:11.514571   19336 main.go:102] Commandline: ["/root/go/bin/mtail" "-progs" "progs/" "-logs" "test_log.txt" "-v=3" "-logtostderr"]
I1013 23:32:11.515830   19336 loader.go:196] Loaded program myprog.mtail
I1013 23:32:11.516367   19336 loader.go:215] Program myprog.mtail has goroutine marker 0x6d797072
I1013 23:32:11.516738   19336 vm.go:715] Starting program myprog.mtail
I1013 23:32:11.517057   19336 loader.go:219] Started myprog.mtail
I1013 23:32:11.517375   19336 mtail.go:55] Tail pattern "test_log.txt"
I1013 23:32:11.517851   19336 tail.go:130] glob matches: [test_log.txt]
I1013 23:32:11.518275   19336 tail.go:347] EOF on first read
I1013 23:32:11.518540   19336 tail.go:363] Tailing test_log.txt
I1013 23:32:11.518854   19336 mtail.go:216] Listening on port :3903
```

**Comment by mjf** [comment]
Suffering of (probably) the same issue too.

**Comment by jarro2783** [comment]
I'm seeing this too. Running it with `-one_shot` seems to produce the right values. Making it a `gauge` doesn't change anything either.

**Comment by jaqx0r** [comment]
That's bizzare, because this is one of the example end-to-end tests.  Thanks for the report, I'll investigate further.

**Comment by jaqx0r** [comment]
OK, maybe somethin has changed again since, but I can't repro this:

```
make install
~/go/bin/mtail --progs examples --logs /tmp/test.log -v=3 --logtostderr
```
another shell:

cat >> /tmp/test.log
send some newlines

open up localhost:3903/varz, which has
line_count{prog=linecount.mtail,instance=gunstar} 2

/json has

```
  {
    "Name": "line_count",
    "Program": "linecount.mtail",
    "Kind": 1,
    "Type": 0,
    "LabelValues": [
      {
        "Value": {
          "Value": 2,
          "Time": 1509598704239888678
        }
      }
    ]
  },
```

and /metrics:

```
# TYPE line_count counter
# line_count defined at linecount.mtail:4:9-18
line_count{prog="linecount.mtail"} 2
```

Can you please update to latest HEAD and try again?

**Comment by jarro2783** [comment]
There have been no new commits since I last tried. It's broken on d72ed38d6e2d1951c45c678f7bc63f7d5fb9cac0. I double checked, it's definitely still broken.

**Comment by benhansenslc** [comment]
Thanks @jaqx0r for looking at this. It appears the issue only happens when relative paths are given as the `-logs` argument. When an absolute path is given it works fine.  -one_shot does seem to work with relative paths. Also commit tagged "v3.0.0-rc2" and before works with relative paths so this does appear to be a regression. Let me know if you are not able to reproduce this issue when using a relative path and I can give you access to a cloud server that has a setup that produces the issue.
