### ISSUE TITLE
TestLogWatcherAddError fails under root

### ISSUE THREAD

**Issue by dohnto** [google/mtail#111]
Hello, using current master (d72ed38)

```
$ id
uid=1000(tom) gid=1000(tom) groups=1000(tom),10(wheel),966(pkg-build),975(vboxusers),1001(docker)
$ make test
...
$ echo $?
0
```

But if I run tests under root user:
```
$ id
uid=0(root) gid=0(root) groups=0(root)
$ make test
...
=== RUN   TestLogWatcherAddError
--- FAIL: TestLogWatcherAddError (0.00s)
	log_watcher_test.go:160: didn't fail to add file
=== RUN   TestWatcherErrors
E1019 14:21:16.062382   10292 log_watcher.go:60] fsnotify error: Injected error for test
--- PASS: TestWatcherErrors (0.00s)
...
```

It seems to be failing due to fact, that running under root user there is no permission check when accessing files.

**Comment by jaqx0r** [comment]
Seems legit. Why are you running it under root?

**Comment by dohnto** [comment]
I am used to build stuff in docker and it is the easiest choice to build it under root.

**Comment by jaqx0r** [comment]
I accidentally closed this.  We can skip the tests that can't fail when run as root.
