### ISSUE TITLE
Support for optional labels

### ISSUE THREAD

**Issue by ferringb** [google/mtail#112]
If one is writing their own exporter, they can add labeling freeform to the metrics exported.  Mtail however forces a constant set of labels, which force people to use separate metrics for this scenario.

Consider backuppc logs.  A snippet of the logs mtail will be ran against is thus:
```
2017-10-20 08:04:03 Backup failed on node_x (Unable to read 4 bytes)
2017-10-20 08:04:03 Finished node_y (BackupPC_link node_y)
```
This results should be synthesized into one metric type- a gauge indicating success for the target, and *preferably*, labeling the failure with the cause ('Unable to read 4 bytes' in this case).

If I were rolling my own exporter, the metrics would be thus:
```
# TYPE backuppc_job_status gauge
backuppc_job_status{job="node_y"} 1 <that-timestamp>
backuppc_job_status{job="node_x", cause="Unable to read 4 bytes"} 0 <that-timestamp>
```
and when that cranky node_x stopped failing, it would become:
```
# TYPE backuppc_job_status gauge
backuppc_job_status{job="node_x"} 1 <that-timestamp>
backuppc_job_status{job="node_y"} 1 <that-timestamp>
```

As best I can tell, mtail fundamentally doesn't like the optional annotation thing I want to do here; metric definitions state the indexing (```gauge backuppc_job_status by job```), thus if I want to piggyback the cause in as a label, I must add that dimension to *all* metrics exported of that name.

Further, mtail wouldn't wipe the metrics it has in this scenario- thus that 'failed' version of the metric would live on, alongside the 'non-failed' version due to the labeling differing.  That's not optimal.

As said, if this were my own exporter, I can work around this.  I don't see a way to do this in mtail currently- even if I used ```del``` (and that's assuming it works against non hidden metrics), I'd have to know the 'cause' to do the deletion.

Assuming I'm not missing something obvious in the analysis above, a rough syntax suggestion is thus:

```
    gauge backuppc_job_succeeded by job
    /Finished +(?P<name>[^ ]+) +\(Backup[^)]+\)$/ {
      backuppc_job_succeeded[$name] = 1
    }
    /Backup failed on (?P<job>[^ ]+) \((?P<cause>.+)\) *$/ {
      backuppc_job_succeeded[$job] = 0
      annotate_metric(backuppc_job_succeeded[$job], cause=$cause)
    }
```
The idea behind annotate_metric is that it's optional labels- not required to index that metric, but added until the next time that metric is updated, at which point the extra labeling is dropped.

Thoughts?

**Comment by jaqx0r** [comment]
Fundamentally the idea of having an optional dimension on a metric means
that the metric should have that value for the entire vector. This is
unsolvable in the general case because the domain of the dimension is
unknowable until the lines appear.

Prefer to separate the error and success metrics if one is decomposed into
status and the other is not.  The total of both should equal the number of
attempts. (And all that postprocessing should be done in Prometheus.)

**Comment by jaqx0r** [comment]
If the program looked like:

`
counter backuppc_job_result by job, status

    /Finished +(?P<name>[^ ]+) +\(Backup[^)]+\)$/ {
      backuppc_job_result[$name]["ok"]++
    }

    /Backup failed on (?P<job>[^ ]+) \((?P<cause>.+)\) *$/ {
      backuppc_job_result[$job]["cause"]++
    }
`

I believe you get all the information you need from the log to be able to report on error rates and also extract causes.   Passing OK as a "cause" for successes has worked for me in the past ; and is equvalent to an HTTP 200 error code.

**Comment by jwalzer** [comment]
See #84: There could be a reason, to implement this. I'm happy to explain again the idea I have in mind
