### ISSUE TITLE
a check-syntax option should be added

### ISSUE THREAD

**Issue by ferringb** [google/mtail#114]
I'm looking for syntax checking like what is possible via promtool.  promtool rules in particular is stupidly useful if you're using a SCM and want to enforce a parse check on the file before it gets deployed (or if the dev is well behaved, they're checking it before they open a CL/PR).

Mtail has a way to do this, but it's non obvious.  You can do thus to accomplish the same:
```
mtail --progs [/path/to/that/prog|/path/to/programs-directory-to-validate] --logs /dev/null --logtostderr --oneshot
```

If parsing fails, that blows up with an exit code, which can be used to identify that the compilation failed.  It's a hack, but it works.

It would be preferable if we could just instead do thus:

```
mtail --check-syntax [/path/to/that/prog|/path/to/programs-directory-to-validate]
```

That's mostly just syntactic glue- thus should be simple to implement I suspect- but it's also a far simpler way to tell people how to do a parse/compile check.

**Comment by jaqx0r** [comment]
--compile_only is supposed to be this feature.  It's documented, but I suspect not well enough.  Where did you look so I can add it there?

**Comment by ferringb** [comment]
I think you made a fundamental mistake in your question of "where did you look?".  That flaw is thus: you assumed I thought to look at the help output.  I'd love to claim I did, but I didn't.

Pardon for the noise ;)

I strongly suggest you add a reference to this into the deploying section.  That's where I'd look for details of how to deploy/integrate.
