### ISSUE TITLE
using metric in comparison conditions

### ISSUE THREAD

**Issue by Kelvin-Chu** [google/mtail#116]
Build: mtail version v3.0.0-rc4-7-gd72ed38 git revision d72ed38d6e2d1951c45c678f7bc63f7d5fb9cac0 go version go1.8.3

Howdy Folks,

I'm trying to store the response time after multiplying it by 1000 to a variable and trying to put it in buckets... something like this:

```
gauge response_time
counter hit
counter miss

/^/ +
/(?P<response_seconds>\d+\.\d+) / +
/$/ {
    response_time = $response_seconds * 1000
    response_time < 100000 {
        hit++
    } else {
        miss++
    }
}
```
 I will see the correct value for the gauge 'response_time' but 'hit' and 'miss' will get no data.  What am I missing?

Cheers,
Kelvin

Edit: I'm aware I can just change it to:
```
    $response_seconds < 100 {
        hit++
    } else {
        miss++
    }
```

**Comment by jaqx0r** [comment]
I'm not sure you'r emissing anything.  It looks like a bug to me!  Thanks for the report!
