### ISSUE TITLE
getfilename() should allow for regexes and capturing

### ISSUE THREAD

**Issue by ferringb** [google/mtail#118]
The syntax for this is likely going to be related to #88 ; I'm trying to monitor conserver logs to identify if a heartbeat message has or has not been sent, and using that to verify that serial settings are correct.  Specifically, I'm doing this via triggering a sysrq message to ensure it goes to console.

Yes that's dirty and horrible, but hey, it works.

What I'd like to write is thus:
```
counter console_heartbeat_seen by host
getfilename() =~ /^\/var\/log\/conserver\/(?P<host>.+)$/ {
  /SysRq : HELP :/ {
    conssole_heartbeat_seen[$host]++
  }
}
```
However, there is no way to do matching against getfilename for grouping.  More annoyingly, because I'm monitoring a directory without knowing the files that exist up front, I'm using ```-logs /var/log/conserver/*```; however I can't use regex against getfilename() to limit the program.  For example, the following is an example of where getfilename() now isn't fully usable (irregardless of my request for captures):
```
getfilename() == "/var/log/conserver/*"
```
Since getfilename is the log file name, and since I'm using globbing for -logs, there is no way to make this syntax work for whitelisting.  Blacklisting- like thus- is the workaround.
```
getfilename() != '/var/log/kern.log'
```
That's not a great solution; that assumes that no other log source mtail sees will have the pattern I'm checking for, and also results in that program being applied to all log sources sans kern.log.

**Comment by jaqx0r** [comment]
I think this is an exact duplicate of #36

**Comment by ferringb** [comment]
Yeah, looks it.  I'd suggest tweaking the title of #36 to include getfilname; that ticket (afaik) was filed before getfilename() was added, thus is more generic- and not as easily found if one is searching based on the current functionality for this.
