### ISSUE TITLE
panic when Tailer.openLogPath runs out of retries

### ISSUE THREAD

**Issue by aecolley** [google/mtail#120]
Stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x72606a]
goroutine 15 [running]:
github.com/google/mtail/tailer.(*Tailer).startNewFile(0xc4200e6b40, 0x0, 0x0, 0x1, 0x2, 0xa21ec0)
/builddir/build/BUILD/mtail-4cd3e4e9d47a17a61d83c1f1a08155d88c725519/src/github.com/google/mtail/tailer/tail.go:357 +0x3a
github.com/google/mtail/tailer.(*Tailer).openLogPath(0xc4200e6b40, 0xc4200725e0, 0x11, 0x1)
/builddir/build/BUILD/mtail-4cd3e4e9d47a17a61d83c1f1a08155d88c725519/src/github.com/google/mtail/tailer/tail.go:347 +0x29d
github.com/google/mtail/tailer.(*Tailer).handleLogCreate(0xc4200e6b40, 0xc4200725e0, 0x11)
/builddir/build/BUILD/mtail-4cd3e4e9d47a17a61d83c1f1a08155d88c725519/src/github.com/google/mtail/tailer/tail.go:301 +0x69b
github.com/google/mtail/tailer.(*Tailer).run(0xc4200e6b40, 0xc420053980)
/builddir/build/BUILD/mtail-4cd3e4e9d47a17a61d83c1f1a08155d88c725519/src/github.com/google/mtail/tailer/tail.go:418 +0x28f
created by github.com/google/mtail/tailer.New
/builddir/build/BUILD/mtail-4cd3e4e9d47a17a61d83c1f1a08155d88c725519/src/github.com/google/mtail/tailer/tail.go:99 +0x298
```

The condition was that mtail was being run under systemd, using [ReadOnlyDirectories](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ReadWritePaths=) to limit filesystem access. One of mtail's log targets was `/var/log/messages`, but that file was excluded from the `ReadOnlyDirectories` and so it was inaccessible. Mtail got permission-denied when it tried to read that file. All was well until the file was logrotated. The expected behavior is that mtail logs an error and continues to ignore the file. The actual behavior was a panic.

Rotation of the file caused `openLogPath` to attempt to open it in a loop. When the last retry failed, the loop exited with `f == nil`, but the following code assumes incorrectly that `f != nil`.

**Comment by jaqx0r** [comment]
Nice find, thanks!

**Comment by jaqx0r** [comment]
Was /var/log/messages explicitly listed in the logs flag or was it picked up by a glob?

**Comment by jaqx0r** [comment]
The fix is easy, making a test to reproduce this is hard.

https://github.com/spf13/afero/issues/150 filed to get the test filesystem to support chmodding; in the meantime I'm trying to do it with raw filesystem access.

**Comment by aecolley** [comment]
In answer to your question, /var/log/messages was the first entry in the list of log files to watch. Other entries in the list used globbing, but not /var/log/messages.

**Comment by jaqx0r** [comment]
Thanks, that helps to understand how we entered that codepath the second
time.  Looks like we have a 5 year old logic bug that seems to have been
benign because we never really had to perform a retry.
