### ISSUE TITLE
tags for prometheus

### ISSUE THREAD

**Issue by freeseacher** [google/mtail#125]
Hi. there are mention in doc about tags but there are no examples of tags. 
So how do i add tags for Prometheus about what am i collecting ? 

my scheme will be like this
/var/log/noc/discovery-*.log under * is something about 12 files. that part of file have to be one of the tags that i've collecting 
in file there are several lines with interesting data
one of them in
`/var/log/noc/discovery-NSK-00.log`
like
`2017-11-26 19:18:45,694 [scheduler.discovery] [MY.SW] [discovery|periodic|switch-01] Timings: uptime = 10033.82ms, interfacestatus = 10061.28ms, metrics = 20077.60ms`
so the final metrics from prometheus i am expecting is something like 
`uptime_time{log="NSK", profile="MY.SW"} 10033.82`

**Comment by freeseacher** [comment]
ok. let me answer this by my self
here are https://github.com/google/mtail/issues/36 for extracting data from filename
and profile var can be set up like this 
`uptime_time by profile` so it will appear in tags

**Comment by freeseacher** [comment]
so final real world example will be like this:
```version: '2'
services:
  promt:
    image: prom/prometheus:v2.0.0
    restart: always
    volumes:
      - "$PWD/prom:/etc/prometheus"
      - "/data/metrics/prom/:/prometheus-data"
    command: 
      - --log.level=debug
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus-data
      - --storage.tsdb.retention=30d
      - --web.external-url=https://prom.center.rt.ru/ 
      - --query.max-concurrency=40
      - --query.timeout=20s

**Comment by jaqx0r** [comment]
Hi!  Which documentation are you referring to?

Sounds like you're blocking on #36 to be fixed to do what you need?

**Comment by freeseacher** [comment]
That one https://github.com/google/mtail/wiki/Metrics

currently there are no troubles with mtail. it works as i want. Tnx.
