### ISSUE TITLE
Updating a parser file duplicates metrics

### ISSUE THREAD

**Issue by ioggstream** [google/mtail#127]
Hi @all, I get the following behavior. Which is the right way to solve it?

### reproduce

1- run mtail  1.0.0-rc4
2- edit a parser file in progs directory

### I expect

1- stats name won't be duplicated

### instead

  * multiple metrics with the same name are shown.
  * prometheus takes only the first one (the older).

```
$ curl 0:3209/metrics |& grep local_total

# TYPE postfix_local_total counter
# postfix_local_total defined at postfix.mtail:20:9-27
postfix_local_total{prog="postfix.mtail"} 2
# postfix_local_total defined at postfix.mtail:20:9-27
postfix_local_total{prog="postfix.mtail"} 0
# postfix_local_total defined at postfix.mtail:20:9-27
portfix_local_total{prog="postfix.mtail"} 104
```

**Comment by jaqx0r** [comment]
Uhoh. Thanks for the report. The oldest metric should be reused but looks
like they are now recreated when the new compile occurs.

**Comment by ioggstream** [comment]
@jaqx0r can you pls point me to the code which is doing the reuse? I could try to fix it...

**Comment by ioggstream** [comment]
The part re-adding metrics is here:

https://github.com/google/mtail/blob/master/metrics/store.go#L35

Is it enough to check that metric labels are not duplicated?

A simple workaround could be to just to prepend new metrics instead of append them.

**Comment by jaqx0r** [comment]
I think the better place to do this is in the loader,
https://github.com/google/mtail/blob/master/vm/loader.go#L198 where we do
the metric add immediately after compilation.  Here instead we should be
testing for existence in the store.

However the complication here is that the loader is only given a list of
metrics to add, and the copmiler has already created new metrics, so the
fix would need to update the program's reference as well.

**Comment by jprukner** [comment]
@ioggstream Any progress on this issue?

**Comment by ioggstream** [comment]
@jprukner no, sorry :(  The submitted patch is working fine months and I hadn't the time to rework on the item, moreover a better solution is quite more complex to implement than mine.

I'm currently working 24/7 on another project: if you can work on that let me know and I'll try to help in the few time I have.

Thanks for asking anyway! Peace, R.

**Comment by jprukner** [comment]
@ioggstream Thanks for response.
I am experiencing a similar issue to what you described and I thought it may be caused by the same bug. Duplicates start to show up after log is rotated. I don't know if the patch you made fixes both issues or if it's a different issue. I haven't tried yet. I'll investigate it and let you know. If it's caused by the same bug, I'll try to create more complex fix.

**Comment by ioggstream** [comment]
Hi @jprukner, just try my PR ;) and check. The work to be done should be different depending on the result.

**Comment by jaqx0r** [comment]
Thanks for the reminder!  I just forked the PR and added the test I wanted, which uncovered a bug when the duplicated metric had no labelvalues attached.
