### ISSUE TITLE
Glob matching keeps deleted files open

### ISSUE THREAD

**Issue by schweikert** [google/mtail#129]
We have apache-style access log files like this:

    /var/log/access_log.2017-12-04
    /var/log/access_log.2017-12-05
    /var/log/access_log.2017-12-06
    ...

It seemed like mtail's file globbing ability would be ideal here, so we started using it as follows:

    /usr/bin/mtail -progs /etc/mtail -logs /var/log/access_log.*

Unfortunately, we then found out that the filesystem was getting full, and the reason was that mtail was keeping old log files open, that were long deleted by the log rotation script.

IMO, mtail needs to close files that are deleted (fsnotify probably also notifies this), because otherwise it prevents disk space to be reclaimed by deleted log files. Until this is changed, the file globbing feature should not be used for timestamped log files (or you should restart mtail every night, as a workaround).

**Comment by jaqx0r** [comment]
Doh!  This is a simple fix, and I'm embarassed to say a feature I did not
port from our internal version because I couldn't remember why it existed.

**Comment by schweikert** [comment]
Thanks a lot for the fix! I have verified that it works for us.
