### ISSUE TITLE
A single metric can be of different Type: is that correct?

### ISSUE THREAD

**Issue by ioggstream** [google/mtail#130]
I'm working around metrics duplication #127 and I found that:

  - the same metric can be of different types (eg. Int, Float)

Eg.
```
	s := NewStore()
	s.Add(NewMetric("foo", "prog", Counter, Int))
	s.Add(NewMetric("foo", "prog", Counter, Float))
```

Is that fine?

**Comment by jaqx0r** [comment]
The store doesn't have any checks against this, that's correct.  It's
possible for two programs to create metrics with the same name and
different types, with different labels too, and the behaviour is undefined
in this case.  The 'prog' label is the only namespacing available so it
should be possible for two programs to do this and it all works but no
guarantees are made, really.

**Comment by ioggstream** [comment]
Can I add a test on that, to make it clear?

**Comment by jaqx0r** [comment]
Sure.
