### ISSUE TITLE
error when building on windows

### ISSUE THREAD

**Issue by nicholasfoden** [google/mtail#135]
when trying to build mtail on windows, i encounter the following error

```
...
go install -ldflags "-X main.Version=v3.0.0-rc4-136-gcbf107b -X main.Revision=cbf107b4d532a3dd830019da3c9f12c692b70544"
# github.com/google/mtail/tailer
tailer\tail.go:260:8: undefined: syscall.Stat_t
tailer\tail.go:261:18: s.Ino undefined (type interface {} is interface with no methods)
make: *** [mtail] Error 2
```

I am running go version go1.9.2 windows/amd64

building using make from msys (mingw)

**Comment by jaqx0r** [comment]
Cool, thanks! This is probably the first time someone has tried to build on
Windows. The program uses inode to detect file rotation, looks like we'll
need something different here.

**Comment by nicholasfoden** [comment]
looks like https://github.com/moriyoshi/go-fileid/blob/master/fileid_windows.go might be something in the right direction.

**Comment by jaqx0r** [comment]
Great, thanks for the tip!

**Comment by jaqx0r** [comment]
Because of the use of spf13/afero abstraction over the filesystem, I can't use moriyoshi/go-fileid directly; the latter avoids the go os package and directly syscalls.  I need a new interface layer between mtail and both libraries :/

**Comment by jaqx0r** [comment]
An alternate idea is to figure out if the inode tracking code is required at all, and thus possibly discard it.
