### ISSUE TITLE
mtail cannot produce timestamps for logs without timestamps

### ISSUE THREAD

**Issue by alkuzad** [google/mtail#142]
Hi

I started experimenting with mtail to parse old legacy program logs to metrics. However this program does not output timestamps in logs, just raw data. 

I saw that `timestamp()` function does not work without setting time previously, but `settime` and `strptime` needs input from pattern to work correctly.

How to solve this problem and use system time ? I see in debug output that labels have correct time assigned so it is possible to fetch it.

**Comment by jaqx0r** [comment]
Alright. This is either a feature or a massive oversight on my part.

mtail ought to use the system time when the log arrives if there is no
parsed timestamp, that is the behaviour of the previous internal google
version.

I can't explain why it doesn't do that in this version. I'm going to go
with:I forgot.

But it should be easy enough to add!

**Comment by jaqx0r** [comment]
Looks like the code did in fact attempt to handle this case, but not fully (as you're seeing a problem.) 
The code that sets timestamps handles the case where the thread timestamp is zero.  It's possible that somehow the timestamp is not zeroed, but I would have expected you should not need to use strptime or settime at all and this should have just worked.

Do you have an example log file and program you were using?

**Comment by jaqx0r** [comment]
I've run the linecount.mtail program which does not use strptime, and it is working correctly.  Sorry, I can't reproduce your problem.  If you can give me a way of reproducing it that would be very helpful.

**Comment by jwalzer** [comment]
Hi,
I'm using this little mtail-program to get some verification, that it's running correctly and logs are received:
```
counter mtail_lines_read_count by filename
gauge mtail_file_lastread_timestamp by filename

/.*/ {
  mtail_lines_read_count[getfilename()]++
  mtail_file_lastread_timestamp[getfilename()]=timestamp()
}
```

for all logfiles it monitors I receive the following output:
```
# TYPE mtail_file_lastread_timestamp gauge
# mtail_file_lastread_timestamp defined at default_stats.mtail:2:7-35
mtail_file_lastread_timestamp{filename="/var/log/syslog",prog="default_stats.mtail"} -62135596800
```
so, how is this supposed to be working?

Because I'm watching different logs with different (or none) time field, I can't use timestamp-field-parsing here, but would rather have the current system timestamp here.

**Comment by jaqx0r** [comment]
I think it's a bug, this is supposed to work. Thanks for the reproducible
test case.
