### ISSUE TITLE
No metrics after 'cat /dev/null'

### ISSUE THREAD

**Issue by ojle** [google/mtail#143]
Hi,

I have following scenario:

Mtail is set to watch file /tmp/test.log
I do several:
`echo "Test-Code: 999" >> /tmp/test.log` 
and everything working as expected by the .mtail rules, ie, metrics are generated
After a while, I do:
`cat /dev/null > /tmp/test.log`
and then continue to write to the file with:
`echo "Test-Code: 999" >> /tmp/test.log` 
Now mtail is no longer generating new metrics.

Running mtail 3.0.0-3

**Comment by jaqx0r** [comment]
That's an excellent bug.  I suspect the file offset is not reset when you
truncate the file (assuming that's what's happening here with the cat
dev/null.)

Can you try this with --v=2 to get verbose logs, and have a look what the
log_watcher and tailer log messages say when you try this?

**Comment by ojle** [comment]
Nothing happens
Did the same scenario above while running:
`mtail -progs /opt/mtail/ -logs /tmp/test.log --v=2`


This is the log file /tmp/mtail.INFO :

I0226 09:01:42.121855   46410 mtail.go:103] Tail pattern "/tmp/test.log"
I0226 09:01:42.121873   46410 tail.go:125] glob matches: [/tmp/test.log]
I0226 09:01:42.122105   46410 vm.go:715] Starting program test.mtail
I0226 09:01:42.135520   46410 tail.go:349] Tailing /tmp/test.log
I0226 09:01:42.135707   46410 mtail.go:290] Listening on port :3903

**Comment by jaqx0r** [comment]
Thanks!
I'm working on getting a reproducing test case at the moment.

**Comment by jaqx0r** [comment]
My test reproduction shows that this is working correctly already. You said
the version is 3.0.0-rc3, can you pull the latest please?

**Comment by ojle** [comment]
Ok, I'll check with latest

**Comment by ojle** [comment]
I installed mtail version v3.0.0-rc9
I didn't manage to test it thorough, since after running while it quickly filled up /tmp dir :), since /tmp/mtail.INFO now is generating massive logs every sec, even though v2 is not enabled

Running with
`/opt/mtail/mtail -progs /opt/mtail -logs /opt/xxx/logs/xxx.log,/opt/yyy/logs/yyy.out`

I0302 08:08:09.682566   25206 loader.go:97] Skipping /opt/yyy/logs/api.log due to file extension.
I0302 08:08:09.683000   25206 loader.go:97] Skipping /opt/yyy/logs/yyy.out due to file extension.
I0302 08:08:09.683012   25206 loader.go:97] Skipping /opt/yyy/logs/yyy.out due to file extension.
I0302 08:08:09.683252   25206 tail.go:204] File size is 473569107
I0302 08:08:09.683261   25206 tail.go:230] handletrunc with error 'no truncate appears to have occurred'
I0302 08:08:09.683437   25206 loader.go:97] Skipping /opt/yyy/logs/api.log due to file extension.
I0302 08:08:09.739822   25206 loader.go:97] Skipping /opt/yyy/logs/yyy.out due to file extension.
I0302 08:08:09.739857   25206 loader.go:97] Skipping /opt/yyy/logs/yyy.out due to file extension.
I0302 08:08:09.739940   25206 tail.go:204] File size is 473569342
I0302 08:08:09.739949   25206 tail.go:230] handletrunc with error 'no truncate appears to have occurred'
I0302 08:08:09.740044   25206 loader.go:97] Skipping /opt/yyy/logs/api.log due to file extension.
I0302 08:08:09.750941   25206 loader.go:97] Skipping /opt/xxx/logs/xxx.log due to file extension.
I0302 08:08:09.750961   25206 loader.go:97] Skipping /opt/xxx/logs/xxx.log due to file extension.
I0302 08:08:09.750970   25206 loader.go:97] Skipping /opt/xxx/logs/xxx.log due to file extension.
I0302 08:08:09.751009   25206 tail.go:204] File size is 809044678
I0302 08:08:09.751024   25206 tail.go:230] handletrunc with error 'no truncate appears to have occurred'
I0302 08:08:09.751048   25206 tail.go:204] File size is 809044678
I0302 08:08:09.751059   25206 tail.go:230] handletrunc with error 'no truncate appears to have occurred'
I0302 08:08:09.751083   25206 tail.go:204] File size is 809044678
I0302 08:08:09.751092   25206 tail.go:230] handletrunc with error 'no truncate appears to have occurred'
I0302 08:08:09.751102   25206 loader.go:97] Skipping /opt/xxx/logs/xxx.log due to file extension.
I0302 08:08:09.797904   25206 loader.go:97] Skipping /opt/xxx/logs/xxx.log due to file extension.
I0302 08:08:09.797919   25206 loader.go:97] Skipping /opt/xxx/logs/xxx.log due to file extension.
I0302 08:08:09.797923   25206 loader.go:97] Skipping /opt/xxx/logs/xxx.log due to file extension.

**Comment by jaqx0r** [comment]
Ugh. Sorry. I noticed this last week and haven't fixed the filter but I
should definitely downgrade that log message.

**Comment by jaqx0r** [comment]
Ok, please try again with the latest (rc10.)

**Comment by ojle** [comment]
The truncation part works, I got metrics after 
```cat /dev/null > /tmp/test.log```
and
``` > /tmp/test.log```
here is log

I0305 07:59:00.048057   15782 loader.go:97] Skipping /tmp/test.log due to file extension.
I0305 07:59:00.048075   15782 loader.go:97] Skipping /tmp/test.log due to file extension.
I0305 07:59:00.048109   15782 tail.go:204] File size is 0
I0305 07:59:00.048127   15782 tail.go:230] handletrunc with error '<nil>'
I0305 07:59:00.048141   15782 tail.go:204] File size is 0
I0305 07:59:00.048150   15782 tail.go:230] handletrunc with error 'no truncate appears to have occurred'
I0305 07:59:00.048181   15782 tail.go:204] File size is 0
I0305 07:59:00.048191   15782 tail.go:230] handletrunc with error 'no truncate appears to have occurred'
I0305 07:59:06.087982   15782 loader.go:97] Skipping /tmp/test.log due to file extension.
I0305 07:59:06.087999   15782 loader.go:97] Skipping /tmp/test.log due to file extension.


But still same thing with the logs, there are lots of them, nothing changed on that part.

btw, when I run --version now, I get
```mtail version  git revision  go version go1.9.2```

**Comment by jaqx0r** [comment]
Your version string is incomplete. Did you build with 'make install' ?

We now have precompiled binaries on the release page on GitHub, too.

**Comment by jaqx0r** [comment]
But it seems like the issue is resolved.

**Comment by ojle** [comment]
Yup, tried the precompiled binary and all good so far.
+1 for pushing binaries :)

**Comment by jaqx0r** [comment]
Thanks!
