### ISSUE TITLE
how to stop watching directory containing a path to be watched

### ISSUE THREAD

**Issue by laoguanjie** [google/mtail#161]
i start mtail like 
`/opt/mtail/mtail -port 9106 -progs /opt/mtail/nginx/nginx.mtail -logs /tmp/log/hao.log -v=10 -logtostderr`

and get info
`I0607 14:44:26.357992   17775 mtail.go:68] Tail pattern "/tmp/log/hao.log"
I0607 14:44:26.358018   17775 tail.go:154] glob matches: [/tmp/log/hao.log]
I0607 14:44:26.358025   17775 log_watcher.go:144] Resolved path for lookup "/tmp/log/hao.log"
I0607 14:44:26.358031   17775 log_watcher.go:121] Adding a watch on resolved path "/tmp/log/hao.log"
I0607 14:44:26.358042   17775 tail.go:373] openlogPath /tmp/log/hao.log false false
I0607 14:44:26.358048   17775 log_watcher.go:144] Resolved path for lookup "/tmp/log"
I0607 14:44:26.358052   17775 log_watcher.go:121] Adding a watch on resolved path "/tmp/log"`

actually i do not want to watch '/tmp/log'. i just want to count lines in '/tmp/log/hao.log' instead of '/tmp/log/*.log'

what can i do?

**Comment by jaqx0r** [comment]
This is working as intended, there is a watch on the directory to make sure
mtail sees log rotation happen. You've given it a single filename to watch
so other files won't be opened, because once a new file shows up it will be
compared to the log pattern you have and all other names won't match.

**Comment by laoguanjie** [comment]
@jaqx0r thx you help :)

but when i run 'echo hello >> /tmp/log/new.log'  which does not match '/tmp/log/hao.log', mtail still count this line. 

before run 'echo hello >> /tmp/log/new.log'
> curl http://localhost:9106/json
[
  {
    "Name": "nginx_line_count",
    "Program": "nginx.mtail",
    "Kind": 1,
    "Type": 0,
    "LabelValues": [
      {
        "Value": {
          "Value": 0,
          "Time": 0
        }
      }
    ]
  }
]

after run 'echo hello >> /tmp/log/new.log'
> curl http://localhost:9106/json
[
  {
    "Name": "nginx_line_count",
    "Program": "nginx.mtail",
    "Kind": 1,
    "Type": 0,
    "LabelValues": [
      {
        "Value": {
          "Value": 1,
          "Time": 1528424574409587355
        }
      }
    ]
  }
]

'LabelValues[0].Value.Value' has increased, that is not what i want, i just want to count lines in '/tmp/log/hao.log'.

contents in '/opt/mtail/nginx/nginx.mtail'
> counter nginx_line_count
/$/ {
  nginx_line_count++
}`
`

**Comment by jaqx0r** [comment]
Oh no! That's definitely a bug then!
