### ISSUE TITLE
Huge mtail output logs.

### ISSUE THREAD

**Issue by PsychoSid** [google/mtail#165]
Hi,

Running the last RC and just processing some not particularly intensive Apache log files. And the INFO output log has gone to 1.8gb in 24 hours.

$ ls -lh mtail*
lrwxrwxrwx 1 root root   55 Jun 28 03:17 mtail.INFO -> mtail.<thing>.root.log.INFO.20180628-031715.27377
-rw-r--r-- 1 root root 1.8G Jun 28 03:17 mtail.<thing>.root.log.INFO.20180628-025426.27377

The process is running as
/usr/local/bin/mtail -logs /var/log/httpd/ssl_access_log -progs /usr/local/etc/apache_metrics.mtail -log_dir /var/log

Log file created at: 2018/06/28 03:17:15
Running on machine: lpdosper50136
Binary: Built with gc go1.10.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0628 03:17:15.036155   27377 vm.go:86] Prog: apache_metrics.mtail
Metrics
        0 Metric: name=apache_http_requests_total program=apache_metrics.mtail kind=Counter type=Int hidden=false keys=[request_method http_version request_status] labelvalues=[LabelValue: [GET HTTP/1.1 200] 9683@1530181005000000000 LabelVa
lue: [GET HTTP/1.1 500] 52@1530176281000000000 LabelValue: [GET HTTP/1.1 400] 56@1530180932000000000 LabelValue: [GET HTTP/1.1 302] 6421@1530180790000000000 LabelValue: [GET HTTP/1.0 500] 74@1530180770000000000 LabelValue: [GET HTTP/1.1 404
] 851@1530181034000000000 LabelValue: [OPTIONS HTTP/1.1 302] 1@1530139497000000000 LabelValue: [POST HTTP/1.1 500] 25@1530168638000000000 LabelValue: [GET HTTP/1.1 503] 403@1530180767000000000 LabelValue: [HEAD HTTP/1.1 302] 9@1530180525000
000000 LabelValue: [POST HTTP/1.0 500] 15@1530180858000000000 LabelValue: [OPTIONS HTTP/1.1 200] 19@1530180878000000000 LabelValue: [POST HTTP/1.1 302] 196@1530180765000000000 LabelValue: [HEAD HTTP/1.0 500] 9@1530180707000000000 LabelValue
: [OPTIONS HTTP/1.1 404] 3@1530180737000000000 LabelValue: [POST HTTP/1.1 404] 31@1530181002000000000 LabelValue: [GET HTTP/1.1 502] 4@1530175752000000000 LabelValue: [PUT HTTP/1.1 404] 1@1530181021000000000] source=apache_metrics.mtail:3:9
-34
        1 Metric: name=apache_http_responses_total program=apache_metrics.mtail kind=Counter type=Int hidden=false keys=[request_method http_version request_status] labelvalues=[LabelValue: [GET HTTP/1.1 200] 9683@1530181005000000000 LabelV
alue: [GET HTTP/1.1 500] 52@1530176281000000000 LabelValue: [GET HTTP/1.1 400] 30@1530180778000000000 LabelValue: [GET HTTP/1.1 302] 6086@1530180790000000000 LabelValue: [GET HTTP/1.0 500] 74@1530180770000000000 LabelValue: [POST HTTP/1.1 5
00] 25@1530168638000000000 LabelValue: [GET HTTP/1.1 503] 403@1530180767000000000 LabelValue: [GET HTTP/1.1 404] 173@1530181006000000000 LabelValue: [POST HTTP/1.0 500] 15@1530180858000000000 LabelValue: [POST HTTP/1.1 302] 192@153018076500
0000000 LabelValue: [OPTIONS HTTP/1.1 404] 1@1530175022000000000 LabelValue: [GET HTTP/1.1 502] 4@1530175752000000000 LabelValue: [POST HTTP/1.1 404] 5@1530178243000000000] source=apache_metrics.mtail:4:9-35
...

Etc is there something in this RC with extra debug, or have I mis-configured somewhere ?

Thanks

**Comment by jaqx0r** [comment]
Yow, there's some extra debugging logs.  Sorry about that; should be an
easy fix tho.

**Comment by jaqx0r** [comment]
You should only see that specific line if the flag --dump_bytecode is set,
or if there's a program error jus tbefore it.  Is that the only line
(vm.go:86) being printed?

What version are you using -- mtail --version will tell you.

**Comment by jaqx0r** [comment]
I've tagged and pushed v3.0.0-rc15 which has fewer INFO logs, so please try
that (i.e. pull from latest HEAD at the moment.)

**Comment by PsychoSid** [comment]
Thanks, I have updated and initially looking good. Will keep an eye on it but will shut this one down now.
