### ISSUE TITLE
Log rotation frequently fails

### ISSUE THREAD

**Issue by hynek** [google/mtail#17]
Hi,

we monitor an exim log file using mtail that gets regularly rotated.

And sadly, frequently (but not always) mtail fails and fills its own log file with:

```
I0402 10:43:06.053308    2930 tail.go:139] read /var/log/exim4/mainlog: bad file descriptor
```

It there anything we can do here or is that some bug in mtail?  Anyone else experiencing this?

**Comment by jaqx0r** [comment]
Can you reproduce with more logs, i.e. run with -v=2, so we can see what is
happening around that moment?

**Comment by hynek** [comment]
I did that but tonight I found an entry that may solve the mystery:

```
I0403 00:00:02.282011    4924 tail.go:212] Seek to start on /var/log/exim4/mainlog
I0403 00:00:02.283560    4924 tail.go:244] Failed to open "/var/log/exim4/mainlog" for reading: open /var/log/exim4/mainlog: perm
Mission denied
```

I believe the rotation act contains a chmod step which is a race condition and mtail doesn’t try again to open the file.

As a temporary fix, I’m running mtail as root but it would be nice if mtail could handle this error properly.

**Comment by jaqx0r** [comment]
Do you know the sequence of syscalls that the log rotation performs? Is it
exim doing the rotation or something systemwide like logrotate?

**Comment by jaqx0r** [comment]
In the general case I think permission denied can be a retryable error
after a rotation, but a hard error at startup.  I can do an exponential
back off and retry for rotation errors, up to a threshold.

**Comment by jaqx0r** [comment]
I have a test case that reproduces this, thanks for the report!

**Comment by hynek** [comment]
Great, thanks!
