### ISSUE TITLE
HTTP request to / returns a 302

### ISSUE THREAD

**Issue by jarro2783** [google/mtail#170]
```
curl localhost:9197 -I
HTTP/1.1 302 Found
Content-Type: text/html
Date: Mon, 20 Aug 2018 01:21:03 GMT
Content-Length: 1055
```

A request to `/` returns a 302 with content. This seems wrong to me. Our monitoring system also reports that the `Location` header is missing.

**Comment by jaqx0r** [comment]
Thanks for the report; can you post the mtail version and commandline
arguments please?  (The top few lines of the INFO log would be sufficient,
too.)

**Comment by jarro2783** [comment]
Sure.

`mtail version v3.0.0-rc15 git revision 2991023ad62fd5c9512687697a7e32b56477bb28 go version go1.10.3`

`/usr/local/bin/mtail -progs /etc/mtail -logs /var/log/mail.log -port 9197 -statsd_hostport REDACTED:8125 -metric_push_interval_seconds 10`

**Comment by jaqx0r** [comment]
This looks like it's working as intended.  A HTTP request to / from a web browser follows the redirect and shows you the page.  A `curl` without the -I header does the same.

I'm not sure what curl -I is supposed to do, or what the HTTP standard says, or what the Go httpserver should be doing, but I don't think this bug belongs here, sorry.  `mtail` doesn't do anything clever with the standard library.

What problem are you trying to solve?

**Comment by jarro2783** [comment]
No there is no `Location` header, so how can it follow a redirect to anything?

It's not returning a redirect, it's returning the actual page content. So if you go to it in your browser you will just see the actual page.

`302 Found` is the wrong response here, if it's going to return content it should just be a `200`.

**Comment by jarro2783** [comment]
The problem is this line: https://github.com/google/mtail/blob/master/mtail/mtail.go#L163

`mtail` is setting the status as `http.StatusFound`.

**Comment by jaqx0r** [comment]
OHHhhhhhh.  Thanks!
