### ISSUE TITLE
Mark for Deletion or i--?

### ISSUE THREAD

**Issue by jnovack** [google/mtail#172]
I have a use-case where I would like to delete a variable... but not yet.  We are processing maillogs right from the SMTP server, and a traditional flow looks like this. (Extrapolated for simplicity)

**Since I can't do an `count[i]--`, and I can't do a `dellater count[i]`, I use an obscene amount of memory from mtail over the course of the day.**

```
Start Connection 100
Start TLS on Connection 100
Start Message 200 on Connection 100
Start SpamProcessing on Message 200
End SpamProcessing on Message 200 verdict isSpam
End Message 200
Done Message 200 
Start Message 201 on Connection 100
End Message 201
End Connection 100
Start SpamProcessing on Message 201
End SpamProcessing on Message 200 verdict isSpam
Done Message 201
```

The point here, is that the message MAY still be processing after the message "Ends", and after a connection "Ends".  I never know when all messages from a connection have been process to be able to delete the connection.

I cannot delete the connection object at "End Connection" because data in it is still needed (for example, the TLS flag is by Connection).

I don't know what the right solutionis , but I'm suggesting being able to use counter-- ONLY in hidden fields for tracking.

I could:
* `messages_on_conn[$connID]++` on a "Start Message",
* `messages_on_conn[$connID]--` on the "Done Message", and
* `messages_on_conn[$connID] == 0`, then del `messages_on_conn[$connID]`

**Comment by jaqx0r** [comment]
Thanks for the report!

Are you using the suggestion in those bullets at the end at the moment?  I
guess not because mtail doesn't have --.  You could in the interim use foo
= foo - 1 form.  I'll add -- because it seems logical to have it for
symmetry.

Your report gives me another idea too -- in issue #84 I decided to add an
option to remove metrics after some timeout, but never figured out how.
You've suggested dellater, but I think it'd be easy to write "del foo[bar]
after 24h" as the syntax.

**Comment by jnovack** [comment]
> You've suggested dellater, but I think it'd be easy to write "del foo[bar] after 24h" as the syntax.

Just threw it out there, was not making a formal declaration of syntax.  I do like `after (\d+)units`.

I'm my use case, `del foo[bar] after 5m` would be a much simpler solution for the end user (than tracking connection messages via `i++`/`i--`), it prevents them having to write additional logic.

But I didn't want to rule out `i--` as it did seem helpful and consistent.

**Comment by jaqx0r** [comment]
Yep, understood.  Both are good ideas, so I'm going to do both.

Making the metrics expire after a timeout is tricky, but the decrement
operator is now available.

**Comment by jaqx0r** [comment]
Please try out the new syntax, and let me know how it goes.
