### ISSUE TITLE
expose go + mtail metrics

### ISSUE THREAD

**Issue by roidelapluie** [google/mtail#174]
I would like to have an endpoint with metrics on the prometheus format

```
go_gc_duration_seconds_count                                                                                                              
go_gc_duration_seconds{quantile="0"}
go_gc_duration_seconds{quantile="0.25"}
go_gc_duration_seconds{quantile="0.5"}
go_gc_duration_seconds{quantile="0.75"}
go_gc_duration_seconds{quantile="1"}
go_gc_duration_seconds_sum
go_goroutines
go_info{version="go1.10.3"}
go_memstats_alloc_bytes
go_memstats_alloc_bytes_total
go_memstats_buck_hash_sys_bytes
go_memstats_frees_total
go_memstats_gc_cpu_fraction
go_memstats_gc_sys_bytes
go_memstats_heap_alloc_bytes
go_memstats_heap_idle_bytes
go_memstats_heap_inuse_bytes
go_memstats_heap_objects
go_memstats_heap_released_bytes
go_memstats_heap_sys_bytes
go_memstats_last_gc_time_seconds
go_memstats_lookups_total
go_memstats_mallocs_total
go_memstats_mcache_inuse_bytes
go_memstats_mcache_sys_bytes
go_memstats_mspan_inuse_bytes
go_memstats_mspan_sys_bytes
go_memstats_next_gc_bytes
go_memstats_other_sys_bytes
go_memstats_stack_inuse_bytes
go_memstats_stack_sys_bytes
go_memstats_sys_bytes
go_threads
```

And mtail metrics (reloads, runtime errors)

```
mtail_program_loader_compile_errors_total{progs="foo.mtail"}
mtail_program_loader_load_total{progs="foo.mtail",status="error"}
mtail_program_loader_load_total{progs="foo.mtail",status="success"}
mtail_program_loader_runtime_errors_total{progs="foo.mtail"}
mtail_watched_files_errors_total
mtail_watched_files_rotations_total
mtail_watched_files_truncations_total
mtail_watched_files_lines_read_total
```

Both could be on the same endpoint.

**Comment by jaqx0r** [comment]
Me too :)

I have been procrastinating on adding the prometheus go client directly
because I haven't yet figured out how to merge the mtail metric store
(which supports more than just prometheus export) with the prom client.

Thanks for filing the bug, it'll remind me to do it :-)

**Comment by roidelapluie** [comment]
I would also be happy to have 2 endpoints .. /metrics and /mtailmetrics for example

**Comment by jaqx0r** [comment]
I'm not satisfied by that, so I'm going to continue researching how to
integrate them.

**Comment by finkr** [comment]
Hello,

As far as I understand, this issue contains two different enhancements requests:
1. the endpoint metrics, typically gathered by prometheus library
2. mtail metrics (reloads, runtime errors).

If I understand correctly, the endpoint metrics is difficult to add to /metrics, since that involve merging *the mtail metric store  with the prom client* (@jaqx0r).

However, the second part, might be much easier, since it involve adding mtail metrics to mtail metric store.

A distinct issue could be useful to track the progress separately. Shall I open it ?

Regards

**Comment by roidelapluie** [comment]
According to me, the mtail metric store should comply to the Collector and Gatherer prometheus interfaces.

**Comment by jaqx0r** [comment]
@roidelapluie yes, I think that's the way to do it, thanks!  I don't fully understand how it works though from a brief scan of the Prometheus go client code.

**Comment by jaqx0r** [comment]
OK, try release rc24.

**Comment by roidelapluie** [comment]
Awesome. I will give it a try really soon.
