### ISSUE TITLE
[Question] Loadable Plugins?

### ISSUE THREAD

**Issue by jnovack** [google/mtail#178]
Question for the future, definitely not near future (considering you are close to a release).

With Go permitting plug-in architecture in recent builds, have you given thought to separating the tailing functions from the metrics processing function to be incorporated as a plugin?

You have a phenomenally structured and well-built tailing function. I wouldn't want to duplicate efforts for another project considering yours has been put through tests and real-life examples.

I wanted to write a "tail-to-syslog forwarder" (multiplatform, but specifically for windows clients, as there currently is none), but realized I'd be duplicating most of your tailing and filewatching code.  

I realize the syslog forwarding is out of scope of this project, that's why I was curious about the loadable plugins potential.

**Comment by jaqx0r** [comment]
I don't know about making it a plugin, but it could be turned into it's own package to be imported into your own code...

**Comment by jnovack** [comment]
This is the same ball-park of a question as #199. 

Closing this as discussion is better over there.
