### ISSUE TITLE
[Workaround] VM thinks IP is a Float

### ISSUE THREAD

**Issue by jnovack** [google/mtail#179]
I was trying to capture an IP address to be used as a label.  Unfortunately, the internal VM thinks it's a float. 

```
hidden text ipaddr 
/ip address (\d+\.\d+\.\d+\.\d+)/ {
    ipaddr = $1
}
```
```
## cat "ip address 1.1.1.1" > log.txt
mtail version v3.0.0-rc16 git revision 77eeba903db0ffd90e29c1ee778fdefb0112bfab go version go1.11
vm.go:76] maillogs.mtail: Runtime error: conversion of "1.1.1.1" to float failed: strconv.ParseFloat: parsing "1.1.1.1": invalid syntax
```

It gets parsed as a Float. because 1.1.1.1 looks like a float with two extra decimal points and fails.

```
hidden text ipaddr 
/ip address (\d+\.\d+\.\d+\.\d+)/ {
    ipaddr = "$1"
}
```

Gets parsed as a String, and returns `"$1"`, which is unhelpful.

I need a way to explicitly type cast, especially in the case of IP addresses, or acknowledge the type at the definitions (I told it should be text, I don't care if it's an int or a float, make it text).

Perhaps a built-in function of `toInt()`, `toString()` or `toFloat()`?

Current Workaround:
```
/ip address (\d+)\.(\d+)\.(\d+)\.(\d+)/ {
    ipaddr = $1 + "." + $2 + "." + $3 + "." + $4
}
```

**Comment by jaqx0r** [comment]
--dump_ast and --dump_ast_types will print out the internal representation
of the program and explain what it things the type of $1 is.  There's
explicit code to not cast to float if more than one \. is seen, so of
course I'm curious :-)

**Comment by jaqx0r** [comment]
FYI there's a builtin function `string()` which should do the cast you were asking for originally.    I just realised it's not documented.
