### ISSUE TITLE
Failure to create log watcher: function not implemented

### ISSUE THREAD

**Issue by jakirpatel** [google/mtail#193]
mtail version: **v3.0.0-rc16**
mtail log: 
mtail.INFO file: 
```
Log file created at: 2018/11/09 11:30:38
Running on machine: xxxxxxxxxxx
Binary: Built with gc go1.11 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1109 11:30:38.922992    6118 main.go:93] mtail version v3.0.0-rc16 git revision 77eeba903db0ffd90e29c1ee778fdefb0112bfab go version go1.11
I1109 11:30:38.923149    6118 main.go:94] Commandline: ["./mtail" "--compile_only" "--progs" "progs/example.mtail"]
F1109 11:30:38.923165    6118 main.go:118] Failure to create log watcher: function not implemented

```

systeminfo: 

```
Linux xxx.xxx.xxx.xxx 2.6.18-274.el5 #1 SMP Fri Jul 22 04:43:29 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
```
I tested with the other kernal version and it seems working, 

```
Linux xxx.xxx.xxx.xxx 4.4.110-1.el7.elrepo.x86_64 #1 SMP Fri Jan 5 11:35:48 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by jakirpatel** [comment]
Thank you for your reply @jaqx0r 

Some of my comments: 
It supports notify. I think polling should work for me... 
If there is some error in inotify then mtail should tell to use polling... Also, I encountered a similar problem while reading the log from NFS... 

Initially, it was not able to read the lines (due to inotify maybe) but after polling, it was able to.. I think mtail should give an error in terms if it is not tailing the file. Or suggest using polling. :)

**Comment by jaqx0r** [comment]
inotify doesn't work for NFS filesystems so this is unexpected -- but what sho;dn't happen is mtail fail to start.

Can you add the flag `--poll_interval=250ms` and try it again?

Perhaps mtail can trap the error you reported and attempt to turn polling on in that case -- or just default to it on.

**Comment by jakirpatel** [comment]
Hello @jaqx0r 
Not sure if mtail is trapping the error and switching to poll... I'll try it and let you know.

**Comment by jakirpatel** [comment]
@jaqx0r I started the same process with polling. I got the same error: 

`Failure to create log watcher: function not implemented
`

**Comment by jaqx0r** [comment]
Can you do this one more time please, with flags `--logtostderr --vmodule=log_watcher=2` and paste the whole log here?

**Comment by jaqx0r** [comment]
Thanks!
