### ISSUE TITLE
Can I clear read log line from remote?

### ISSUE THREAD

**Issue by yoko-chance** [google/mtail#194]
Now I am trying to realize log monitoring.
It simply counts line that matched "/error/".
And catch it with Prometheus's alert rule.

The trouble is that I cannot withdraw alert.
Because it cannot be reset to 0 once it is counted.

I understand to can clear read line when restart mtail.
But I think it is terrible way, I want to control from remote.

Is there a solution?
Or is my use wrong?

**Comment by jaqx0r** [comment]
You want the alert to go away after some time.  Let's say that's 5 minutes
after the alert fires.

What you need is to compute the rate of change of the error counter you're
exporting from mtail.

So, if your exported metric is called 'error', then you can write a
Prometheus recording rule that looks like:

name: error:rate
expr: rate(error, 5m)

or something like that (I'm going from memory, and you'll have to check the
Prometheus documentation.)

This makes a new timeseries of the 5m rate of change of the value.  So if
it's constant for 5 minutes, the rate will be zero.  If the error counter
increases, then the rate will go above zero.

Then you can use that rule to generate your alert; if the rate is above
zero then fire the alert, if it's zero (or under?) then the alert is no
longer triggered.

alert: Error
expr: error:rate > 0

(hopefully you get the idea.)


The main points are: mtail can only really count events (ignoring
extracting values from the log lines); prometheus has a powerful timeseries
processing language, which you can use to analyze the timeseries created
from the collected metrics.

**Comment by yoko-chance** [comment]
Thank you, it muth better than firing forever.

Though I want manually stop an alert.
e.g. when it is necessary to investigate the cause of an error,  I would like to issue an alert until the investigation and coping are completed.
Is that matter that other than mtail?

- - -

It did well.
```
# error is that sent from mtail
groups:
  - name: Error Count
    rules:
      - record: error_rate
        expr: rate(error[5m])
      - alert: Error Count
        #expr: error > 0
        expr: error_rate > 0
```

**Comment by jaqx0r** [comment]
That sounds like you want to use the Prometheus Alertmanager...

**Comment by yoko-chance** [comment]
I am grateful for your help.
I well look up Prometheus Alertmanager.

**Comment by jaqx0r** [comment]
No problem.  Good luck!
