### ISSUE TITLE
how to run with many progs in a process 

### ISSUE THREAD

**Issue by 249510573** [google/mtail#197]
I want to collect three logs with three progs in a process like follow。 it does not work。 how can I do ?

mtail --progs ./progs/apache2_metrics.mtail --logs /var/log/apache2/keystone_metrics.log,/var/log/apache2/nova_placement_metrics.log \
--progs ./progs/apache2_common.mtail --logs /var/log/apache2/keystone_common.log,/var/log/apache2/nova_placement_common.log \
--progs ./progs/apache2_combined.mtail --logs /var/log/apache2/keystone_access.log,/var/log/apache2/nova_placement_access.log \
-metric_push_interval_seconds 30

Thanks!

**Comment by jaqx0r** [comment]
The progs flag takes a directory path containing all programs you want to
run. Just pass -progs once with ./progs

It looks like you're trying to restrict each program to a subset of logs
which is a great idea, but doesn't work.
