### ISSUE TITLE
Parsing non-ordered fields (json)

### ISSUE THREAD

**Issue by NoumanSaleem** [google/mtail#20]
Hi,

My application outputs JSON formatted logs, which are do not have a guaranteed order of keys.
I'd like to capture key/value pairs by having capturing groups that look like: 
`/\\\"name\\\":\\\"(?P<application>[A-Za-z\-]+)/`

Is there a mechanism to allow executing multiple matches against a single line in order to aggregate capturing groups?

thank you!

**Comment by jaqx0r** [comment]
I think you can do this with nested match blocks, like so:

/re1/ {
  /re2/ {
   ...
  }
}

But there is no way to do it in a single match expression at the moment.

It depends on the regular expression engine, and mtail uses the go standard
re library. redgrep is an interesting project that uses regular expression
derivatives which allows you to compose unordered groups like this.

**Comment by NoumanSaleem** [comment]
@jaqx0r thanks for the top, works great!
