### ISSUE TITLE
Segfault when using LogWatcher with enableFsnotify=false

### ISSUE THREAD

**Issue by sgtsquiggs** [google/mtail#209]
Specifically here:
https://github.com/google/mtail/blob/de0e167e25c5f30e33d479c65d0bcd9a9953d7e3/internal/watcher/log_watcher.go#L57

`watcher` will be nil, so when this code is executed:
https://github.com/google/mtail/blob/de0e167e25c5f30e33d479c65d0bcd9a9953d7e3/internal/watcher/log_watcher.go#L194

you receive a core dump :)

**Comment by jaqx0r** [comment]
Thanks! I have a fix for this but it's tied up in a bigger change. I'll try
to extract it out...
