### ISSUE TITLE
file globs

### ISSUE THREAD

**Issue by NoumanSaleem** [google/mtail#21]
Would be very helpful if `/var/logs/*-request.log` style paths were supported

thanks!

**Comment by jaqx0r** [comment]
Is there any time a glob like that would match files you didn't want to
tail?

**Comment by jaqx0r** [comment]
Are all the files going to get matched by the same mtail program, are they
from the same source application?

**Comment by NoumanSaleem** [comment]
@jaqx0r my particular use case is for parsing docker container logs using mtail. Docker will output the logs into `/var/lib/docker/containers/{container-id}/{container-id}-json.log`

**Comment by jaqx0r** [comment]
OK, thanks.  This should be relatively straightforward to add because the
directory containing the files is already watched for changes, that watch
can be modified to do a glob match.

**Comment by mattbostock** [comment]
I'd also find this very useful.
