### ISSUE TITLE
Optional/unordered fields in ligne?

### ISSUE THREAD

**Issue by Xaelias** [google/mtail#217]
Hi (me again, sorry, promise it's the last question :-D )
I'm trying to match something, and I wanted to have bit of freedom while doing so.
That is that given a list of fields definition, these fields may or may not be in the line currently being parsed, and they may be in a random order.
I couldn't find a way to do this with the regular syntax. And then I went into decorators, but it looks like if a decorator isn't matched, then the whole thing "fails".
Is there a way to work around that? Or give a default value to things that don't exist?
Thanks!

**Comment by jaqx0r** [comment]
Currently the only way to do this is to specify multiple different match patterns at the same level in your program; each will be attempted and the ones that match will have their blocks executed.

So as long as you have a fragment of the regex you can put them all next to each other.

```
hidden text a
hidden text b
/a=(\s+)/ {
  a=$1
}
/b=(\s+)/ {
  b=$1
}
```
You can then refer to the values of `a` and `b` later on:
```
counter foo by a,b

{
foo[a][b] ++
}
```

This works if you have something you can trigger on when you know you have all the information.

The https://github.com/google/mtail/blob/master/examples/mysql_slowqueries.mtail program demonstrates how to fetch partial information from a multiline dump, and then turn it into a metric, e.g from this sort of log:

https://github.com/google/mtail/blob/master/internal/mtail/testdata/mysql_slowqueries.log

**Comment by Xaelias** [comment]
(sorry I thought I had put the label in there)
That actually makes a lot of sense. I just didn't think to use the hidden variable for that ><

That could help make my regex way easier to read and update!

Thanks!

PS: Thanks a lot to everyone who wrote mtail. It works really well.
