### ISSUE TITLE
How to ignore some archive files in a log folder

### ISSUE THREAD

**Issue by xuyun1976** [google/mtail#219]
Mtail seems don’t support to exclude the *.gz files in the command. If I execute the command ‘mtail -log /home/logs/access/* --progs ……’, the mtail can’t generate metic. And I didn’t find that other useful regular expression can support the case by mtail. I also tried to use 'getfilename() !~ /?gz/' in config file, but it also didn't work.  I listed the files in access log folder. Where is I missed?

---------------------------------------
-rw-r--r-- 1 root root  1566017 Mar 19 09:15 1548885052638-13757.gz
-rw-r--r-- 1 root root  1525432 Mar 19 09:20 1548885052638-13758.gz
-rw-r--r-- 1 root root  1645235 Mar 19 09:25 1548885052638-13759.gz
-rw-r--r-- 1 root root  1600131 Mar 19 09:30 1548885052638-13760.gz
-rw-r--r-- 1 root root  1685326 Mar 19 09:40 1548885052638-13762.gz
-rw-r--r-- 1 root root  1638019 Mar 19 09:45 1548885052638-13763.gz
-rw-r--r-- 1 root root  1628696 Mar 19 09:50 1548885052638-13764.gz
-rw-r--r-- 1 root root  1729051 Mar 19 09:55 1548885052638-13765.gz
-rw-r--r-- 1 root root  1736072 Mar 19 10:00 1548885052638-13766.gz
-rw-r--r-- 1 root root  1655519 Mar 19 10:05 1548885052638-13767.gz
-rw-r--r-- 1 root root  1761464 Mar 19 10:10 1548885052638-13768.gz
-rw-r--r-- 1 root root 14411664 Mar 19 10:15 1548885052638-13769
-rw-r--r-- 1 root root  1527763 Mar 19 10:16 1548885052638-13770
-rw-r--r-- 1 root root   204104 Feb 20 17:11 1548885052638-6076.gz
drwxr-xr-x 2 root root    20480 Mar 19 09:53 archive/

**Comment by jaqx0r** [comment]
Yep, it currently treats every file it is told to read as text. It doesn't
unzip log files.

Let's add a flag to exclude a pattern from being read.

**Comment by jnovack** [comment]
Does #232 close this? #cleanupcrew

**Comment by jaqx0r** [comment]
I reckon it does.  Try `--ignore_filename_regex_pattern` to filter out paths.
