### ISSUE TITLE
Histogram type incompatible with one_shot and /json: unsupported value +Inf

### ISSUE THREAD

**Issue by bramblek1** [google/mtail#223]
I discovered when testing new programs with v3.0.0-rc29 that oneshot mode cannot be used with a prog which declares a histogram. The same problem is apparent when using the /json http route.

```
I0403 13:48:35.780212    9707 main.go:94] mtail version v3.0.0-rc29 git revision b5aa95d10fb3af7b843e3814bc65aedd983425d9 go version go1.11.6 go arch amd64 go os linux
I0403 13:48:35.780291    9707 main.go:95] Commandline: ["./mtail_v3.0.0-rc29_linux_amd64" "-logtostderr" "-logs" "examples/shc_es_shm1.scheduler.log" "-progs" "bug/"]
I0403 13:48:35.781837    9707 loader.go:220] Loaded program example.mtail
I0403 13:48:35.781861    9707 loader.go:239] Program example.mtail has goroutine marker 0x6578616d
I0403 13:48:35.781931    9707 vm.go:763] Starting program example.mtail
I0403 13:48:35.781953    9707 loader.go:243] Started example.mtail
I0403 13:48:35.782092    9707 tail.go:246] Tailing /home/andrewb/dev/mtail-splunk/examples/shc_es_shm1.scheduler.log
I0403 13:48:35.782158    9707 store.go:136] Starting metric store expiry loop every 1h0m0s
I0403 13:48:35.782202    9707 tail.go:397] Starting log handle expiry loop every 1h0m0s
I0403 13:48:35.782225    9707 mtail.go:316] Listening on [::]:3903
I0403 13:48:43.885109    9707 json.go:23] error marshalling metrics into json:json: error calling MarshalJSON for type *metrics.Store: json: unsupported value: +Inf
```

Simple prog which causes the issue
```
histogram json_marshal buckets 1,2,4,8,16,32

// {
  json_marshal = 1
}
````

**Comment by jaqx0r** [comment]
Thanks! That codepath is untested... Do you rely on the json format?

**Comment by bramblek1** [comment]
You're welcome. I'm not relying on the JSON output , but make use of one_shot mode when developing new programs. Prometheus output seems OK but I did not look too closely nor at any of the other exposition formats.

**Comment by jaqx0r** [comment]
OK thanks for the extra info.  I'll dig into this and get back to you.

**Comment by SuperQ** [comment]
I also use one-shot mode for testing. I wish there was a one-shot-prom format. :)

**Comment by siebenmann** [comment]
Like several other people who've already commented, I use (or want to use) one-shot mode for testing mtail programs that have histograms (among other counters), especially because I'll be exporting to Prometheus. And like @SuperQ, I'd love a one-shot Prometheus metrics format as an option.

Right now, my workaround is to start another copy of mtail on a different port, pointing to a logfile that's empty. Once it's started, I append my test data to the file with `cat testdata >>testlog`, then check the metrics endpoint to see what mtail has generated. But this is awkward and I'm not sure it'd work well if I had a lot of test data.

**Comment by jaqx0r** [comment]
Acknowledged. The json format was never intended to be anything more than
debugging, and mtail should let you test with a production format.

I want to remove the json endpoint and standardise on openmetrics. Seems
everyone is ok with that.

**Comment by jaqx0r** [comment]
4e8b829b9333346fc82c8a5ee253c07c8a87e105 fixed this just now
