### ISSUE TITLE
[Question] strptime with unix timestamp

### ISSUE THREAD

**Issue by sevaTechoPark** [google/mtail#224]
Could you help me?
How to write format for unix timestamp(seconds after 1970 - 1554220313.860 sec) in strptime?

**Comment by sevaTechoPark** [comment]
maybe strptime($unixTimestamp_date, "1136214245") ?

**Comment by jaqx0r** [comment]
Hi!

This is not well documented, but you're looking for the settime function.
See
https://github.com/google/mtail/blob/master/docs/Language.md#builtin-functions
