### ISSUE TITLE
outdated mtail version in dockerfile

### ISSUE THREAD

**Issue by sevaTechoPark** [google/mtail#225]
check it please

**Comment by jaqx0r** [comment]
Can you give some more information please?  What did you see and how did you build it?

`make container` generates the correct version for me so I don't understand the problem.

**Comment by jaqx0r** [comment]
I've just added a container build step to the CircleCI config to catch any docker problems.

https://circleci.com/workflow-run/5dd6f700-0143-4139-8799-ac7ebaa71566 is the first success

**Comment by sevaTechoPark** [comment]
I am sorry
I was wrong and in vain raised a panic

**Comment by jaqx0r** [comment]
Hey no problem! You inspired me to make the Docker build part of the CI .
