### ISSUE TITLE
First custom bucket in histogram metric not created correctly

### ISSUE THREAD

**Issue by biz812** [google/mtail#226]
Hi,

I've noticed there a problem with the first bucket in a custom histogram, in that it doesn't appear to be created correctly or, possibly, at all.

I am using:
`mtail_build_info{branch="HEAD",goversion="go1.11.6",revision="b5aa95d10fb3af7b843e3814bc65aedd983425d9",version="v3.0.0-rc29"} 1`

I am running mtail as follows:
`/usr/local/sbin/mtail -progs /tmp/mtail/foo.mtail -logs /tmp/foo.log`

You can reproduce using this simple program:
```
histogram foo_requests buckets 2, 4, 6 by foo

/^(?P<foo>[a-z]+) (?P<time>\d+)$/ {
  foo_requests[$foo] = $time
}
```

When you create a log entry with a value greater than the first bucket you get metrics:
```
# echo "b 3" >> /tmp/foo.log

# curl -s localhost:3903/metrics|grep request
# HELP foo_requests defined at foo.mtail:1:11-22
# TYPE foo_requests histogram
foo_requests_bucket{foo="b",prog="foo.mtail",le="4"} 1
foo_requests_bucket{foo="b",prog="foo.mtail",le="6"} 1
foo_requests_bucket{foo="b",prog="foo.mtail",le="+Inf"} 1
foo_requests_sum{foo="b",prog="foo.mtail"} 3
foo_requests_count{foo="b",prog="foo.mtail"} 1
```
But you'll notice that the `le="2"` is not there and set to `0` as you would expect.

When you make a request that falls into the first bucket (`0-2`):
```
# echo "c 1" >> /tmp/foo.log

# curl -s localhost:3903/metrics|grep request
# HELP foo_requests defined at foo.mtail:1:11-22
# TYPE foo_requests histogram
foo_requests_bucket{foo="b",prog="foo.mtail",le="4"} 1
foo_requests_bucket{foo="b",prog="foo.mtail",le="6"} 1
foo_requests_bucket{foo="b",prog="foo.mtail",le="+Inf"} 1
foo_requests_sum{foo="b",prog="foo.mtail"} 3
foo_requests_count{foo="b",prog="foo.mtail"} 1
foo_requests_bucket{foo="c",prog="foo.mtail",le="4"} 0
foo_requests_bucket{foo="c",prog="foo.mtail",le="6"} 0
foo_requests_bucket{foo="c",prog="foo.mtail",le="+Inf"} 0
foo_requests_sum{foo="c",prog="foo.mtail"} 1
foo_requests_count{foo="c",prog="foo.mtail"} 1
```

You can see that for `foo="c"` no buckets are populated, but the `sum` and `count` metrics do appear to have processed the record.

I think that's probably all the info you need, however if you require anything further please let me know.

Thanks for maintaining a great piece of software!

Best regards,
Mike Hobbs

**Comment by jaqx0r** [comment]
Yowch! Thanks for the report and the excellent reproduction info.

**Comment by jakirpatel** [comment]
I observed the similar behavior @jaqx0r. 

Program: 
```

counter exalogic_requests_length_bytes by otd, app
counter exalogic_requests_status_count by otd, app, status

#Adding the new histogram syntax
histogram exalogic_requests_time_seconds buckets 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15 by otd, app

#Getting the filename: This will differentiate with the OTD
getfilename() =~ /[^\/]+\/[^\/]+\/otd\/[^\/]+\/net-(?P<otd>[^\/]+)\/logs\/(?P<app>[^-]+)/

def otdlog {
    /\S+\s+\S+\s+\[[^\]]+\]\s+"[^"]+"\s+(?P<status>\d+)\s+(?P<content_length>\d+)\s+\S+\s+(?P<duration>\d+)/ {
    next
    }
}

@otdlog {
        exalogic_requests_length_bytes[$otd][$app] += $content_length
        exalogic_requests_status_count[$otd][$app][$status]++
    	exalogic_requests_time_seconds[$otd][$app] = $duration * 0.000001
}

```
Please check following output:

```
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="0.01"} 65
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="0.025"} 93
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="0.05"} 93
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="0.1"} 93
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="0.25"} 94
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="0.5"} 95
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="1"} 97
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="2.5"} 97
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="5"} 97
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="10"} 97
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="15"} 97
exalogic_requests_time_seconds_bucket{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail",le="+Inf"} 97
exalogic_requests_time_seconds_sum{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail"} 25.337999999999873
exalogic_requests_time_seconds_count{app="rpagecat",otd="otd13",prog="otdAccessLogs.mtail"} 10849
```



My observation:

1. Here the first bucket is not created. 
2. Also the <basename>_count and <basename>_bucket{le="+Inf"} is having the huge difference. 
3. The calculations histogram_quantile() does is wrong.

**Comment by biz812** [comment]
It seems as though you can work around this bug by adding a first bucket of 0 @jakirpatel

**Comment by jakirpatel** [comment]
Thank you @biz812. I used -1 and it worked.

**Comment by antong** [comment]
Still, observations of values zero (or less) will be counted but not added to the lowest bucket. The lower limit is exclusive (a range `r` contains a value if `r.Min < v && v <= r.Max`) and the first implicit bucket has the lower limit 0.

This may be the intended behaviour, but caught me by surprise. I would have expected the histogram to behave similarly to the Prometheus client's `Histogram.Observe()`.

**Comment by jaqx0r** [comment]
That's possibly a bug, then. I'd say the simplest answer is to not have an
implicit zero, or have one and a -inf as well. Not sure which is easier to
understand or has least impact on existing uses.
