### ISSUE TITLE
Mtail should allow sampling over logs

### ISSUE THREAD

**Issue by jakirpatel** [google/mtail#233]
Type: Enhancement

We are parsing around the 40k lines per second to get the Avg. Response Time of the applications over legacy platforms. 

However after improving a lot on mtail side (in terms of performance) we are still facing delays with higher traffic. 

However the Avg. doesn't really need the parsing all logs. My idea is:

1. Allow X% logs to be sampled from N lines per second. 
2. Mtail should parse only X% logs. And skip other lines. 

So we ll get the Avg. result not having the delay.

**Comment by jaqx0r** [comment]
Neat idea. Please can you write a program and/or command line demonstrating
how you'd want to use it?

**Comment by jakirpatel** [comment]
In my opinion this command line would be better. 
I would propose to add two flags: 

--sample-percentage : default 0 to 100% 
--sample-after : If you get more than N number of lines in M time. 

So ideally if I am getting 35k(highest threshold) lines per second. I should start mtail with flags. 
--sample-percentage 50 
--sample-after 35000

This should parse only 35000/2 lines per second. However this should be applied for only Average Metrics. 

1. Calculating response time avg.
2. Calculating Percentile. 

This flag should not be used with the **Counters**. 

What do you think ?

**Comment by jakirpatel** [comment]
However I can help you to implement this. Will take little time.

**Comment by ferringb** [comment]
Thoughts on just using a rule like thus?
```
hidden counter linecount
getfilename() == "your.log" {
  linecount++
  linecount == 1000 {
    linecount = 0
    <put your matching rules here>
  }
}
```
The pattern is a bit unwieldy, but it should work.  Implementing what you're asking for would require associating with a given log a sampling rate- which doesn't really align w/ how mtail handles logs.  That leaves you with only the option of global sampling rate which has it's own downsides.

**Comment by jakirpatel** [comment]
@ferringb 

Thats right. Maybe I can try this out first. Thank you for your suggestion.

**Comment by ferringb** [comment]
A potential enhancement here would be thus:
```
getfilename() == "your.log" {
  getfilelinecount() % 1000 == 0 {
    <put your matching rules here>
  }
}
```
I could see syntax for that being potentially useful- and mtail already has line count metrics in some fashion internally, so I would *guess* it wouldn't require major surgery.

That said, I'm not a maintainer, so I could be completely offbase here...

**Comment by jaqx0r** [comment]
I'm happy to add this if you want to make a PR.  Look for how getfilename
is implemented, and you should be able to plumb this into the parser and vm
without much issue.

**Comment by jakirpatel** [comment]
> Thoughts on just using a rule like thus?
> 
> ```
> hidden counter linecount
> getfilename() == "your.log" {
>   linecount++
>   linecount == 1000 {
>     linecount = 0
>     <put your matching rules here>
>   }
> }
> ```
> 
> The pattern is a bit unwieldy, but it should work. Implementing what you're asking for would require associating with a given log a sampling rate- which doesn't really align w/ how mtail handles logs. That leaves you with only the option of global sampling rate which has it's own downsides.

Dont you think this will actually parse everything ? because it will match the rule. There is no wait. How we can skip N number of lines with M amount of time. 


@jaqx0r  @ferringb

**Comment by jaqx0r** [comment]
You're right that the program suggested will still receive every line, but
it should be faster when it does not want to do any parsing because it
should give up immediately 999/1000 times.

**Comment by jakirpatel** [comment]
@jaqx0r 

I tried the way we talked to add sampling. Seems it's not working. Any other workaround do you suggest ? 


Also , 

I encountered the problem with KILLING process. The process is not itself killed after using the kill command. 

I used **-9** signal to kill the process.

**Comment by jaqx0r** [comment]
I don't have another suggestion for sampling at this time without any
information on why it's not working.   I'll rely on your experimentation to
find one.

Regarding the process kill, did anything appear in the log when you did
so?  What did the process table indicate the process was doing?  (ps
-efwww  | grep mtail for example should tell you.)

Without any other information the only guess I have for it not exiting
immediately is that it was blocked in an IO syscall inside the kernel at
the time.

**Comment by jnovack** [comment]
> Dont you think this will actually parse everything ? because it will match the rule. There is no wait. How we can skip N number of lines with M amount of time.

Skipping still requires a count, which is all mtail is doing anyway.  There's no way to tell the OS to "do not give me the next 999 lines".

Unless you know the exact size of every line, you can't just fseek(+80*999).

**Comment by jakirpatel** [comment]
@jnovack  Actually that doesnt solve my problem. I am still facing the issue related with the delay in parsing. 

NFS is overhead that we realized.

**Comment by jaqx0r** [comment]
I think this is a case of me not understanding what the real performance issue is. Since this bug was filed, mtail has dropped inotify support in lieu of poll only, and a couple of substantial performance improvements in the metrisc store and export have been added.  I am going to close this issue and hoep that a new request includes some profiling information.

Thanks!
