### ISSUE TITLE
Deleted files being kept open (regression)

### ISSUE THREAD

**Issue by schweikert** [google/mtail#237]
It seems that the issue fixed in #129 reappeared. I can reproduce that files that were opened via wildcard and then afterwards deleted, are kept open. I reproduced with mtail 3.0.0-rc16 and 3.0.0-rc29

**Comment by schweikert** [comment]
For the records: I just confirmed with rc29 that deleted files are closed after 24 hours, which is OK for us.

**Comment by jaqx0r** [comment]
Thanks for the confirmation!
