### ISSUE TITLE
nil pointer error when parse

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/mtail#239]
According to the predicate of `if statement`, `p` may be `nil`, then `p.errors` may cause nil pointer error.
https://github.com/google/mtail/blob/f48bc41ab6cb834b39e0bde3427f248dc6851dca/internal/vm/parser/driver.go#L37-L39

**Comment by jaqx0r** [comment]
My understanding of https://golang.org/ref/spec#Logical_operators is that
p.errors won't be evaulated if p is nil.

**Comment by QiAnXinCodeSafe** [comment]
@jaqx0r 
I think you should check it again.
if p is nil, `return nil, p.errors` will be evaluated.

**Comment by jaqx0r** [comment]
Ohhhhh!  Thankyou!
