### ISSUE TITLE
Support for Float values

### ISSUE THREAD

**Issue by SuperQ** [google/mtail#24]
The Prometheus native data format is float64, but it appears mtail only stores metrics as int.  It would be nice to be able to capture float values, for example `3.14` as a value in seconds.

**Comment by jaqx0r** [comment]
It sure would! I have a branch partially implementing multiple storage
types in progress.

**Comment by SuperQ** [comment]
Great, let me know if I can be any help.

**Comment by lamont** [comment]
I'd love to help test as well. I have some logs with seconds as seconds, and I'd like to convert to ms. I suspect I could partially do it with regex but it would be nicer if I could just use the comparisons on the float value.

**Comment by jaqx0r** [comment]
There's a lot of int assumptions baked through the VM, making it a small challenge. I've got a plan though, so now I only need time.

**Comment by jaqx0r** [comment]
I'm knee deep in compiler internals, building a semantic checker so I can add types to the expressions so that the correct instructions are generated.

The data model also needs some work, which I haven't started on yet.

**Comment by moribellamy** [comment]
1) Any ETA on this?
2) Is this just for gauges or for counters as well?

Thanks!

**Comment by jaqx0r** [comment]
No ETA yet.

It will be for all storage types.

**Comment by naveensrinivasan** [comment]
Any update on this?

**Comment by jaqx0r** [comment]
I know you're keen for it and I am too, I'm working on it.

**Comment by ashoksahoo** [comment]
Awesome, let me know if you have any dev build, also if I can be of some help.

**Comment by opsnull** [comment]
Wish this feature to be merged！

**Comment by drawks** [comment]
Eagerly awaiting this change, any news?

**Comment by jaqx0r** [comment]
Eagerly working on it. Most of the core work is done and committed, just
getting it all strung together.

**Comment by jaqx0r** [comment]
There is now floating point and integer types in the compiler and metric export, as documented in the last change.   I assume there are edge cases and bugs that I haven't considered in your use cases, please file new bugs for them!

**Comment by jaqx0r** [comment]
Oh, the wiki git repo doesn't link here?  Huh.  The documentation is now at 

https://github.com/google/mtail/wiki/Language#numerical-capture-groups-and-metric-type-information
