### ISSUE TITLE
nil pointer error when writeJumps

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/mtail#240]
`nil` enter func `errorf` from the 1st parameter:
https://github.com/google/mtail/blob/f48bc41ab6cb834b39e0bde3427f248dc6851dca/internal/vm/codegen/codegen.go#L579

Then enter func `Add` from the 1st parameter:
https://github.com/google/mtail/blob/f48bc41ab6cb834b39e0bde3427f248dc6851dca/internal/vm/codegen/codegen.go#L49

So, `*pos` my cause nil pointer error:
https://github.com/google/mtail/blob/f48bc41ab6cb834b39e0bde3427f248dc6851dca/internal/vm/errors/errors.go#L28

**Comment by jaqx0r** [comment]
This should manifest when the Error() method is called, dereferencing the
pos member on errors.go:20, right?  Thanks!
