### ISSUE TITLE
How to count matches per min

### ISSUE THREAD

**Issue by tima-fey** [google/mtail#243]
Hi!I have a trouble in counting amount of matches per minute.
My current implementation listed below
But I think there is much more efficient way to do it.
Could you kindly advice?
Thanks Tim!

```gauge error_count
hidden gauge hidden_error_count by min
hidden gauge min

def init_parse {
  /(?P<date>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2}) / + /(?P<severity>[A-Z]*): / + /(?P<message>.*)/ + /$/ {
    strptime($date, "2006-01-02 15:04:05")
    min = int(timestamp() / 60)
  next
  }
}

error_count = 0
@init_parse {
$severity =~ /^ERROR/ {
  hidden_error_count[min]++
  error_count = hidden_error_count[min]
}
}
```

**Comment by tima-fey** [comment]
one more idea
`$severity =~ /^ERROR/ {
  error_count++
  del error_count after 1m
}`

**Comment by tima-fey** [comment]
My last idea seems work in improper way

**Comment by tima-fey** [comment]
And one more question: Can't find a way how to specify all params through config file. Could you kindly advice is there are any?

**Comment by SuperQ** [comment]
This is a job for the monitoring system collecting data.

You create a counter like 

```
counter errors_total

/^ERROR/ {
  errors_total++
```

Then in something like [Prometheus](https://prometheus.io), you can do `rate(errors_total[1m]) * 60`. This is more robust, as you typically scrape every 15 seconds, so a missed scrape or a mtail restart doesn't affect things.

**Comment by jaqx0r** [comment]
Thanks @SuperQ.

@tima-fey `mtail` is only a piece of a larger monitoring system.  Its job is just extraction of metrics from textual log data.

What do you mean when you say "specify all params through config file" ?  Are you asking about putting the commandline flags in a config instead?  Perhaps you can give an example of what you mean.

**Comment by tima-fey** [comment]
Thanks @jaqx0r  and @SuperQ  for your answers
@jaqx0r yep I mean exactly what you have said
example:
run mtail with the key `--config mtail.conf`

Thanks

**Comment by jaqx0r** [comment]
There is no config file, all config is supplied by the command line flags
today.

**Comment by tima-fey** [comment]
OK
Thanks
