### ISSUE TITLE
Cut 3.0.0

### ISSUE THREAD

**Issue by SuperQ** [google/mtail#248]
We've been cutting 3.0.0-rc releases for 2 years. Maybe it's time to just cut the release and make 3.1.0 with new features. :smile:

**Comment by jaqx0r** [comment]
We're not yet feature parity with python mtail 2.0.0 :)

**Comment by jaqx0r** [comment]
Yeah ok. Gimme a week to double check then.

**Comment by SuperQ** [comment]
lol, I didn't know there was a python mtail.

**Comment by jaqx0r** [comment]
Oh, there are two! This is why this mtail is V3.

**Comment by jnovack** [comment]
I am pretty sure `milestone: v3.0.0` needs to be added to this issue. ;)

**Comment by jaqx0r** [comment]
It's only been 12 years https://github.com/google/mtail/commit/c6efea5fe4f2f57af4de7e1f6b28da70c8eb94e7 and it's still not ready yet, but :shrug:

**Comment by SuperQ** [comment]
OMG! :tada: Thanks for all the work over the years.

And I will say, it's been ready for at least the last 6 years. Perfect is the enemy of good. :grin:

**Comment by jaqx0r** [comment]
Aww thanks.

It sure is, despite me keeping on thinking "just one more bugfix..."
