### ISSUE TITLE
can't load package: package github.com/google/mtail: no Go files in /root/go/src/github.com/google/mtail

### ISSUE THREAD

**Issue by AATHITH** [google/mtail#250]
root@STG:~/go/src/github.com/google/mtail# mtail -version
mtail version invalid:-use-make-to-build git revision invalid:-use-make-to-build go version go1.12.7 go arch amd64 go os linux

How to install MTAIL perfectly in ubuntu? what is this message saying? how to fix this??

**Comment by jaqx0r** [comment]
How did you install this mtail? It looks like you used go get and that's
not correct, please type make as the error message suggested.

**Comment by AATHITH** [comment]
`go get -u github.com/google/mtail` - when i execute this command it is showing like this.

> package github.com/google/mtail: no Go files in /root/go/src/github.com/google/mtail

`cd $GOPATH/src/github.com/google/mtail`- the source file is cloned here

**Comment by AATHITH** [comment]
just 3 line install and not working properly
go get..
cd...
make....boom nothing worked

**Comment by jaqx0r** [comment]
Can you copy and paste your commands and the output instead of typing
abbreviations?   I can't help you if you don't show me what the errors are.

**Comment by AATHITH** [comment]
Here is my full command and errors
`go get -u github.com/google/mtail` - when I execute this command it is showing like this.

> package github.com/google/mtail: no Go files in /root/go/src/github.com/google/mtail

`cd $GOPATH/src/github.com/google/mtail`- I entered into this directory and 
`make`- make results in 

> go generate -x ./internal/vm/parser
> goyacc -v y.output -o parser.go -p mtail parser.y
> /usr/bin/convert logo.png -define icon:auto-resize=64,48,32,16 internal/mtail/logo.ico || touch internal/mtail/logo.ico
> /bin/sh: 1: /usr/bin/convert: not found
> Install all dependencies, ensuring they're updated
> go get -v bufio bytes context contrib.go.opencensus.io/exporter/jaeger crypto/rand encoding/json expvar flag fmt github.com/fsnotify/fsnotify github.com/golang/glog github.com/golang/groupcache/lru github.com/google/go-cmp/cmp github.com/google/go-cmp/cmp/cmpopts github.com/pkg/errors github.com/prometheus/client_golang/prometheus github.com/prometheus/client_golang/prometheus/promhttp github.com/prometheus/common/version go.opencensus.io/trace go.opencensus.io/zpages html/template io io/ioutil math math/big math/rand net net/http net/http/pprof os os/exec os/signal path path/filepath reflect regexp regexp/syntax runtime runtime/debug sort strconv strings sync sync/atomic syscall testing text/tabwriter time unicode unicode/utf8
> github.com/uber/jaeger-client-go (download)
> github.com/hashicorp/golang-lru (download)
> github.com/fsnotify/fsnotify (download)
> github.com/golang/glog (download)
> github.com/golang/groupcache (download)
> github.com/google/go-cmp (download)
> github.com/pkg/errors (download)
> github.com/prometheus/client_golang (download)
> github.com/beorn7/perks (download)
> github.com/golang/protobuf (download)
> github.com/prometheus/client_model (download)
> github.com/prometheus/common (download)
> github.com/matttproud/golang_protobuf_extensions (download)
> github.com/prometheus/procfs (download)
> github.com/google/go-cmp/cmp/internal/value
> github.com/golang/protobuf/proto
> github.com/google/go-cmp/cmp
> github.com/google/go-cmp/cmp/cmpopts
> github.com/prometheus/procfs
> github.com/prometheus/client_model/go
> github.com/matttproud/golang_protobuf_extensions/pbutil
> github.com/golang/protobuf/ptypes/any
> github.com/golang/protobuf/ptypes/duration
> github.com/prometheus/client_golang/prometheus/internal
> github.com/prometheus/common/expfmt
> github.com/golang/protobuf/ptypes/timestamp
> github.com/golang/protobuf/ptypes
> google.golang.org/genproto/googleapis/rpc/status
> google.golang.org/grpc/status
> go.opencensus.io/plugin/ocgrpc
> github.com/prometheus/client_golang/prometheus
> github.com/prometheus/common/version
> github.com/prometheus/client_golang/prometheus/promhttp
> go get -v bufio context encoding/json errors expvar fmt github.com/golang/glog github.com/pkg/errors github.com/prometheus/client_golang/prometheus/testutil io io/ioutil math math/rand net/http net/http/httptest os os/user path path/filepath reflect regexp regexp/syntax runtime sort strconv strings sync syscall testing testing/quick time
> github.com/prometheus/client_golang/prometheus/testutil
> touch .dep-stamp
> echo "mtail: $(go list -f '{{if not .Standard}}{{.Dir}}{{end}}' $(go list -f '{{ join .Deps "\n" }}' cmd/mtail/main.go) | sed -e 's@$@/*.go@' | tr "\n" " " )" > .d/mtail.d
> GO111MODULE=on go build -ldflags "-X main.Branch=master -X main.Version=v3.0.0-rc33-1-g6128742 -X main.Revision=6128742ae88749a3933b36bd8cea7404cb957fe1" -o mtail cmd/mtail/main.go
> echo "mgen: $(go list -f '{{if not .Standard}}{{.Dir}}{{end}}' $(go list -f '{{ join .Deps "\n" }}' cmd/mgen/main.go) | sed -e 's@$@/*.go@' | tr "\n" " " )" > .d/mgen.d
> GO111MODULE=on go build -ldflags "-X main.Branch=master -X main.Version=v3.0.0-rc33-1-g6128742 -X main.Revision=6128742ae88749a3933b36bd8cea7404cb957fe1" -o mgen cmd/mgen/main.go
> echo "mdot: $(go list -f '{{if not .Standard}}{{.Dir}}{{end}}' $(go list -f '{{ join .Deps "\n" }}' cmd/mdot/main.go) | sed -e 's@$@/*.go@' | tr "\n" " " )" > .d/mdot.d
> GO111MODULE=on go build -ldflags "-X main.Branch=master -X main.Version=v3.0.0-rc33-1-g6128742 -X main.Revision=6128742ae88749a3933b36bd8cea7404cb957fe1" -o mdot cmd/mdot/main.go






My GO version - go version go1.12.7 linux/amd64

My GO ENV -
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/root/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/root/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="0"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build365346898=/tmp/go-build -gno-record-gcc-switches"

**Comment by jaqx0r** [comment]
So it looks like it worked then?

**Comment by AATHITH** [comment]
So it looks like it worked then?


no it didn't worked, 
 

**mtail --version**
> 
> Command 'mtail' not found, did you mean:
> 
>   command 'xtail' from deb xtail
>   command 'mltail' from deb svtools
>   command 'ctail' from deb byobu
>   command 'mail' from deb mailutils
>   command 'tmail' from deb uw-mailutils
>   command 'rtail' from deb ruby-file-tail
>   command 'tail' from deb coreutils
> 
> Try: apt install <deb name>
>

**Comment by jaqx0r** [comment]
./mtail -version

because it's been built in the current directory.

**Comment by jaqx0r** [comment]
I see where the instructions have led you astray now.  This is confusing because GO changed how `go get` worked with Go 1.12.

Sorry about that, about to update them.
