### ISSUE TITLE
No Go files in $GOPATH/src/github.com/google/mtail

### ISSUE THREAD

**Issue by AATHITH** [google/mtail#251]
When try the following, i'm getting a  error,
`go get -u github.com/google/mtail` 

> package github.com/google/mtail: no Go files in /root/go/src/github.com/google/mtail

`cd $GOPATH/src/github.com/google/mtail`- the source file is cloned here

`make test` results:

> can't load package: package github.com/google/mtail: no Go files in /root/go/src/github.com/google/mtail

**Comment by jaqx0r** [comment]
If you're using Go 1.11 or later, can you try GO11MODULE=on before go get?
I.e.:

GO11MODULE=on go get -u github.com/google/mtail

and let me know if that works for you

**Comment by AATHITH** [comment]
but my GO version is  `go1.12.7 linux/amd64`
