### ISSUE TITLE
mtail creating huge log files, running out of disk every couple of days

### ISSUE THREAD

**Issue by bc-mahesh** [google/mtail#252]
Hello, 

I start mtail by using the command - 

`mtail --progs tomcat_metrics.mtail --port 9101 --logs '/opt/apache-tomcat-8.0.12/logs/localhost_access_log*.txt'`

We started using mtail to publish app metrics to prometheus and monitor our app performance over time. Prometheus also scrapes the resource metrics from these servers using node exporter. But the issue is that it produces big mtail.INFO logs, with log rotation. And every 2 days we have prometheus firing alerts about low disk space!! 

Is there an option to delete mtail INFO logs frequently or not log anything at all?

**Comment by jaqx0r** [comment]
Sorry about that.

What version of mtail is this?  What log messages do you see?

You should look at the --help to see what flags you can use to turn off
logging, but please let me know what the logs are because generating this
much in normal operation is a bug.

**Comment by bc-mahesh** [comment]
Thanks a lot for your reply,
Version - 
`mtail version v3.0.0-rc29 git revision b5aa95d10fb3af7b843e3814bc65aedd983425d9 go version go1.11.6 go arch amd64 go os linux`

Log sample (Lot of these!!) - 

0@1564697399560496218 LabelValue: [/manager-0.1/auth/receive/upgrade/pending/sdsdsd GET 200] 0@1564697399560678953 LabelValue: [/bot-platform-manager-0.1/botinfo/menu/dsdsds GET 200] 0@1564697409560973192 LabelValue: [manager-0.1/domai GET 200] 0@1564697739616592138] source=tomcat_metrics.mtail:8:11-39 buckets=[{0.005 0.01} {0.01 0.025} {0.025 0.05} {0.05 0.1} {0.1 0.25} {0.25 0.5} {0.5 1} {1 2.5} {2.5 5} {5 10} {10 15} {15 +Inf}]
Regexps
        0 /^(?P<remote_host>[0-9A-Za-z\.:-]+) (?P<remote_logname>[0-9A-Za-z-]+) (?P<remote_host_1>[0-9A-Za-z\.:-]+) (?P<remote_username>[0-9A-Za-z-]+) (?P<remote_username_1>[0-9A-Za-z-]+) \[(?P<timestamp>\d{2}/\w{3}/\d{4}:\d{2}:\d{2}:\d{2} (\+|-)\d{4})\] "(?P<request_method>[A-Z]+) (?P<request_uri>/bot-platform-manager-0.1/[^?]+)(?P<query_string>\S+) (?P<http_version>HTTP/[0-9\.]+)" (?P<status_code>\d{3}) ((?P<response_size>\d+)|-) (?P<response_time>\d+)$/
Strings
 disasm  l         op  opnd
         0      match     0
         1        jnm    64
         2 setmatched false
         3       push     0
         4     capref     9
         5       push     0
         6     capref     8
         7      mload     0
         8      dload     2
         9        inc <nil>
        10       push     0
        11     capref     9
        12       push     0
        13     capref     8
        14       push     0
        15     capref    12
        16        s2i <nil>
        17        i2s <nil>
        18      mload     2
        19      dload     3
        20        inc <nil>
        21       push     0
        22     capref    15
        23        s2i <nil>
        24       push     0
        25       icmp     1
        26        jnm    29
        27       push  true
        28        jmp    30
        29       push false
        30        jnm    49
        31 setmatched false
        32       push     0
        33     capref     9
        34       push     0
        35     capref     8
        36       push     0
        37     capref    12
        38        s2i <nil>
        39        i2s <nil>
        40      mload     3
        41      dload     3
        42       push     0
        43     capref    15
        44        s2i <nil>
        45       push  1000
        46       idiv <nil>
        47       iset <nil>
        48 setmatched  true
        49       push     0
        50     capref     9
        51       push     0
        52     capref     8
        53       push     0
        54     capref    12
        55        s2i <nil>
        56        i2s <nil>
        57      mload     1
        58      dload     3
        59       push     0
        60     capref    14
        61        s2i <nil>
        62        inc     0
        63 setmatched  true
I0801 22:18:19.606145   29550 vm.go:90] tomcat_metrics.mtail: Runtime error: strconv.ParseInt: parsing "": invalid syntax
I0801 22:18:19.606173   29550 vm.go:91] VM stack:
goroutine 46 [running]:
runtime/debug.Stack(0xc000024300, 0x28, 0xc000c3bc50)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/mtail/internal/vm.(*VM).errorf(0xc00022e1e0, 0x931401, 0x2, 0xc000c3bc50, 0x1, 0x1)
	/go/src/github.com/google/mtail/internal/vm/vm.go:91 +0x113
github.com/google/mtail/internal/vm.(*VM).execute(0xc00022e1e0, 0xc0006be2d0, 0x34, 0x0, 0x0)
	/go/src/github.com/google/mtail/internal/vm/vm.go:675 +0x2c43
github.com/google/mtail/internal/vm.(*VM).processLine(0xc00022e1e0, 0xc000ff4160)
	/go/src/github.com/google/mtail/internal/vm/vm.go:748 +0x18c
github.com/google/mtail/internal/vm.(*VM).Run(0xc00022e1e0, 0x746f6d63, 0xc00020c5a0, 0xc00020c600, 0xc00020c660)
	/go/src/github.com/google/mtail/internal/vm/vm.go:767 +0xf5
created by github.com/google/mtail/internal/vm.(*Loader).CompileAndRun
	/go/src/github.com/google/mtail/internal/vm/loader.go:241 +0x70d
I0801 22:18:19.606180   29550 vm.go:92] Dumping vm state
I0801 22:18:19.606183   29550 vm.go:93] Name: tomcat_metrics.mtail
I0801 22:18:19.606186   29550 vm.go:94] Input: &logline.LogLine{Filename:"/opt/apache-tomcat-8.0.12/logs/localhost_access_log.2019-08-01.txt", Line:"10.0.1.84 - 10.0.1.84 - - [01/Aug/2019:22:18:12 +0000] \"POST /manager-0.1/userMessageEvent HTTP/1.1\" 200 - 1"}
I0801 22:18:19.606197   29550 vm.go:95] Thread:
I0801 22:18:19.606200   29550 vm.go:96]  PC 61
I0801 22:18:19.606202   29550 vm.go:97]  Matched true
I0801 22:18:19.606205   29550 vm.go:98]  Matches map[0:[10.0.1.84 - 10.0.1.84 - - [01/Aug/2019:22:18:12 +0000] "POST /bot-platform-manager-0.1/userMessageEvent HTTP/1.1" 200 - 1 10.0.1.84 - 10.0.1.84 - - 01/Aug/2019:22:18:12 +0000 + POST /bot-platform-manager-0.1/userMessageEven t HTTP/1.1 200 -  1]]
I0801 22:18:19.606215   29550 vm.go:99]  Timestamp 0001-01-01 00:00:00 +0000 UTC
I0801 22:18:19.606223   29550 vm.go:100]  Stack [0@1564627686126403017]
I0801 22:18:19.622750   29550 vm.go:101] Prog: tomcat_metrics.mtail

**Comment by jaqx0r** [comment]
Ok you are getting some because of an mtail bug, and a lot more because of
a Parse error in your program. The stack trace tells you where in the
bytecode it is erroring but it's not easy to turn that into a line in the
source code.

**Comment by jaqx0r** [comment]
I think the mtail bug is fixed already in rc32, so please try the latest
version.

**Comment by bc-mahesh** [comment]
Ok @jaqx0r, thank you. Is there an option to ignore parse errors or should I tweak my regex to ignore those?

**Comment by jaqx0r** [comment]
Please get rc33 which was just uploaded, and try that out.  It has new log
messages which are both less spammy than before, and more useful to help
debug where the parse error is occurring, to help you tweak your regexes.

**Comment by bc-mahesh** [comment]
Oh, cool! Thank you @jaqx0r
