### ISSUE TITLE
Parsing integers / floats with commas (thousand separator)

### ISSUE THREAD

**Issue by guiwoda** [google/mtail#254]
Given a log line such as
```
I found 12,345 cases.
```
When trying to run this program:
```
gauge cases

/I found (?P<amount>[\d\,]+) cases./ {
    cases = $amount
}
```

I always get `0` back as the value.
It also fails to interpret values lower than `1,000`, so I'm assuming it has something to do with the capture group's regex and type inference.

**Comment by guiwoda** [comment]
Forcing the type coercion to integer didn't work:

```
gauge cases

/I found (?P<amount>[\d\,]+) cases./ {
    cases = int($amount)
}
```

**Comment by jaqx0r** [comment]
mtail relies on the go library's number parser, which doesn't support
commas. We'll have to implement a custom parser.

**Comment by jaqx0r** [comment]
So, a workaround, if you only get numbers lower than 1,000,000:

/I found (?P<thous>\d+),(?P<ones>\d{1-3}) cases./ {
    cases = $thous*1000+$ones
}


/I found (?P<amount>\d{1-3}) cases./ {
    cases = $ones
}

Probably could collapse that into one expression with a '?' on the first
group.

**Comment by guiwoda** [comment]
Yes, I'm doing exactly that right now.

**Comment by jaqx0r** [comment]
See also #326 , I've just realised these are duplicates.
