### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [google/mtail#256]
Hi, I'm Yevgeny Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

I saw that you implemented Fuzz targets but they are currently not running as part of the CI.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by jaqx0r** [comment]
I would love that!

Will you make me an API key in this PR?  Or should I just go ahead and
follow the instructions and examples you made/

Is the fuzzit command available in a docker image or only over the binary
downlioaded with wget?

Where's the corpus stored?

Is there a UI for looking at fuzz results?

**Comment by yevgenypats** [comment]
HI, Cool!

You can sign-up at [https://app.fuzzit.dev](https://app.fuzzit.dev) and I'll add you to the `mtail` organisation. 

The corpus is stored on our servers where you can always download it as well as run regression that will include the corpus.

Fuzzit CLI is OSS and available in this [repo](https://github.com/fuzzitdev/fuzzit). currently not available in a docker image but we can add this.

I think for more questions regarding the integration you can also join our [slack](https://slack.fuzzit.dev) and dm me.

One more thing we have a [reward](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) program. If you would like to do the integration I'll be happy to get you rewarded as well as to get unbiased feedback of how smooth was the integration. If you currently don't have time for it and would like us to contribute the PR that's also good but you won't be eligible for the reward. Let me know what works for you:)

Cheers,
Yevgeny

**Comment by jaqx0r** [comment]
Alright, I've signed up with my Github account id.  I'll do the setup and
ask you questions if I get stuck.

**Comment by yevgenypats** [comment]
Hi, forgot to comment here - I've added you to mtail organisation and dedicated currently 4 CPUs let me know if more is needed: https://app.fuzzit.dev/orgs/mtail/dashboard

**Comment by jaqx0r** [comment]
Thanks!

**Comment by jaqx0r** [comment]
OK I'm going through the setup now, and I have questions.

When I create a new target, what am I making?  Is this the name of the
thing I want to fuzz?

What format file does "upload corpus" accept?

**Comment by yevgenypats** [comment]
Yes the fuzz target is the identifier name where you will upload your fuzzers with different versions but the same fuzz functions. those fuzzers will share the corpus that will be generated.

seed corpus - zip, tar.gz of test-case files.

**Comment by jaqx0r** [comment]
Great, thanks.  (I was just reading the quick-start page.)

**Comment by yevgenypats** [comment]
Yes, our docs are in need of improvement. we will put an effort on this in the upcoming week:)

**Comment by jaqx0r** [comment]
OK, next struggle is getting the CI step to build the fuzzer target.
Copying the instructions in the example-go to get clang-9 installed is
really trying my patience.

Do we really need clang-9 and not just use go-fuzz?  I suppose something
requires that the C++ libfuzzer is used, not the pure Go version?

Could you make a section in your main docs that looks like
https://github.com/fuzzitdev/example-go#setting-up-the-development-environment
with
the minimum necessary to get the build env configured in order to build?

For example: https://circleci.com/gh/google/mtail/3632  is the current
state of thigns for me.  Not insurmountable, but I just followed these
instructions and it's not working.

**Comment by yevgenypats** [comment]
@jaqx0r So any clang > 6.0 should work and libFuzzer integration is indeed currently necessary. 
I think in CircleCI option you need to use our docker (In Travis it's already installed for some reason) where we already installed clang-9. I'll add instruction for Circle in the repo I think that might help.
fuzzitdev/golang:1.12.7-buster (The dockerfile is [here](https://github.com/fuzzitdev/fuzzit/tree/master/docker/debian/stretch/golang12-llvm9))

**Comment by jaqx0r** [comment]
Thanks, will try!

**Comment by yevgenypats** [comment]
If you give up let me know and I'll try:)

**Comment by jaqx0r** [comment]
Your dockerfile doesn't install the fuzzit tool :)

**Comment by yevgenypats** [comment]
Yes, this is kind of on purpose it's just contains the toolchain as the fuzzit CLI changes more rapidly so we didn't wont to release a new docker every time we release a new version of fuzzit CLI.

**Comment by jaqx0r** [comment]
Ok, but I'd assume you'd build a new docker image when you do too. No
problem.

**Comment by jaqx0r** [comment]
https://circleci.com/gh/google/mtail/3642 getting closer! I out the API key
in the project environment but seems I missed something at the end. Can I
increase verbosity?

**Comment by yevgenypats** [comment]
ok I need to add a more descriptibe error message. I can see that you didn't create a fuzz target on mtail. I create this for you, Now you just need to change `internal/vm` to `mtail/internal-vm`. The change is only in the first argument, the last argument is fine as it's just the pass to the fuzzer.

**Comment by yevgenypats** [comment]
any luck? what's the latest issue?

**Comment by jaqx0r** [comment]
That worked! I should have realised I didn't create the target yet.

New problem, flags.
https://app.fuzzit.dev/orgs/mtail/targets/internal-vm/gTVBEWowoOxvbuIdHI2u
shows a flag not accepted. I probably need to change the fuzz program.

**Comment by jaqx0r** [comment]
By the way, the login screen on mobile hides both Google and GitHub oauth
buttons. I can send you a screenshot of you like.

**Comment by jaqx0r** [comment]
I see this in the logs on the fuzz target job:

FUZZER: Usage:
FUZZER: flag provided but not defined: -max_total_time

Is this supposed to timeout the fuzzer?  I believe I've fixed the flag parser so it's not interfering with libFuzzer or clang sanitizer, so not sure why this is erroring.

**Comment by jaqx0r** [comment]
OH, I uploaded a corpus but I can't see any confirmation that it's being used.

**Comment by yevgenypats** [comment]
I'm not sure about the corpus but the code that parsing the variable is doing the problem afaik
https://github.com/google/mtail/commit/715564d057e14cd2c2bcccce60ebd74a2befe02e#diff-07ae698bce29b7f17d938154e57d7b49R16
maybe there is a way either to remove the need for this initialisation at alls or pass additional arguments?

**Comment by jaqx0r** [comment]
The previous commit that had no flag.parse also showed the max_time flag
wasn't parsed.

https://app.fuzzit.dev/orgs/mtail/targets/internal-vm/86yTKnYk7n1Pk8GWtp0k

**Comment by yevgenypats** [comment]
wow, this is a rough integration:) I tried uploading the fuzzer (without the flag commit) [again](https://app.fuzzit.dev/orgs/mtail/targets/internal-vm/HMp8uOttoL0oqHLplK1P) and you can see that in the beginning it works fine but then there is the error `declaration of capture group reference` which is unrelated to libFuzzer and this something with app. I think the last commit you did partially solved the problem but introduced a new one as the flag parsing now eats some of the libfuzzer arguments. I'm not sure what the solution is but maybe this is because `flags.newFlagSet` is passed an empty string. I think it will be the fastest if you can try the fixes in a docker this way the iterations will be faster. You can reproduce the fuzzit behaviour by calling the fuzzer with `./fuzzer -max_total_time=3600` as it's called on fuzzit servers.

**Comment by jaqx0r** [comment]
the "declaration of capture group reference" is WAI, part of the code being
fuzzed.  I just wanted to understand where the -max_total_time is coming
from and why the code under test warns that it doesn't get parsed by the
clang sanitized binary.  I know for a fact that the flag isn't being parsed
because the current code at head is not parsing the argv of the program,
that's the empty string you see -- the previous problem was that it was
seeing all the clang flags and failing.

So to recap, the first upload had a flag parse, and failed when it saw
flags it didn't understand in argv, which were from fuzzit aimed at the
clang main function.
The second upload removed that code from the Fuzz function, and then it
threw lots of errors that flag parsin hadn't been done before glog.Info was
called.
The third version puts back a flag.PArse so that the glog.Info warning
doesn't appear, by hcaking it with an empty string instead of Argv.

So when the latest version is complaining that -max_total_time is
unrecognised, that must be now in the clang-generated main function.

**Comment by jaqx0r** [comment]
Good news, I figured out why the flag parse still wasn't working.  Turns out I misunderstood the go flags package initialization.

**Comment by yevgenypats** [comment]
Alright! sounds good. so it works now?

**Comment by jaqx0r** [comment]
Yep! Some fine tuning remains I think, I can't get the local regression to
fail on the corpus anymore, and I haven't tested the PR runs the regression
without the fuzzing.

**Comment by yevgenypats** [comment]
Cool! let me know if you encounter bugs or have other questions. Also do you mind putting a Fuzzit badge:) it's not a whole lot useful currently apart from people knowing that you fuzz your code as well as linking to a page that you need to login to view. Though we do plan to have an opt-in option to link it soon to a page with some interesting (and harmless) statistics like corpus-size/runs/tests etc.

**Comment by jaqx0r** [comment]
Yeah what URl do I use for fuzzit badge?  I only see a static-passing link at the top of the page, and there's nothing in the Dashboard or Settings to paste into my README.

**Comment by jaqx0r** [comment]
OH right.  Just the static one then :)

**Comment by yevgenypats** [comment]
Yeah, click on this it will give you Markdown text to copy:)

**Comment by jaqx0r** [comment]
Oh cool, thanks!
