### ISSUE TITLE
regex for Chinese

### ISSUE THREAD

**Issue by xxfeng2016** [google/mtail#257]
/^[\u4e00-\u9fa5]/ {
lines_total++
}
has a problem :

 error parsing regexp: invalid escape sequence: `\u`

**Comment by jaqx0r** [comment]
Thanks for the report.

The go regexp library doesn't support that notation:
https://golang.org/pkg/regexp/syntax/

Try \x4e00 or if you can use a unicode character class, \p{class name}.

I'm sorry I've never had to try this before so it's clearly woefully
English-centric.

**Comment by xxfeng2016** [comment]
Thanks a  lot. I  have got it .

**Comment by yudidi** [comment]
You can use `"[\u4e00-\u9fa5]+"`to replace ````
