### ISSUE TITLE
Mtail blocks disk space

### ISSUE THREAD

**Issue by grobie** [google/mtail#26]
Our alerts started to fire on more and more machines about low available disk space. While that was clearly visible in `df`, nothing showed up when using `du`. Eventually I was able to track this down to mtail, restarting mtail (which was running for >1 month) freed up all the disk space immediately. I'm still investigating this issue.

* the log file is a svlogd controlled "current" ~~symlink~~ file
* no open file descriptors for (deleted) files are hold by mtail (the typical scenario for df/du differences)
* The log file show many `Unexpected event: {"...."}` lines. I believe because the DeleteEvent isn't handled and svlogd will briefly delete the symlink before creating it again.

Additionally it seems I can't kill mtail on some instances with a sigterm, only a hard kill worked. On some other nodes the metrics were stale.

While the last version was built on march 26th from master, I can't guarantee that version is actually used on all nodes, given a sigterm sometimes doesn't work.

**Comment by jaqx0r** [comment]
Yow.

Here's a wild guess: the fsnotify code is holding open file descriptors.

I'm impressed you had a daemon running that long and this was the first
problem. I was expecting some slowness or memory leak :)

I am not sure that mtail handles the symlink well either. That deserves an
integration test.

**Comment by grobie** [comment]
Here some info from one of such nodes. I'll continue to debug this issue soon.

```
$ sv status mtail
run: mtail: (pid 11079) 522542s; run: log: (pid 953) 26650661s

$ df -h
Filesystem                                              Size  Used Avail Use% Mounted on
rootfs                                                  143G  123G   20G  87% /
udev                                                     10M     0   10M   0% /dev
tmpfs                                                   6.3G  256K  6.3G   1% /run
/dev/disk/by-uuid/1be39b37-....                         143G  123G   20G  87% /
tmpfs                                                   5.0M     0  5.0M   0% /run/lock
tmpfs                                                    14G     0   14G   0% /run/shm

$ du -hs /
18G     /

$ lsof -p $(pidof mtail)
COMMAND   PID   USER   FD   TYPE     DEVICE SIZE/OFF       NODE NAME
mtail   11079 nobody  cwd    DIR        8,1       42  537168787 /etc/sv/mtail
mtail   11079 nobody  rtd    DIR        8,1     4096        128 /
mtail   11079 nobody  txt    REG        8,1 10086936  805381511 /srv/mtail/mtail
mtail   11079 nobody  mem    REG        8,1    47616  805534732 /lib/x86_64-linux-gnu/libnss_files-2.13.so
mtail   11079 nobody  mem    REG        8,1    43560  805534734 /lib/x86_64-linux-gnu/libnss_nis-2.13.so
mtail   11079 nobody  mem    REG        8,1    89056  805458563 /lib/x86_64-linux-gnu/libnsl-2.13.so
mtail   11079 nobody  mem    REG        8,1    31584  805458564 /lib/x86_64-linux-gnu/libnss_compat-2.13.so
mtail   11079 nobody  mem    REG        8,1  1607696  805343560 /lib/x86_64-linux-gnu/libc-2.13.so
mtail   11079 nobody  mem    REG        8,1   131107  805307865 /lib/x86_64-linux-gnu/libpthread-2.13.so
mtail   11079 nobody  mem    REG        8,1   136936  805307866 /lib/x86_64-linux-gnu/ld-2.13.so
mtail   11079 nobody    0u   CHR        5,1      0t0       1036 /dev/console
mtail   11079 nobody    1w  FIFO        0,8      0t0  627728076 pipe
mtail   11079 nobody    2w  FIFO        0,8      0t0  627728076 pipe
mtail   11079 nobody    3r  0000        0,9        0       4732 anon_inode
mtail   11079 nobody    4u  0000        0,9        0       4732 anon_inode
mtail   11079 nobody    5r  FIFO        0,8      0t0 3250757555 pipe
mtail   11079 nobody    6w  FIFO        0,8      0t0 3250757555 pipe
mtail   11079 nobody    7r  0000        0,9        0       4732 anon_inode
mtail   11079 nobody    8u  0000        0,9        0       4732 anon_inode
mtail   11079 nobody    9r  FIFO        0,8      0t0 3250775486 pipe
mtail   11079 nobody   10w  FIFO        0,8      0t0 3250775486 pipe
mtail   11079 nobody   12u  IPv6 3250687972      0t0        TCP *:3903 (LISTEN)
mtail   11079 nobody   13u  0000        0,9        0       4732 anon_inode

$ pstree $(pidof mtail)
mtail───62*[{mtail}]
```

**Comment by jaqx0r** [comment]
Thanks for the logs!

I've got a test that I think reproduces the symlink issue but I can't make
it fail, so I don't think that is it.

The fd list looks like it does not have any logs open at the time you
snapshotted it -- what log file are you expecting to ahve open?

Can you attach a profiler to the /debug/pprof URI hander on port 3903 and
get a snapshot of the memory usage?  See
https://blog.golang.org/profiling-go-programs for more info.

Also, what OS/Distro, what version of Go built mtail, and what commit did
you download mtail at?

**Comment by grobie** [comment]
I was wrong actually, svlogd doesn't use a symlink. `current` is just the
current file which gets rotated and will briefly disappear during the
rotation. Sorry for the false information. I'll provide more information
tomorrow.

**Comment by jaqx0r** [comment]
The semantics of log rotation handling in mtail is that when a new file is
*created*, mtail detects that by comparing the inode of the old file with
the new one, reading the old to EOF, then closing it before oening the new
one and seeking to the start and replacing the file handle object. File
deletion events are ignored because in log rotations, they are followed
with a create event.

It's possible that the lack of delete handling is causing old logs to be
kept open but I'd expect to see the fd in the mtail process.  Also if
svlogd is moving and creating new 'current' files, then this should fit the
same pattern already handled.

You can increase the logging level with --v=2 and --logtostderr to redirect
mtail's logs to stderr.  You can also force a stack trace with the
--log_backtrace_at='file.go:lineno' command where file.go:lineno must match
the file:line of a log message.

**Comment by jaqx0r** [comment]
I'll be interested to see if this problem persists after https://github.com/google/mtail/pull/28

**Comment by SuperQ** [comment]
Here's a Prometheus graph :smile: 

You can see restarts and slow leaking of files as mtail locked up.  #28 fixes the problem. 

![filedescriptorleakfix](https://cloud.githubusercontent.com/assets/1320667/15539322/fbf40114-2281-11e6-8bdf-4e4015ebf504.png)

**Comment by grobie** [comment]
Thanks!

**Comment by jaqx0r** [comment]
My theory is that the blocked fsnotify remove held the fd open, holding the
disk space.  This seems to support that.

Thanks for the help!
