### ISSUE TITLE
Release builds for power pc users

### ISSUE THREAD

**Issue by tkschmidt** [google/mtail#261]
Hi,
is it fine to open a pull request to enable also release builds for ppc users?
It`s just a one-line change in https://github.com/google/mtail/blob/master/Makefile#L143.

Best,
Tobias

**Comment by jaqx0r** [comment]
Yes it is!

**Comment by jaqx0r** [comment]
Did you want linux/ppc64 or darwin/ppc64?

**Comment by jaqx0r** [comment]
Ah it must be linux/ppc64 because there isn't any other per https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63
