### ISSUE TITLE
Hangs on sigterm

### ISSUE THREAD

**Issue by grobie** [google/mtail#27]
A sigterm doesn't always cleanly terminate mtail. The process just hangs on `23:53:07.163583   25177 mtail.go:255] Shutdown requested.`

**Comment by jaqx0r** [comment]
I can't reproduce this, but this means shutdown has started and something
is blocking and not receiving the shutdown channel notice.

Can you get mtail to dump the goroutine stacks when this happens?

Before running, set GOTRACEBACK=2 environment variable, and then send kill
-QUIT to the process after you send the sigterm and it hangs.

More info here:
https://golang.org/pkg/runtime/

**Comment by grobie** [comment]
https://gist.github.com/grobie/a3e11009b8397cd5ef1adfde655de2a5

**Comment by jaqx0r** [comment]
Goroutines 14 and 15 look like culprits here.

**Comment by jaqx0r** [comment]
Can you tell me what git commit you have built mtail at so I can correlate those stacktraces?

There's a failed watch remove in the logbefore it looks like it tries to add a watch, and blocks on the lock (the semacquire) which appears to block the chan send goroutine.  Just a hypotheis at this stage.

**Comment by grobie** [comment]
It was an earlier commit version, but I can reproduce this on master (6e0eac2) as well. https://gist.github.com/grobie/c2c53a3a565605efa0485114faf460dc

**Comment by jaqx0r** [comment]
Thanks!

**Comment by jaqx0r** [comment]
Yep I think what is happening is tail.go:208 (goroutine 41 in the last gist) is blocking the run() loop in the same routine from taking the next item off the queue, which causes the [chan send] in 40 to block; which means the watcher cannot receive the shutdown message (that Events is closed, from mtail.shutdownHandler()->tailer.Close()->logwatcher->Close())

Why the goroutine 41 is blocked on the semacquire is curious.    fsnotify.v1/inotify.go says that it's waiting for "ignoreLinux" deletes maps, ignoreLinux() only runs in the readevents loop which is running in routine 34, and that one is blocked in a syscall to wait on the fd for new notifications.

I wonder what happened to fsnotify in the logs earlier when:
I0505 01:58:15.582756   29528 tail.go:210] Failed removing watches on/home/grobie/code/go/src/github.com/google/mtail/test/logs/current
occurred.
I'm going to patch the log message to be more verbose, then I'll have to get you to run the test again.

**Comment by jaqx0r** [comment]
Please update your source tree, and rebuild at 827bd74 Merge branch 'sigterm'

**Comment by SuperQ** [comment]
Cool, It's a public holiday for me, but @grobie can also probably build and test this fix.

**Comment by SuperQ** [comment]
It looks like you reverted part of the sigterm fix.

**Comment by jaqx0r** [comment]
I don't think it is a fix, is why. It causes the race detector to fail the
tests and I think it isn't fixing the root cause. It was a guess and now
I've seen the stack trace I think it was ineffective.

**Comment by SuperQ** [comment]
Sorry, I didn't mean to imply that it was actually a fix.  @grobie noticed the race condition and suggested I hold off on additional testing.  I should have reported that earlier.

We have been running mtail with our production load for a while now, but only when I introduced a counter for every line did we start seeing issues with random lockup.

**Comment by jaqx0r** [comment]
Is that after I added that code?  Or if not, it sounds like another data
point, if you can get a stack dump when it happens that will be great.

Also, what ballpark number of programs, variables exported, concurrent
input logs, and line rate does your mtail run with?

**Comment by SuperQ** [comment]
No, before the lock code.  I will see about getting a stack dump.

The mtail instance that crashes has one config file with
* 10 metrics with a number of labels
* 600-700 metrics exported
* 1 input log
* ~15 regexp matchers

Instances seem to be prone to partial lockup (stops reading log lines) around 300 lines/sec, and are much more prone at ~800 lines/sec.

**Comment by SuperQ** [comment]
@beorn7 traced this a bit, and thinks it is a bug in fsnotify, it turns out my build was using an out of date (Feb 22) `fsnotify.v1` tree.  I have updated and will try out a new binary build.

**Comment by beorn7** [comment]
With the up-to-date version of fsnotify, the same deadlock happens. It seems to be connected to removing a watcher. It is either a bug in the way mtail uses fsnotify, or it is a bug within fsnotify.
I'll investigate more and let you know.

**Comment by beorn7** [comment]
So I think I have found the problem. I'll prepare a PR for review.

**Comment by beorn7** [comment]
Ugh, have to jump through bureaucracy hoops first...

**Comment by jaqx0r** [comment]
Thanks!

**Comment by jaqx0r** [comment]
Please pull past 7252e33 to fix another race on log rotation.

**Comment by SuperQ** [comment]
Ok, I'll build and get that into testing soon.

**Comment by SuperQ** [comment]
Everything seems to be fine with the new patch as well.

**Comment by jaqx0r** [comment]
Excellent!
