### ISSUE TITLE
max/min values

### ISSUE THREAD

**Issue by chiganov** [google/mtail#272]
Hello

I want to get max/min values and this code doesn't work for me.
Where am i wrong?

```
counter timing_total
counter timing_counter
counter max_timing


/^"(?P<request_method>[A-Z]+) / {
  /\/check-widget\?t=(?P<timing>\d+)/ {
    timing_counter++
    timing_total+=$timing
    $timing > max_timing {
      max_timing = $timing
    }
  }
}
```

I mean If I use in condition constant, for example `$timing>200` or `max_timing>200` it works but If I compare regex variable and counter it don't.

**Comment by chiganov** [comment]
Sorry, It was my problem. I used mtail from ubuntu repository version 3.0.0~rc5, now I use actual relise and it work.

**Comment by jaqx0r** [comment]
good to hear, thanks for letting me know!
