### ISSUE TITLE
unable to read from unix socket

### ISSUE THREAD

**Issue by xinau** [google/mtail#276]
It seems like systemd-journald support was left out due to the possiblity to read from a named pipe or unix socket. While trying to configure mtail to read from the `/run/systemd/journal/syslog` where systemd-journald forwards all messages to, I got the following error
```
...
I1108 13:21:25.043783    2636 loader.go:224] Loaded program linecount.mtail
I1108 13:21:25.043926    2636 mtail.go:99] Tail pattern "/run/systemd/journal/syslog"
I1108 13:21:25.044052    2636 tail.go:134] AddPattern: /run/systemd/journal/syslog
I1108 13:21:25.044189    2636 log_watcher.go:268] Adding a watch on resolved path "/run/systemd/journal"
I1108 13:21:25.044335    2636 log_watcher.go:248] No abspath in watched list, added new one for /run/systemd/journal
I1108 13:21:25.044479    2636 tail.go:158] glob matches: [/run/systemd/journal/syslog]
I1108 13:21:25.044620    2636 log_watcher.go:268] Adding a watch on resolved path "/run/systemd/journal/syslog"
I1108 13:21:25.044744    2636 log_watcher.go:248] No abspath in watched list, added new one for /run/systemd/journal/syslog
I1108 13:21:25.044886    2636 tail.go:265] openlogPath /run/systemd/journal/syslog false
I1108 13:21:25.045035    2636 log_watcher.go:268] Adding a watch on resolved path "/run/systemd/journal"
I1108 13:21:25.045174    2636 log_watcher.go:253] Found this processor in watched list
I1108 13:21:25.045315    2636 file.go:52] file.New(/run/systemd/journal/syslog, false)
I1108 13:21:25.045454    2636 file.go:111] open failed all retries
W1108 13:21:25.045577    2636 mtail.go:101] attempting to tail "/run/systemd/journal/syslog": open /run/systemd/journal/syslog: no such device or address
...
```

mtail version and command line
```
$ sudo mtail --logs /run/systemd/journal/syslog --progs . --logtostderr -v 5
I1108 13:21:25.037480    2636 main.go:100] mtail version v3.0.0-rc33 git revision aedde73f9c304e4d558a53ece22a5472c87a7fdb go version go1.12.7 go arch amd64 go os linux
```

Related Issues: #58

**Comment by jaqx0r** [comment]
Can you do an ls -al /run/systemd/journal/syslog please?

**Comment by jaqx0r** [comment]
Also can you take a look at #281 and see if that looks the same?

**Comment by xinau** [comment]
> Can you do an ls -al /run/systemd/journal/syslog please?

```
$ ls -al /run/systemd/journal/syslog 
srw-rw-rw- 1 root root 0 Dec 13 22:08 /run/systemd/journal/syslog
```

I also don't see the behavior mentioned in #281. Just the behavior mentioned above.

**Comment by xinau** [comment]
This is the output recieved after restarting `systemd-journald`
```
I1213 22:23:35.463206    2210 log_watcher.go:202] watcher event "/run/systemd/journal/kernel-seqnum": WRITE
I1213 22:23:35.463253    2210 tail.go:234] No file handle found for "/run/systemd/journal/kernel-seqnum", but is being watched
I1213 22:23:35.463271    2210 tail.go:308] "/run/systemd/journal/kernel-seqnum" did not match pattern "/run/systemd/journal/syslog"
I1213 22:23:35.463280    2210 tail.go:328] did not start tailing "/run/systemd/journal/kernel-seqnum"
^CI1213 22:23:37.651456    2210 mtail.go:349] Received SIGTERM, exiting...
I1213 22:23:37.651474    2210 mtail.go:363] Shutdown requested.
I1213 22:23:37.657792    2210 log_watcher.go:218] Shutting down log watcher.
I1213 22:23:37.657815    2210 loader.go:376] Shutting down loader.
I1213 22:23:37.657899    2210 mtail.go:386] END OF LINE
```

Also the `/metrics` endpoint is available the hole time.

**Comment by jaqx0r** [comment]
Can you please run mtail with the flag --vmodule=file=2,log_watcher=2 and
share the log?

**Comment by xinau** [comment]
```
$ sudo mtail --logs /run/systemd/journal/syslog --progs . --logtostderr -vmodule=file=2,log_watcher=2
I1217 21:03:23.931100    8447 main.go:100] mtail version v3.0.0-rc33 git revision aedde73f9c304e4d558a53ece22a5472c87a7fdb go version go1.12.7 go arch amd64 go os linux
I1217 21:03:23.931241    8447 main.go:101] Commandline: ["mtail" "--logs" "/run/systemd/journal/syslog" "--progs" "." "--logtostderr" "-vmodule=file=2,log_watcher=2"]
I1217 21:03:23.933492    8447 log_watcher.go:268] Adding a watch on resolved path "/home/ubuntu"
I1217 21:03:23.933601    8447 log_watcher.go:248] No abspath in watched list, added new one for /home/ubuntu
I1217 21:03:23.933822    8447 log_watcher.go:268] Adding a watch on resolved path "/run/systemd/journal"
I1217 21:03:23.933921    8447 log_watcher.go:248] No abspath in watched list, added new one for /run/systemd/journal
I1217 21:03:23.934009    8447 log_watcher.go:268] Adding a watch on resolved path "/run/systemd/journal/syslog"
I1217 21:03:23.934079    8447 log_watcher.go:248] No abspath in watched list, added new one for /run/systemd/journal/syslog
I1217 21:03:23.934130    8447 log_watcher.go:268] Adding a watch on resolved path "/run/systemd/journal"
I1217 21:03:23.934178    8447 log_watcher.go:253] Found this processor in watched list
I1217 21:03:23.934237    8447 file.go:52] file.New(/run/systemd/journal/syslog, false)
I1217 21:03:23.934294    8447 file.go:111] open failed all retries
W1217 21:03:23.935320    8447 mtail.go:101] attempting to tail "/run/systemd/journal/syslog": open /run/systemd/journal/syslog: no such device or address
I1217 21:03:23.935721    8447 store.go:136] Starting metric store expiry loop every 1h0m0s
I1217 21:03:23.935779    8447 tail.go:435] Starting log handle expiry loop every 1h0m0s
I1217 21:03:23.935844    8447 mtail.go:321] Listening on [::]:3903
^CI1217 21:03:30.396320    8447 mtail.go:349] Received SIGTERM, exiting...
I1217 21:03:30.396339    8447 mtail.go:363] Shutdown requested.
I1217 21:03:30.401359    8447 log_watcher.go:218] Shutting down log watcher.
I1217 21:03:30.401373    8447 loader.go:376] Shutting down loader.
I1217 21:03:30.401429    8447 mtail.go:386] END OF LINE
```

**Comment by jaqx0r** [comment]
OK thanks, I can reproduce this locally.

https://www.freedesktop.org/wiki/Software/systemd/syslog/ suggests reading
from this socket isn't correct, though.  I can't decipher what *is*
supposed to be correct.

**Comment by jaqx0r** [comment]
Aha.

The problem is that mtail reads from named pipes, not unix sockets.  The
code is failing because it's attempting to open the unix socket
/run/systemd/journal/syslog as a named pipe, which fails because there is
"no such device or address" called that.

The clue was eventually I read man 7 pipe and then thought "Am I sure the s
at the start of the ls before is in fact a named pipe?" and then the ls
info page revealing to me it's in fact a socket...

I have a funny feeling I deleted some code about two years ago that did
this.

**Comment by xinau** [comment]
I seem to struggle to find the location where the documentation you referenced says that a syslog daemon should read from another location. Instead it suggest using this socket location instead of `/dev/log`.

> If your logging daemon wants to get access to all logging data then it should listen on /run/systemd/journal/syslog instead via the syslog.socket unit file that is shipped along with systemd

> I have a funny feeling I deleted some code about two years ago that did this.

No worries happens to the best of us :).

**Comment by jaqx0r** [comment]
Try now from HEAD!

**Comment by jaqx0r** [comment]
Ah, this is not fixed yet.  I didn't fully test against the syslog socket and it's not properly supported.

**Comment by jaqx0r** [comment]
Please take another look at HEAD now, and let me know how it goes.  Add the text ",log=2,socket=2" to the earlier vmodule flag.


`sudo mtail --logs /run/systemd/journal/syslog --progs . --logtostderr -vmodule=file=2,log=2,socket=2`

**Comment by xinau** [comment]
Thanks, will give it a try. And will let you know of the results

**Comment by jaqx0r** [comment]
Any news on this?  Thanks!

**Comment by xinau** [comment]
First of all sry for the late reply. I've got some news. 
When running mtail from HEAD with the arguments from above I get the following output. 
```
I0124 12:07:36.529033   15567 main.go:100] mtail version v3.0.0-rc34 git revision 7b4270cb6e8b6ed1f2febe48e370cb68d38681f9 go version go1.12.15 go arch amd64 go os linux
I0124 12:07:36.529190   15567 main.go:101] Commandline: ["./mtail" "--logs" "/run/systemd/journal/syslog" "--progs" "progs/" "--logtostderr" "-vmodule=file=2,log=2,socket=2"]
I0124 12:07:36.543722   15567 log_watcher.go:249] No abspath in watched list, added new one for /home/ubuntu/progs
I0124 12:07:36.547668   15567 loader.go:229] Loaded program linecount.mtail
I0124 12:07:36.547819   15567 log_watcher.go:249] No abspath in watched list, added new one for /run/systemd/journal
I0124 12:07:36.547947   15567 log_watcher.go:249] No abspath in watched list, added new one for /run/systemd/journal/syslog
I0124 12:07:36.548045   15567 log_watcher.go:254] Found this processor in watched list
I0124 12:07:36.548124   15567 log.go:33] tailer.NewLog(/run/systemd/journal/syslog, false)
I0124 12:07:36.548177   15567 socket.go:31] tailer.NewSocket(/run/systemd/journal/syslog)
W0124 12:07:36.548253   15567 mtail.go:101] attempting to tail "/run/systemd/journal/syslog": listen unixgram /run/systemd/journal/syslog: bind: address already in use
I0124 12:07:36.548542   15567 store.go:136] Starting metric store expiry loop every 1h0m0s
I0124 12:07:36.548621   15567 tail.go:446] Starting log handle expiry loop every 1h0m0s
I0124 12:07:36.548672   15567 mtail.go:321] Listening on [::]:3903
```

This results in and `address already in use` error which after some investigation happens due to the following line of code https://github.com/google/mtail/blob/72d2a6092ce58288b3016aa1387fea94a7071c48/internal/tailer/socket.go#L32
when changing mentioned line as follows 

```diff
-       c, err := net.ListenUnixgram("unixgram", &net.UnixAddr{absPath, "unixgram"})
+       c, err := net.Dial("unixgram", absPath)
```

the above command results in a 
```
I0124 12:14:03.438437   15591 main.go:100] mtail version v3.0.0-rc34-3-g901261b-dirty git revision 901261b38470236a5d528d8220faaa607529a013 go version go1.12.3 go arch amd64 go os linux
I0124 12:14:03.438577   15591 main.go:101] Commandline: ["./mtail.3" "--logs" "/run/systemd/journal/syslog" "--progs" "progs/" "--logtostderr" "-vmodule=file=2,log=2,socket=2"]
I0124 12:14:03.458601   15591 log_watcher.go:249] No abspath in watched list, added new one for /home/ubuntu/progs
I0124 12:14:03.462290   15591 loader.go:229] Loaded program linecount.mtail
I0124 12:14:03.463411   15591 log_watcher.go:249] No abspath in watched list, added new one for /run/systemd/journal
I0124 12:14:03.463524   15591 log_watcher.go:249] No abspath in watched list, added new one for /run/systemd/journal/syslog
I0124 12:14:03.463607   15591 log_watcher.go:254] Found this processor in watched list
I0124 12:14:03.463708   15591 log.go:33] tailer.NewLog(/run/systemd/journal/syslog, false)
I0124 12:14:03.463782   15591 socket.go:31] tailer.NewSocket(/run/systemd/journal/syslog)
I0124 12:14:03.463891   15591 log_watcher.go:254] Found this processor in watched list
I0124 12:14:03.463946   15591 tail.go:300] Tailing /run/systemd/journal/syslog
I0124 12:14:03.464152   15591 store.go:136] Starting metric store expiry loop every 1h0m0s
I0124 12:14:03.464234   15591 tail.go:446] Starting log handle expiry loop every 1h0m0s
I0124 12:14:03.464285   15591 mtail.go:321] Listening on [::]:3903
```

But nevertheless it doesn't seem to work when issuing a command like `systemd-cat mtail` the `mtail_lines_total` is still zero.

After reading some more documentation about the `syslog.socket` at https://wiki.freedesktop.org/www/Software/systemd/syslog/ I found the following snippet

> Of course, only one implementation of BSD syslog can own that symlink, and hence only one implementation can be enabled at a time

Which makes me question the hole approach for reading the journal with mtail as it's probably better to read from some output of a syslog daemon instead.

But I still wonder where the issue lies as I'm also unable to configure mtail to read from a `unix` socket created with `socat - UNIX-LISTEN:/tmp/mtail.sock` (`mtail --logs /tmp/mtail.sock`). Which results in no error meaningful output if mtail is executed after the socat command, but if mtail is executed before a read timeout gets logged.

```diff
-       c, err := net.ListenUnixgram("unixgram", &net.UnixAddr{absPath, "unixgram"})
+       c, err := net.Dial("unix", absPath)
```

```
I0124 12:40:24.323278   15699 main.go:100] mtail version v3.0.0-rc34-3-g901261b-dirty git revision 901261b38470236a5d528d8220faaa607529a013 go version go1.12.3 go arch amd64 go os linux
I0124 12:40:24.323423   15699 main.go:101] Commandline: ["./mtail.2" "--logs" "/tmp/mtail.sock" "--progs" "progs/" "--logtostderr" "-vmodule=file=2,log=2,socket=2"]
I0124 12:40:24.324273   15699 log_watcher.go:249] No abspath in watched list, added new one for /home/ubuntu/progs
I0124 12:40:24.324673   15699 loader.go:229] Loaded program linecount.mtail
I0124 12:40:24.324815   15699 log_watcher.go:249] No abspath in watched list, added new one for /tmp
W0124 12:40:24.324942   15699 mtail.go:101] No matches for pattern "/tmp/mtail.sock"
I0124 12:40:24.325094   15699 store.go:136] Starting metric store expiry loop every 1h0m0s
I0124 12:40:24.325152   15699 tail.go:446] Starting log handle expiry loop every 1h0m0s
I0124 12:40:24.325226   15699 mtail.go:321] Listening on [::]:3903
I0124 12:40:29.579127   15699 log_watcher.go:254] Found this processor in watched list
I0124 12:40:29.579249   15699 log.go:33] tailer.NewLog(/tmp/mtail.sock, true)
I0124 12:40:29.579381   15699 log.go:47] ignoring seekToStart=true as "/tmp/mtail.sock" is a socket
I0124 12:40:29.579462   15699 socket.go:31] tailer.NewSocket(/tmp/mtail.sock)
I0124 12:40:29.590932   15699 log_watcher.go:249] No abspath in watched list, added new one for /tmp/mtail.sock
I0124 12:40:29.591052   15699 tail.go:300] Tailing /tmp/mtail.sock
I0124 12:40:30.591400   15699 socket.go:72] read count 0 err read unix @->/tmp/mtail.sock: i/o timeout
I0124 12:40:30.591538   15699 socket.go:77] timeout, returning
```

When I build mtail from HEAD and start mtail and use `socat - UNIX-CONNECT:/tmp/mtail.sock` I get the following output form socat

```
2020/01/24 12:44:26 socat[15718] E connect(5, AF=1 "/tmp/mtail.sock", 17): No such file or directory
```

due to mtail not creating the listening socket as their are no matches found for `/tmp/mtail.sock`

```
I0124 12:44:18.429556   15710 main.go:100] mtail version v3.0.0-rc34 git revision 7b4270cb6e8b6ed1f2febe48e370cb68d38681f9 go version go1.12.15 go arch amd64 go os linux
I0124 12:44:18.429687   15710 main.go:101] Commandline: ["./mtail" "--logs" "/tmp/mtail.sock" "--progs" "progs/" "--logtostderr" "-vmodule=file=2,log=2,socket=2"]
I0124 12:44:18.430549   15710 log_watcher.go:249] No abspath in watched list, added new one for /home/ubuntu/progs
I0124 12:44:18.430949   15710 loader.go:229] Loaded program linecount.mtail
I0124 12:44:18.431069   15710 log_watcher.go:249] No abspath in watched list, added new one for /tmp
W0124 12:44:18.431158   15710 mtail.go:101] No matches for pattern "/tmp/mtail.sock"
I0124 12:44:18.431379   15710 store.go:136] Starting metric store expiry loop every 1h0m0s
I0124 12:44:18.431436   15710 tail.go:446] Starting log handle expiry loop every 1h0m0s
I0124 12:44:18.431509   15710 mtail.go:321] Listening on [::]:3903
```

I hope this helps a little bit.

**Comment by jaqx0r** [comment]
The section you quoted from the systemd docs is why mtail tries to listen
instead of dial! I tried to shut off rsyslog so mtail could receive on the
socket but I think I agree with you that mtail shouldn't replace rsyslog or
equivalent, and instead have the operator configure rsyslog and not systemd
to send to mtail.

I'll update the docs and be interested to see how you set up your logger to
forward to mtail, and if we need to alter the socket code more to do so.

**Comment by jaqx0r** [comment]
I'm going to try a test case with socat as you've shown me to try to make
mtail more robust to sockets, but I don't think it can ever handle systemd
journal per the systemd protocol.

**Comment by jaqx0r** [comment]
Great news here, I've figured out why mtail isn't creating sockets to receive logs at all, it's protected by a code path that is trying to stat the file first so if no socket exists it never gets to the point of trying to listen on it.

I'm going to fix this by requiring the user to specify a prefix like "unixgram:" before the pathname.

**Comment by CoolDreamZ** [comment]
sorry if this is off-topic, I am also working on tailing the systemd journal and find that using a named pipe is working well (so far!). Why use the .../syslog socket when this works:

**in one terminal session create a named pipe 'pipe' and tail journal to it:**

<img width="321" alt="Screenshot 2020-12-15 at 11 10 36" src="https://user-images.githubusercontent.com/70951446/102208012-c9802f80-3ec6-11eb-876e-6402fe2bb6b0.png">

**in another terminal session run mtail to read log from 'pipe':**

<img width="470" alt="Screenshot 2020-12-15 at 11 21 44" src="https://user-images.githubusercontent.com/70951446/102208803-c2a5ec80-3ec7-11eb-90a2-47407c78252b.png">


Is this a reasonable approach? am I missing something??

**Comment by jaqx0r** [comment]
Yes it's reasonable to mkfifo before mtail reads it, but a fifo is not a socket, it's a named pipe.  If we could make a socket that would work, but AFAIK the listener has to create the socket itself.

mtail's named pipe implementation is satisfactory, but not its socket reader.

**Comment by CoolDreamZ** [comment]
Thanks for confirming the named pipe approach, it is working well for me  :-)

Digging deeper it seems to me that binding to the syslog socket is not the way to tail the systemd journal . The very last line of the [docs](https://wiki.freedesktop.org/www/Software/systemd/syslog/) states "_And remember: don't ship any socket unit for /dev/log or /run/systemd/journal/syslog (**or even make your daemon bind directly to these sockets**)! That's already shipped along with systemd for you._"

On my system `rsyslogd.service` is bound to the `/run/systemd/journal/syslog` socket by `systemd` at startup. Looks like this:

<img width="883" alt="Screenshot 2020-12-17 at 07 05 30" src="https://user-images.githubusercontent.com/70951446/102455028-c906a680-4036-11eb-9708-38f8e3242f4f.png">

**Comment by CoolDreamZ** [comment]
There is also an example [here](https://www.rsyslog.com/how-to-write-to-a-local-socket/) of setting up rsyslog to forward messages to a unix socket (via socat) which may help if a socket is required instead of a named pipe

**Comment by jaqx0r** [comment]
Here's a quick summary of what I've learned while building socket support.

traditional `syslog()` sends to `/dev/log`, which is a unix domain datagram socket, and normally a syslogd listens on it for logs to then write to whereever.

Nowadays on Linux, the `systemd-journal` process handles logs from userspace, kernel, and keeps them in the journal.  `journalctl` lets you poke around with them, and `systemd-journal` will also forward them on to a `syslogd` if one is listening on the correct unix-dgram socket.

To receive logs directly from systemd-journal, one must be able to read from a unix domain socket.  `mtail` now does this, although I kind of regret it.  Socket support for both datagram and stream families was tricky and likely has many future bugs.

Normally your distro will have one of `syslog-ng` or `rsyslogd` acting as that `syslogd`, though.

I strongly do not recommend `mtail` being the direct listener of `/dev/log` or the `systemd` journal.   `mtail` does not perform any ordinary syslog functions, it merely matches text file inputs and increments counters.  The interoperation of `systemd` and the `syslogd` appears to be a rich API and tools like `syslog-ng` automatically support `systemd-journal` in the normal course of their role.  `mtail` doesn't want to be in the business of specific API interoperation, for at least two reasons: one is binary size as a result of features, and the other is maintenance cost.

So, if you want to interoperate `mtail` with syslog, then I suggest using the above syslog daemons to "tee" off the logs you're interested in:

* rsyslog supports forwarding to a [named pipe](https://www.rsyslog.com/doc/master/configuration/modules/ompipe.html) and to a [unix domain socket](https://www.rsyslog.com/doc/master/configuration/modules/omuxsock.html)

* syslog-ng supports output to [named pipe](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/44#TOPIC-1595018) and [unix domain socket](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/54#TOPIC-1595060)

Configure `mtail` to listen on that pipe or unix domain socket, and you'll get what you want.

`mtail`'s filtering is not great -- you have to get to the match program before yuo end up discarding log entries, which is expensive in terms of memory copies. With both the above tools you have lots of power for filtering which input gets sent to the `mtail` pipe.

**1: Do not replace your syslog with mtail, you will lose a lot of functionality and reliability.**


I also wouldn't recommend using `mtail` to receive cross-network log traffic.  Firstly it's not lossless, for all the reasons that the rsyslog's [RELP](https://www.rsyslog.com/doc/v8-stable/tutorials/reliable_forwarding.html) protocol exists.  `mtail` isn't that smart; `mtail` doesn't want to be in the business of reliable network transport; it just wants to tail a log stream as fast as possible and turn that into metrics.

If I wanted a single `mtail` central service reading logs from multiple remote nodes, I'd use `rsyslogd` to perform the log transport, and a local named pipe to funnel the bytes from the receiver `rsyslogd` to `mtail`.


**2: Do not let `mtail` listen on a network for logs, prefer a reliable log transport option and then a local forward over a Unix named pipe.**

*Why would I recommend a pipe over a socket?*  The overhead is lower, so the bytes move faster.  The read semantics are nearly identical to a file and thus well tested.  Sockets are OK but the connection oriented stream now incurs an API cost (we're now listening on an address anyone can connect to) and complexifies the implementation (multiple connection handlers are possible) and the datagram socket violates the interface by not having any concept of "end of transmission", though the workaround is a neat hack.
