### ISSUE TITLE
[Request] static linked binary option.

### ISSUE THREAD

**Issue by ota-akira** [google/mtail#280]
Hi, product owner.
Thank you for your mtail product and polite work.
It is brilliant product for me and my work.

My request is simple.
Could you provide static linked binaries Or add to static link build option into the Makefile.

Because, I want run the mtail on minimum size container (like a Docker's scratch image or apline).

Thank you.

**Comment by jaqx0r** [comment]
Hey,

mtail is a Go program and so it alreayd is a staticly linked binary when
built.

There's a Dockerfile that you can use to build yourself a container, or you
could look at the releases page here
https://github.com/google/mtail/releases to download a prebuilt binary.

**Comment by ota-akira** [comment]
Hi.
I understand mtail is a Go program and provide pre build binary.
but, it looks not static linked binary.

```bash
$ file mtail_v3.0.0-rc33_linux_amd64
mtail_v3.0.0-rc33_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
```

Currently, I rewrite Makefile bellow.

```diff
@@ -114,7 +114,7 @@
 # runs can read the dependencies and update iff they change.
 $(TARGETS): %: cmd/%/main.go $(DEPDIR)/%.d | .dep-stamp
    $(MAKEDEPEND)
-   GO111MODULE=on go build -ldflags $(GO_LDFLAGS) -o $@ $<
+   CGO_ENABLED=0 go build -ldflags '-w -s -extldflags "-static"' -o $@ $<

 internal/vm/parser/parser.go: internal/vm/parser/parser.y | $(GOYACC)
    go generate -x ./$(@D)
```

Thankyou.

**Comment by jaqx0r** [comment]
Aha thanks for the info, now I understand.

**Comment by jaqx0r** [comment]
Thanks for the report!  Please check out the latest in HEAD to see if that helps your case!

You will need to call it as `make STATIC=y` to set the magic option that enables static builds.  The Dockerfile does this now by default.

**Comment by jaqx0r** [comment]
I must have typoed the commit message to link it to this report.   1667947cbcb2a1066a5b71e3119444a93414f984 contains the fix.

**Comment by ota-akira** [comment]
@jaqx0r 
Thank you for rapid work! 😄
