### ISSUE TITLE
complex conditions

### ISSUE THREAD

**Issue by sevaTechoPark** [google/mtail#282]
line:
`(is_url_matched == 1 || $request_uri =~ // + URL_START_WHITE_LIST) && $request_uri !~ // + URL_BLACK_LIST {`
`some usefull code...`
`}`

throw:
```
compile failed for nginx.mtail: nginx.mtail:180:91-109: Redeclaration of capture group `0' previously declared at nginx.mtail:180:45-69 nginx.mtail:180:91-109: Redeclaration of capture group `1' previously declared at nginx.mtail:180:45-69
```

how can I write this: **(condition OR condition) AND condition {...}**

**Comment by sevaTechoPark** [comment]
oooh, sorry, my problem was with `// + `

**Comment by jaqx0r** [comment]
Yeah the problem is with the automatic capture group references. There's
two expressions in that line and so they both create the variables in scope
and then you get the error.

One way to avoid it is to split at the && and put the second expression in
an inner pattern match block.
