### ISSUE TITLE
HTTP compression for metrics

### ISSUE THREAD

**Issue by filippog** [google/mtail#283]
Hi,
I'm using mtail on a single host to extract ~14k Prometheus metrics, thus `/metrics` is ~2.7MB and it can generate significant amounts of traffic when polled frequently enough. Is compressing HTTP responses something that could be added to mtail? Thanks!

**Comment by anthraxn8b** [comment]
If you tend to implement it please directly support brotli.

Workaround: nginx reverse proxy with the correct compression flag set.

**Comment by jaqx0r** [comment]
I've found some example compression code using Brotli here: https://github.com/andybalholm/redwood/blob/03647265e47f77b9a4ed9fa7a8d1f146e04f456f/proxy.go

**Comment by jaqx0r** [comment]
I think you get compression already?

https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promhttp#HandlerOpts which we don't modify, so as long as the HTTP client requests compression I expect you'd get it.

If you want brotli, you'll have to take it up with the prometheus/client_golang maintainers.
