### ISSUE TITLE
mtail stop to work for one hours

### ISSUE THREAD

**Issue by arrow2012** [google/mtail#287]
mtail log:

![image](https://user-images.githubusercontent.com/46478986/71962660-e0d58800-3234-11ea-9c84-bd3d902c13f7.png)

mtail_lines_total   is still growing

but other metrics count did not grow any more

**Comment by jaqx0r** [comment]
I'm gunna need more information than that please.

Take a look at
https://github.com/google/mtail/blob/master/docs/Troubleshooting.md first.


I'm also interested in knowing what the log is doing, can you run mtail
with the flag --vmodule=tail=2,log_watcher=2 and share the whole log please

**Comment by arrow2012** [comment]
[session.log](https://github.com/google/mtail/files/4034638/session.log)



mtail version v3.0.0-rc33 git revision aedde73f9c304e4d558a53ece22a5472c87a7fdb go version go1.12.7 go arch amd64 go os linux
