### ISSUE TITLE
mailing list not accessible anymore?

### ISSUE THREAD

**Issue by bbigras** [google/mtail#293]
I saw the mailing list's URL in the README but when I try to access it I get some message saying that either the group doesn't exist anymore or that I don't have access to see it.

**Comment by pgporada** [comment]
I'm unable to access the group too.

**Comment by jaqx0r** [comment]
I don't know what you are seeing but when I clicked on the link I got taken to the group page and see that it has messages on it, people are able to join without restriction, non-members can post with moderation, members can post without moderation.

Please attach screenshots or paste error messages so I can see what you see.

**Comment by bbigras** [comment]
![image](https://user-images.githubusercontent.com/24027/100691737-3ea91c00-3381-11eb-90fa-957bab8e1bd2.png)

**Comment by jaqx0r** [comment]
Merci beaucoup

**Comment by jaqx0r** [comment]
Please try again now!  I think I have found the setting that must be new that restricted who can even see the group.

**Comment by bbigras** [comment]
It works now :tada: Thanks!

**Comment by jaqx0r** [comment]
Phew, thanks for reporting!
