### ISSUE TITLE
Do not exit with status code 1 when given -version flag

### ISSUE THREAD

**Issue by drzero42** [google/mtail#295]
I am maintaining a tool that helps install and update commandline utilities distributed as single binaries through Github, just like mtail is. (The tool is called [vk](https://github.com/cellpointmobile/vk)) This is done in part by parsing the version output from the utility itself. However, mtail does something that no other utility seems to do, it exits with status code 1, instead of 0 when given the -version flag. As you probably are aware, any exit status code above 0 is considered an error in Posix programs. Therefore vk can not, without ugly hacks, handle mtail.
Would you be open to having mtail exit with status code 0 when outputting version info?

**Comment by jaqx0r** [comment]
That sounds like a great idea.
