### ISSUE TITLE
how to deal with incremental logs?

### ISSUE THREAD

**Issue by cleverchou** [google/mtail#298]
For example:  there are  10 lines  in the original log, and I can get  lines = 10. After a new line is wrote, it will be 21,  which is actually 11.
how to do ?

Thanks!

**Comment by jaqx0r** [comment]
Please share the command line you run mtail with, and the version, and the
full info log when this happens.

Also can you say again, are you expecting the result to be 11 or 21? I
assume that you are getting 21 and it should be 11.

**Comment by cleverchou** [comment]
1、./mtail -version
mtail version  git revision  go version go1.13.8 go arch amd64 go os linux
2、 command line
./mtail -port 9100 -progs /home/xxxx/stat  -logs /home/xxxx/data  -emit_metric_timestamp -override_timezone "Local"
3、cat stat/xxx.mtail
counter allreco  
/^/ +
/\d+/ +
/\s+(?P<sip_p>\d+\.\d+\.\d+\.\d+)/ +
/\s+(?P<dip_p>\d+\.\d+\.\d+\.\d+)/ +
/\s+(?P<sp_p>\d+)/ +
/\s+(?P<dp_p>\d+)/ +
/\s+(?P<flags_p>\w+)/ +
/\s+(?P<no_p>\d+)/ +
/\s+/ + 
/$/ {

# line count
    allreco++
}
4、cat data
1 10.0.0.10 193.0.0.51 65535 6789 tcp  1938310 
1 157.0.0.95 56.0.0.43 65535 61400 tcp  110886 
1 58.0.0.158 193.0.0.182 0 1704 tcp  12777 
1 43.0.0.216 193.0.0.183 0 6000 tcp  66915 
1 142.0.0.87 56.0.0.40 0 1352 tcp  77793 
1 135.0.0.30 56.40.0.10 1707 tcp  48335 
1 163.0.0.12 56.0.0.134 0 1221 udp  75386 
1 239.0.0.202 89.0.0.178 65535 1521 tcp  60492 
1 157.0.0.30 56.40.0.40 65535 15126 tcp  76649 
1 255.0.0.109 89.0.149.214 0 1521 tcp  11421 
5、results
First time  I will get allreco=10; when  a new line is wrote into data , I will get allreco=21;  but there are 11 lines in data

**Comment by jaqx0r** [comment]
Normally mtail logs go to /tmp/mtail.INFO.  Can you please add the
commandline flag --vmodule=tail=2,log_watcher=2 , reproduce this, and then
send the INFO log here?

**Comment by cleverchou** [comment]
After adding the new line, show:

I0228 10:43:23.781523    3239 log_watcher.go:203] watcher event "/home/XXXX/filter_test/.goutputstream-U8HHG0": CREATE
I0228 10:43:23.781564    3239 tail.go:234] No file handle found for "/home/XXXX/filter_test/.goutputstream-U8HHG0", but is being watched
I0228 10:43:23.781578    3239 tail.go:321] "/home/XXXX/filter_test/.goutputstream-U8HHG0" did not match pattern "/home/XXXX/filter_test/data"
I0228 10:43:23.781589    3239 tail.go:341] did not start tailing "/home/XXXX/filter_test/.goutputstream-U8HHG0"
I0228 10:43:23.781597    3239 tail.go:244] Internal error finding file handle for "/home/XXXX/filter_test/.goutputstream-U8HHG0" after create
I0228 10:43:23.781617    3239 log_watcher.go:203] watcher event "/home/XXXX/filter_test/.goutputstream-U8HHG0": CHMOD
I0228 10:43:23.781630    3239 tail.go:234] No file handle found for "/home/XXXX/filter_test/.goutputstream-U8HHG0", but is being watched
I0228 10:43:23.781638    3239 tail.go:321] "/home/XXXX/filter_test/.goutputstream-U8HHG0" did not match pattern "/home/xxxx/filter_test/data"
I0228 10:43:23.781646    3239 tail.go:341] did not start tailing "/home/XXXX/filter_test/.goutputstream-U8HHG0"
I0228 10:43:23.781652    3239 tail.go:244] Internal error finding file handle for "/home/XXXX/filter_test/.goutputstream-U8HHG0" after create
I0228 10:43:23.791653    3239 log_watcher.go:203] watcher event "/home/XXXX/filter_test/.goutputstream-U8HHG0": WRITE
I0228 10:43:23.791711    3239 tail.go:234] No file handle found for "/home/XXXX/filter_test/.goutputstream-U8HHG0", but is being watched
I0228 10:43:23.791735    3239 tail.go:321] "/home/XXXX/filter_test/.goutputstream-U8HHG0" did not match pattern "/home/zhoucong/filter_test/data"
I0228 10:43:23.791753    3239 tail.go:341] did not start tailing "/home/XXXX/filter_test/.goutputstream-U8HHG0"
I0228 10:43:23.791770    3239 tail.go:244] Internal error finding file handle for "/home/XXXX/filter_test/.goutputstream-U8HHG0" after create
I0228 10:43:23.795034    3239 log_watcher.go:203] watcher event "/home/XXXX/filter_test/.goutputstream-U8HHG0": RENAME
I0228 10:43:23.795436    3239 tail.go:234] No file handle found for "/home/XXXX/filter_test/.goutputstream-U8HHG0", but is being watched
I0228 10:43:23.795454    3239 tail.go:321] "/home/XXXX/filter_test/.goutputstream-U8HHG0" did not match pattern "/home/XXXX/filter_test/data"
I0228 10:43:23.795466    3239 tail.go:341] did not start tailing "/home/XXXX/filter_test/.goutputstream-U8HHG0"
I0228 10:43:23.795478    3239 tail.go:244] Internal error finding file handle for "/home/XXXX/.goutputstream-U8HHG0" after create
I0228 10:43:23.795493    3239 log_watcher.go:203] watcher event "/home/zhoucong/XXXX/data": CREATE
I0228 10:43:23.795587    3239 file.go:153] EOF
I0228 10:43:23.799691    3239 log_watcher.go:203] watcher event "/home/XXXX/filter_test/data": CHMOD
I0228 10:43:23.800930    3239 log_watcher.go:203] watcher event "/home/XXXX/filter_test/data": REMOVE

**Comment by jaqx0r** [comment]
The lines that match '.goutputstream' are not interesting unless they're
the name of the file before being renamed to 'data', except the log doesn't
indicate that is the case.

The last three lines are the ones that are interesting, though.

Why is the log being removed?  What happens next?

Can you start mtail again, write the 10 lines, pause, then write the 11th
line?


Something I just noticed is that you don't have a version string in your
mtail version output, so did you build the project with the makefile?

**Comment by cleverchou** [comment]
Thanks for your help, I've done @ jaqx0r

**Comment by jaqx0r** [comment]
Oh! What was the problem?

**Comment by cleverchou** [comment]
1. Create new text date, write 10 lines, and close
2.mtail will get allline = 10
3. Reopen the text, add a new line, and close
4.mtail will get allline = 21
This process was operated manually , and  then using C language （3 functions : fopen、fprintf、fclose）, the result is correct.
