### ISSUE TITLE
Having a hard time parsing through a JSON line

### ISSUE THREAD

**Issue by pgporada** [google/mtail#301]
Hi,

I'm having a hell of a time trying to figure out how to parse the following log line. A particular application emits a log message with one of the fields containing json. I can get the first occurrence of the group to increment a counter, but after that mtail will stop processing the remainder of the line and proceed to the next log line. It's unclear how large the json blob will be each time it's emitted (most times the field is empty).

mtail version: `v3.0.0-rc34`

Example log:
```
20200319 app[6667]: someGarbageData data={"foobar":{"result":"error"},"foobaz":{"result":"warn"},"boobar":{"result":"error"}} moreGarbageData
```

Example program:
```
counter mycounter by field

def example {
  /^/ {
    next
  }
}

@example {
    /data={(.*)}}/ {
        /"result":"(?P<level>\w+)"/ {
            mycounter[$level]++
        }
    }
}
```

Output:
```
$ mtail --one_shot --progs mycounter.mtail --logs mycounter.log 
Metrics store:{
  "mycounter": [
    {
      "Name": "mycounter",
      "Program": "mycounter.mtail",
      "Kind": 1,
      "Type": 0,
      "Keys": [
        "field"
      ],
      "LabelValues": [
        {
          "Labels": [
            "error"
          ],
          "Value": {
            "Value": 1,
            "Time": 1584643505262202611
          }
        }
      ]
    }
  ]
}
```

What I expect to see is the following. Any guidance would be greatly appreciated.
```
$ mtail --one_shot --progs mycounter.mtail --logs mycounter.log 
Metrics store:{
  "mycounter": [
    {
      "Name": "mycounter",
      "Program": "mycounter.mtail",
      "Kind": 1,
      "Type": 0,
      "Keys": [
        "field"
      ],
      "LabelValues": [
        {
          "Labels": [
            "error"
          ],
          "Value": {
            "Value": 2,
            "Time": 1584643505262202611
          },
         {
          "Labels": [
            "warn"
          ],
          "Value": {
            "Value": 1,
            "Time": 1584643505262202611
          }
        }
      ]
    }
  ]
}
```

**Comment by jaqx0r** [comment]
Thanks for the question.

mtail does a single line match, so your json object isn't being parsed how
you want.  The patterns on line 10 and 11 match on the line and then the
action is executed once, and I'm pretty sure (but guessing) that it's
matched the first instance of "error" in your input line.

There's no way to get mtail to match more than once per line, and there's
not a way to get regular expressions to count repetitions in a match.

I can imagine a half-solution where you explicitly name the levels you want
to match on and count them, but it won't do what you want.

mtail was designed for unstructured text logs, not structured data objects,
sorry.

**Comment by pgporada** [comment]
Thank you @jaqx0r.

**Comment by jaqx0r** [comment]
Oh I remembered bug #291 tracks an issue related to this request.
