### ISSUE TITLE
Metric as constant value

### ISSUE THREAD

**Issue by dsever** [google/mtail#302]
Hi,

I'm using mtail "v3.0.0-rc34", so together with metrics parsed from logs I would like to announce version of ansible-role that configures mtail.

So is there any eay to do that, I tried by:
mtail_ansible_role_info[mtail_role_version] = 1

or even:
mtail_ansible_role_info = mtail_role_version 

But don't see anything as exported in prom,I  believe because value is not changing, so is there kind of workarround, to make it static?

Tnx

**Comment by jaqx0r** [comment]
I can't think why this wouldn't work.  Is this the entire program?  What's
the commandline you're using?

**Comment by dsever** [comment]
Hi this is my config...I briefly looked into the code and I see that static items, are defined separately 

`hidden gauge element
hidden gauge service
hidden gauge response_group

**hidden ansible_version
gauge mtail_ansible_role_version**

counter response_counter by verb, response_group, element, service
counter response_time_counter by verb, response_group, element, service
histogram response_time_histogram by verb, response_group, element, service buckets
{%- for bucket in histogram_buckets|sort  %}
 {{ bucket }}{% if not loop.last %},{% endif %}
{% endfor %}


const IPORHOST /(?P<clientip>(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|(\b(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][0-9A-Za-z-]{0,62}))*(\.?|\b))) /
const REMOTE_LOGNAME /(?P<remote_logname>[0-9A-Za-z-]+) /
...


{%  if read_element_service_from_file %}
getfilename() =~ /.*\/(?P<element>(.*-.*)|(.*))-(?P<service>.*)-access.log/  {
{% endif %}

/^/ +
IPORHOST +
REMOTE_LOGNAME +
REMOTE_USERNAME +
TIMESTAMP +
HTTPDETAILS +
REQUESTSTATUS +
RESPONSESIZE +
REFERER +
USERAGENT +
DURATION{

**ansible_version = "{{ mtail_ansible_version }}"**

{% if read_element_service_from_file %}

element = $element
service = $service

{% else %}

  element = "{{ element }}"
  service = "{{ service }}"

{% endif %}

  string($response)  =~ /2\d{2}/ {
  response_group = "2xx"
  }
....

  response_counter[$verb][response_group][element][service]++
  response_time_counter[$verb][response_group][element][service]+=$duration
  response_time_histogram[$verb][response_group][element][service] = $duration
  **mtail_ansible_role_version = ansible_version**
}

{%  if read_element_service_from_file %}
}
{% endif %}`

**Comment by jaqx0r** [comment]
Could you please process the config template and show me the generated
config?

**Comment by dsever** [comment]
Complete generated config:

`hidden gauge element
hidden gauge service
hidden gauge response_group

gauge mtail_role_version

counter response_counter by verb, response_group, element, service
counter response_time_counter by verb, response_group, element, service
histogram response_time_histogram by verb, response_group, element, service buckets 100, 1000, 10000, 100000

const IPORHOST /(?P<clientip>(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|(\b(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][0-9A-Za-z-]{0,62}))*(\.?|\b))) /
const REMOTE_LOGNAME /(?P<remote_logname>[0-9A-Za-z-]+) /
const REMOTE_USERNAME /(?P<remote_logusername>[0-9A-Za-z-]+) /
const TIMESTAMP /\[(?P<timestamp>\d{2}\/\w{3}\/\d{4}:\d{2}:\d{2}:\d{2} (\+|-)\d{4})\] /
const HTTPDETAILS /"(?P<verb>[A-Z]+) (?P<URI>\S+) (?P<http_version>HTTP\/[0-9\.]+)" /
const REQUESTSTATUS /(?P<response>\d{3}) /
const RESPONSESIZE /((?P<response_size>\d+)|-) /
const REFERER /"(?P<referer>\S+)" /
const USERAGENT /"(?P<user_agent>[[:print:]]+)" /
const DURATION /(?P<duration>\d+)$/



/^/ +
IPORHOST +
REMOTE_LOGNAME +
REMOTE_USERNAME +
TIMESTAMP +
HTTPDETAILS +
REQUESTSTATUS +
RESPONSESIZE +
REFERER +
USERAGENT +
DURATION{


  element = "api-proxy"
  service = "keystone"


  string($response)  =~ /2\d{2}/ {
  response_group = "2xx"
  }

  string($response)  =~ /3\d{2}/ {
  response_group = "3xx"
  }

  string($response)  =~ /4\d{2}/ {
  response_group = "4xx"
  }

  string($response)  =~ /5\d{2}/ {
  response_group = "5xx"
  }

  response_counter[$verb][response_group][element][service]++
  response_time_counter[$verb][response_group][element][service]+=$duration
  response_time_histogram[$verb][response_group][element][service] = $duration
  mtail_role_version = "v0.1-rc4"
}
`

**Comment by dsever** [comment]
@jaqx0r any idea is it possible to do?

Tnx

**Comment by dsever** [comment]
I resolved my problem, so value can't be anything else than number. So I transferred my version by using labels
