### ISSUE TITLE
Fetching metrics from JSON logs

### ISSUE THREAD

**Issue by accts324** [google/mtail#303]
Hi Team,

i am facing an issue while fetching metrics from logs that are in JSON format. Sample logs are shown below . Can you help me with getting the metrics for all the key values.

Sample logs

{ "sys": "esp", "creation_timestamp": "2020-03-27T07:27:49", "msg": "Success", "log_type": "INFO", "format_ver": "1.1", "id": { "global": "erfefwfefffelgrgrlvlsvll", "caller": "", "local": "jwrfwdkfhkqkdwqkldkewfhjw"},"app": { "name": "insurance_life_esp", "service": "", "resp_time_ms": "1", "protocol": "GET", "method": ""},"caller": { "authid": "", "ip": "192.168.0.1"},"local": { "ip": "192.168.0.1"},"custom_fields": { "companyid": "", "wsdlver": "0", "agent": null, "port": "9100", "activereqs": "1", "internal": "0", "activeS": "0", "comp": "1", "contLen": "-1", "conttype": "", "httpmethod": "GET", "rcvdReq": "0", "sslProtocol": "none"}}

**Comment by jaqx0r** [comment]
You have to specify every key name explicitly at the moment.

If you want dynamically parsed keys, then you need to follow bug #291 .

**Comment by accts324** [comment]
Hi Jaqx0r,

i have prepared the below pattern which works well for LOG1 but does not work for LOG2. The only difference between both the logs is extra spaces in LOG1 format.

A quick help here would be appreciated.

**Pattern**

counter mycounter1 by field
counter mycounter2 by field
counter mycounter3 by field
counter mycounter4 by field
counter mycounter5 by field
def example {
  /^/ {
    next
  }
}

 

@example {
/"sys": "(?P<level1>\w+)"/ {
mycounter1[$level1]++
}

 

/"msg": "(?P<level2>\w+)"/ {
mycounter2[$level2]++
}

 


/"app": / {

 

    /"name": "(?P<level3>\w+)"/ {
            mycounter3[$level3]++
       }

 

    /"resp_time_ms": "(?P<level4>\w+)"/ {
            mycounter4[$level4]++
       }

 

    /"protocol": "(?P<level5>\w+)"/ {
            mycounter5[$level5]++
       }

 


    }
 
}

**LOG1**
{ "sys": "esp", "creation_timestamp": "2020-03-31T16:19:22", "msg": "Success", "log_type": "INFO", "format_ver": "1.1", "id": { "global": "EyhTt8i3WsSV32bktjC7va", "caller": "", "local": "EyhTt8h8gAb15iupsTx1Rf"},"app": { "name": "insurance_life_esp", "service": "", "resp_time_ms": "0", "protocol": "GET", "method": ""},"caller": { "authid": "", "ip": "192.168.0.1"},"local": { "ip": "192.168.0.1"},"custom_fields": { "companyid": "", "wsdlver": "0", "agent": null, "port": "7270", "activereqs": "1", "internal": "0", "activeS": "0", "comp": "0", "contLen": "-1", "conttype": "", "httpmethod": "GET", "rcvdReq": "0", "sslProtocol": "none"}}


**LOG2**

{"sys":"mvr","msg":"MVROrderReceived","log_type":"INFO","format_ver":"1.1","id":{"global":"EehSkouB9HSDuk3LAhiAbZ","caller":null,"local":"EehSkou2EeEnetp8DCJD77","ref":"11W20191120141703066"},"app":{"name":"MVR-Workflow","service":"mvr-workflow","resp_time_ms":"0.40","status":"NOT","status_code":"N","method":"Request","protocol":"non-TSS"},"caller":{"authid":"","ip":null,"hostname":null},"local":{"ip":"192.168.0.1","hostname":"192.168.0.1"},"custom_fields":{"c":"NV"},"creation_timestamp":"2019-11-20T14:17:03"}
