### ISSUE TITLE
Providing a flag to hide log lines from the web interface

### ISSUE THREAD

**Issue by quatre** [google/mtail#305]
Hello!

currently, mtail can expose log lines through the web interface (for example through the /progz endpoint) when they cause a program to fail (eg. by trying to compare a string with an int).

What is your opinion on having a command line flag that would prevent these log lines to be exposed through the web interface?

**Comment by jaqx0r** [comment]
Why do you want to turn that feature off?

**Comment by quatre** [comment]
In some cases, logs may contain sensitive information (think for example, a username, or an IP address) that would be better not to expose.

When things are working nicely, this shouldn't be a problem. But if the application log format changes  and breaks the mtail program, it could become an information leak.

**Comment by jaqx0r** [comment]
Yep that makes sense. Do you not firewall the mtail port though?

**Comment by quatre** [comment]
We sure would firewall it :p!
But the people who have shell access to Prometheus (to edit its config for example) do not necessarily have access to sensitive logs.

**Comment by jaqx0r** [comment]
That's a good reason!

**Comment by robert-heinzmann-logmein** [comment]
I reopened the original PR with a new branch. I also added an option to disable the /varz and /progz endpoints, as those could also leak some information that is not intended for public access as typically needed with prometheus.
