### ISSUE TITLE
getting average value OR division operator issue

### ISSUE THREAD

**Issue by accts324** [google/mtail#309]
Hi,

I am using the below pattern to get the average response time from my logs. Need some help here to figure out what is wrong here.

**Pattern**

counter requests_total by protocol
gause total_response_time by protocol
timer avg_response_time_ms by protocol
/\.*("resp_time_ms": "(?P<resp_time_ms>\w+)").*("protocol": "(?P<protocol>\w+)")/ {
  requests_total[$protocol]++
  total_response_time[$protocol] += $resp_time_ms
  avg_response_time_ms[$protocol] = $total_response_time[$protocol] / $requests_total[$protocol]
 }

**ERROR LOGS**

I0406 12:16:05.915582   21009 log_watcher.go:249] No abspath in watched list, added new one for /root/go/bin/json.mtail
I0406 12:16:05.915772   21009 loader.go:123] Compile errors for json.mtail:
compile failed for json.mtail:
json.mtail:15:57: syntax error: unexpected LSQUARE, expecting NL

**Comment by jaqx0r** [comment]
On line 15 at position 57 there's a [ where it was expecting the end of the line.

That's weird, because this program only appears to have 8 lines.

`gauge` is misspelled on line 2.

Can you share the actual program source for `json.mtail` please?
