### ISSUE TITLE
Please switch to using native go-fuzz for OSS-Fuzz (2 line change)

### ISSUE THREAD

**Issue by inferno-chromium** [google/mtail#311]
Please see https://github.com/google/oss-fuzz/pull/3638 as example.

**Comment by jaqx0r** [comment]
I'm trying to understand why from the linked issue and PR.  What's the advantage?

**Comment by inferno-chromium** [comment]
@jaqx0r - go114-fuzz-build uses official go compiler libfuzzer instrumentation, and now all OSS-Fuzz go projects are migrated to use it. Read more here - https://github.com/mdempsky/go114-fuzz-build#intro. Basically Go 1.14 support libFuzzer instrumentation natively and is nearly ~20% faster than https://github.com/dvyukov/go-fuzz. Native part is more important since we want to use what official go compiler provides.

**Comment by jaqx0r** [comment]
Thanks for the link.  I guess I'm confused by the word "native"; we keep
using clang and libfuzzer, but the replacement
(mdempsky's go114-fuzz-build) uses Go 1.14 internals "natively" instead --
I interpreted it to mean "we now use go-fuzz instead of clang" and couldn't
make sense of the PR.
