### ISSUE TITLE
Unexpected CPU utilization increase in polling watcher

### ISSUE THREAD

**Issue by shdubsh** [google/mtail#322]
**Mtail Version**: v3.0.0~rc35

**Current Behavior**:
Mtail watches all files in the configured parent directory for changes.

With `-disable_fsnotify` (https://github.com/google/mtail/issues/195) and `-logs` configured to watch a single file (no globbing) in a directory with other files, Mtail runs os.Stat on many files rather than just the one we're interested in.  This is unnecessary overhead that results in a noticeable increase of syscall and CPU utilization when there are many files in the parent directory and the default poll time.

**Expected behavior**:
Mtail should only stat the configured files and ignore the rest when having to poll for modtime.

**Logs**:
[Attached](https://github.com/google/mtail/files/4806032/bug_report.log)

**Demo script**:
```bash
#!/bin/bash

TEST_DIR=/tmp/mtail_testing

mkdir $TEST_DIR
cd $TEST_DIR

wget https://github.com/google/mtail/releases/download/v3.0.0-rc35/mtail_v3.0.0-rc35_linux_amd64
chmod +x mtail_v3.0.0-rc35_linux_amd64

mkdir conf
mkdir logdir
touch logdir/my.log
for IDX in {1..300}; do touch "logdir/my.log.${IDX}"; done

./mtail_v3.0.0-rc35_linux_amd64 -v 2 -logtostderr -progs "$(pwd)/conf" -disable_fsnotify -logs "$(pwd)/logdir/my.log"
```

**Comment by jaqx0r** [comment]
Thanks for the detailed report!

**Comment by hashar** [comment]
From a comment I made to our bug tracker https://phabricator.wikimedia.org/T255776

By raising the log verbosity with `-v=2` the `stat()` calls are shown in the log. I gave it a try with mtail 3.0.0~rc35-3+wmf1 shipped in `docker-registry.wikimedia.org/releng/operations-puppet`. Once in the container:
```
mkdir -p /var/log/logstash
touch /var/log/logstash/{main,1,2,3,4,5}.log
mtail -logtostderr -logs /var/log/logstash/main.log -disable_fsnotify -progs /etc/mtail -v=2
```

It polls every 250ms:
```
I0620 13:31:00.633711     103 main.go:102] mtail version 3.0.0~rc35 git revision 3.0.0~rc35-3+wmf1 go version go1.11.6 go arch amd64 go os linux
I0620 13:31:00.633926     103 log_watcher.go:57] fsnotify disabled and no poll interval specified; defaulting to 250ms poll
```

Watches `main.log` as passed with `-logs`:
```
I0620 13:31:00.636499     103 mtail.go:99] Tail pattern "/var/log/logstash/main.log"
I0620 13:31:00.636546     103 tail.go:134] AddPattern: /var/log/logstash/main.log
```

Watch the parent directory as well bah:
```
I0620 13:31:00.636592     103 log_watcher.go:269] Adding a watch on resolved path "/var/log/logstash"
I0620 13:31:00.636630     103 log_watcher.go:249] No abspath in watched list, added new one for /var/log/logstash
```

And then it starts watching any files in the directory:
```
I0620 13:31:00.885297     103 log_watcher.go:143] Update fi
I0620 13:31:00.885328     103 log_watcher.go:128] Stat "/var/log/logstash"
I0620 13:31:00.885836     103 log_watcher.go:170] sending create for /var/log/logstash/1.log
I0620 13:31:00.885898     103 tail.go:234] No file handle found for "/var/log/logstash/1.log", but is being watched
I0620 13:31:00.885936     103 tail.go:321] "/var/log/logstash/1.log" did not match pattern "/var/log/logstash/main.log"
I0620 13:31:00.885963     103 tail.go:341] did not start tailing "/var/log/logstash/1.log"
I0620 13:31:00.885991     103 tail.go:244] Internal error finding file handle for "/var/log/logstash/1.log" after create
```

So it looks like it watch the holding directory in case `-logs` is a pattern and has to match a file in there (eg one could use: `-logs /var/log/logstash/*.log`, so it gotta look at the list of files in the directory?).

**Comment by jaqx0r** [comment]
You're right, the log_watcher has to poll every file in the directory to find out if it's interesting.  There's a bug though - now it's watching every new file in the watched directory, but it should not do that , it should wait for the tailer to say it's OK to watch.
