### ISSUE TITLE
mtail can't track logs with LF line endings on Windows

### ISSUE THREAD

**Issue by safebear** [google/mtail#324]
# Problem

I've set up mtail to track two logs, foo.log and bar.log.

`foo.log` and `bar.log`.

mtail can track `foo.log` fine, but with `bar.log` it doesn't register when new lines are added. 

There are no errors in `mtail.INFO`. When I run the mtail command with the `--one_shot` option, it parses the 'gold standard' file for `bar.log` and outputs the correct results. When I stop the `bar` service, then suddenly mtail starts reporting on the logs! When I start the `bar` service again, then mtail stops.

I've tried tracking the `bar.log` on it's own with no joy.

I've also tried running `mtail` as admin and disabling `fsnotify`, but with no luck. There are no errors anywhere, so I'm not sure how to debug this problem...

I'm running on `Windows Server 2016 Datacenter`

## Command
mtail --logtostderr  --progs .\monitor.mtail --logs C:\bar.log --logs C:\foo.log

## Program

```
# Number of Errors
counter log_errors by log_name, error_message


# Foo Logs
/^/ +
/(?P<date>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3} \+\d{2}:\d{2})/ +
/,/ {
    /Error,.+?"(?P<error_message>[\w|\s]+)"/ {
        log_errors[getfilename()][$error_message]++
    }
}


# Bar Logs
/^/ +
/(?P<date>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z)/ +
/ \[\] / {
    /error: (?P<error_message>.+((Error)|(\r)))/ {
        log_errors[getfilename()][$error_message]++
    }
}

```

## Output of mtail --version

mtail version v3.0.0-rc35 git revision a33283598c4b7a70fc2f113680318f29d5826cca go version go1.14 go arch amd64 go os windows

## mtail.Info Log
```
I0625 12:37:30.514942    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\Users\admin\Documents\mtail\.mtail
I0625 12:37:30.515917    4696 checker.go:217] declaration of capture group reference `date' at monitor.mtail:16:3 appears to be unused
I0625 12:37:30.515917    4696 checker.go:217] declaration of capture group reference `date' at monitor.mtail:16:3 appears to be unused
I0625 12:37:30.515917    4696 checker.go:217] declaration of capture group reference `2' at monitor.mtail:29:5-48 appears to be unused
I0625 12:37:30.515917    4696 checker.go:217] declaration of capture group reference `3' at monitor.mtail:29:5-48 appears to be unused
I0625 12:37:30.515917    4696 checker.go:217] declaration of capture group reference `4' at monitor.mtail:29:5-48 appears to be unused
I0625 12:37:30.515917    4696 checker.go:217] declaration of capture group reference `date' at monitor.mtail:26:3 appears to be unused
I0625 12:37:30.516894    4696 checker.go:217] declaration of capture group reference `date' at monitor.mtail:26:3 appears to be unused
I0625 12:37:30.516894    4696 loader.go:229] Loaded program monitor.mtail
I0625 12:37:30.516894    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\
I0625 12:37:30.516894    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\bar.log
I0625 12:37:30.517872    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.517872    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.517872    4696 tail.go:302] Tailing C:\bar.log
I0625 12:37:30.517872    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\
I0625 12:37:30.518848    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\foo.log
I0625 12:37:30.518848    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.518848    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.518848    4696 tail.go:302] Tailing C:\foo.log
I0625 12:37:30.518848    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\foo.log
I0625 12:37:30.519819    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.519819    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.519819    4696 tail.go:302] Tailing C:\foo.log
I0625 12:37:30.519819    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\foo.log
I0625 12:37:30.519819    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.520802    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.520802    4696 tail.go:302] Tailing C:\foo.log
I0625 12:37:30.520802    4696 log_watcher.go:249] No abspath in watched list, added new one for C:\foo.log
I0625 12:37:30.520802    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.521776    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.522753    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.530566    4696 log_watcher.go:254] Found this processor in watched list
I0625 12:37:30.530566    4696 tail.go:302] Tailing C:\foo.log
I0625 12:37:30.530566    4696 tail.go:302] Tailing C:\foo.log
I0625 12:37:30.530566    4696 tail.go:448] Starting log handle expiry loop every 1h0m0s
I0625 12:37:30.530566    4696 mtail.go:321] Listening on [::]:3903
I0625 12:37:30.531535    4696 store.go:136] Starting metric store expiry loop every 1h0m0s
```

In the metrics exposed, `foo` appears, but not `bar` even though lines are being added to the file:

`mtail_log_lines_total{logfile="C:\\foo.log"} 292197`

However when I stop the `bar` service, then suddenly the `bar.log` metrics appear!

`mtail_log_lines_total{logfile="C:\\bar.log"} 105`

**Comment by safebear** [comment]
Ok, so it doesn't look like it's anything to do with line endings. Instead, I found that as soon as I stopped the service that was logging to `bar.log`, then mtail picked up the log and started reporting metrics on it. As soon as I started the service again, it stopped reporting. Is there a known issue where mtail on Windows can't tail a log if it's being actively updated?

**Comment by safebear** [comment]
I have tried running mtail as the admin user and it makes no difference.

**Comment by safebear** [comment]
Disabling `fsnotify` didn't work either. There must be something I can try to figure out why mtail can only read the logs when the service is stopped...

**Comment by jaqx0r** [comment]
I have no experience with Windows let alone running mtail there so I'm
afraid I don't have any idea. My suspicion though is that the trailer is
built with POSIX assumptions and needs someone who understands Windows IO
to help.

**Comment by jaqx0r** [comment]
I guess the short answer is yeah, we only look for \n newlines when we send a line to be processed.

Can you be certain that the log file only uses line feed characters for line termination?
