### ISSUE TITLE
brew install mtail

### ISSUE THREAD

**Issue by ankane** [google/mtail#329]
Hi, thanks for this neat library! I'm hoping to add mtail to Homebrew so Mac users can install it with:

```sh
brew install mtail
```

I've created [a formula here](https://github.com/ankane/homebrew-core/blob/mtail/Formula/mtail.rb), but it requires a non-rc release to be accepted. It looks like rc0 was released in June 2017 and there have been 36 rcs since then. Any update on the current release plans for 3.0?

**Comment by jnovack** [comment]
Discussion on 3.0 is here #248

**Comment by jaqx0r** [comment]
When I'm happy with the stability and features it'll stop being a release
candidate, but numbers are just numbers so if homebrew want a non RC
version number then I'll see what I can do before Xmas.

**Comment by jaqx0r** [comment]
FYI this is still some time away, because there are good bugs that keep showing up.  I'm sorry that homebrew won't take a prerelease candidate but I don't want to burn the 3.0 tag on a version I don't think is worthy.

**Comment by ankane** [comment]
Hey, thanks for the responses, and no worries if it's not ready. Will close this and revisit when 3.0 is out.
