### ISSUE TITLE
rc36 doesn't handle negative numbers in capture groups.

### ISSUE THREAD

**Issue by SuperQ** [google/mtail#332]
When handling values that may have a negative number, and also doing math on them (converting milliseconds to seconds for example), upgrading from rc35 to rc36 results in a compile error.

```
gauge foo
/(?P<value_ms>-?\d+)/ {
  foo += $value_ms / 1000.0
}
```

```
$ mtail -one_shot -logtostderr -progs progs -logs test.log
I0813 14:11:04.901253  537158 main.go:103] mtail version v3.0.0-rc36 git revision 7825f115dd3ed9f623377821c0351d1eb7aa3a5a go version go1.14.4 go arch amd64 go os linux
I0813 14:11:04.901310  537158 main.go:104] Commandline: ["mtail" "-one_shot" "-logtostderr" "-progs" "progs" "-logs" "test.log"]
I0813 14:11:04.902026  537158 log_watcher.go:249] No abspath in watched list, added new one for /home/ben/prometheus/mtail/test/progs
E0813 14:11:04.902387  537158 main.go:177] Compile encountered errors:
compile failed for test.mtail:
test.mtail:3:10-27: Internal compiler error, aborting compilation: no opcode for type String in op 57376
```

**Comment by jaqx0r** [comment]
OK this looks simple, just add this test case to the capref inference code.  I see that I missed this, should be easy...

except, for some reason, the alternation here now breaks, and it looks like it's because the standard library doesn't notice the alternation??

https://play.golang.org/p/Qmm2H_k7cEd

**Comment by jaqx0r** [comment]
OK makes sense now; the alternation is compressed into the character class match.  I understand now why the test is broken.
