### ISSUE TITLE
Install and start Mtail in Red HAt Linux

### ISSUE THREAD

**Issue by arunraja2306** [google/mtail#334]
Please guide me to install the Mtail in Red HAt Linux and start command.

I have downloaded the Mtail file from git hub for Linux server "mtail_v3.0.0-rc36_linux_ppc64 " and when I try to start it throws error as below . Please guide me.

$ mtail_v3.0.0-rc36_linux_ppc64 --progs /home/pshrms/softwares --logs "/home/pshrms/logs/*"
-bash: mtail_v3.0.0-rc36_linux_ppc64: command not found

Thanks!

**Comment by arunraja2306** [comment]
still issue not fixed please help

**Comment by jaqx0r** [comment]
Are you using a PowerPC cpu? You're on red hat: type uname -a on a terminal
and tell me which machine type you're using.

 I assume you want the x86-64 version instead.

**Comment by arunraja2306** [comment]
You are right I required that version compatibility. Please help. Below is the uname -a result.

Linux 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue May 26 15:05:43 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jaqx0r** [comment]
Ok please download the mtail binary that has x86-64 in the name.

**Comment by arunraja2306** [comment]
Thanks a lot
