### ISSUE TITLE
Log file is not read by mTail

### ISSUE THREAD

**Issue by arunraja2306** [google/mtail#335]
Hi All,

I am trying to read the log file from the below path , in that path we will have only one log file which will rotate one hour once  like below. mtail not reads the existing file and also it not recognise new files also.

$ cd logs
$ ls -lrt
-rw-r--r-- 1 1086 Sep 30 13:03 nakisa_push_20200930130302.log
$

Log files will be replaced like below .
-rw-r--r-- 1 1086 Sep 30 10:03 nakisa_push_20200930100302.log
-rw-r--r-- 1 1086 Sep 30 11:03 nakisa_push_20200930110302.log
-rw-r--r-- 1 1086 Sep 30 12:03 nakisa_push_20200930120302.log

But mtail not reading the file itself. I am getting below error log.

Log:-

Log file created at: 2020/09/30 12:40:40
Running on machine: 
Binary: Built with gc go1.14.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0930 12:40:40.309423   80195 main.go:103] mtail version v3.0.0-rc36 git revision 7825f115dd3ed9f623377821c0351d1eb7aa3a5a go version go1.14.4 go arch amd64
go os linux
I0930 12:40:40.309651   80195 main.go:104] Commandline: ["mtail" "--progs" "/home/inframon/mtail" "--logs" "/prd/psft/gbl/interface/NAKISA/logs/nakisa_push_2
0200930120302.log" "--logs" "/home/inframon/mtail/test.log" "--emit_metric_timestamp"]
I0930 12:40:40.313592   80195 log_watcher.go:249] No abspath in watched list, added new one for /home/inframon/mtail
I0930 12:40:40.313974   80195 loader.go:229] Loaded program nakisa_delete.mtail
I0930 12:40:40.314108   80195 loader.go:229] Loaded program nakisa_update.mtail
I0930 12:40:40.314247   80195 loader.go:229] Loaded program test.mtail
I0930 12:40:40.314289   80195 log_watcher.go:249] No abspath in watched list, added new one for /prd/psft/gbl/interface/NAKISA/logs
I0930 12:40:40.314310   80195 log_watcher.go:249] No abspath in watched list, added new one for /prd/psft/gbl/interface/NAKISA/logs/nakisa_push_2020093012030
2.log
I0930 12:40:40.314318   80195 log_watcher.go:254] Found this processor in watched list
I0930 12:40:40.314355   80195 log_watcher.go:254] Found this processor in watched list
I0930 12:40:40.314386   80195 tail.go:315] Tailing /prd/psft/gbl/interface/NAKISA/logs/nakisa_push_20200930120302.log
I0930 12:40:40.314397   80195 log_watcher.go:259] appended this processor
I0930 12:40:40.314413   80195 log_watcher.go:249] No abspath in watched list, added new one for /home/inframon/mtail/test.log
I0930 12:40:40.314420   80195 log_watcher.go:254] Found this processor in watched list
I0930 12:40:40.314444   80195 log_watcher.go:254] Found this processor in watched list
I0930 12:40:40.314447   80195 tail.go:315] Tailing /home/inframon/mtail/test.log
I0930 12:40:40.314639   80195 store.go:136] Starting metric store expiry loop every 1h0m0s
I0930 12:40:40.314647   80195 mtail.go:341] Listening on 0.0.0.0:3903
I0930 12:40:40.314656   80195 tail.go:461] Starting log handle expiry loop every 1h0m0s
I0930 13:03:02.710075   80195 file.go:129] Stat failed on "/prd/psft/gbl/interface/NAKISA/logs/nakisa_push_20200930120302.log": stat /prd/psft/gbl/interface/
NAKISA/logs/nakisa_push_20200930120302.log: no such file or directory
I0930 13:03:02.710124   80195 file.go:129] Stat failed on "/prd/psft/gbl/interface/NAKISA/logs/nakisa_push_20200930120302.log": stat /prd/psft/gbl/interface/
NAKISA/logs/nakisa_push_20200930120302.log: no such file or directory

In mtail below is appears :-  

   #TYPE nakisa_update counter
nakisa_update{prog="nakisa_update.mtail"} 0 0

nakisa.mtail file contains :-   

counter nakisa_update
getfilename() =~ /nakisa_push_/ {
/check 1/ {
 nakisa_update=1
}
/check 2/ {
nakisa_update=2
}
}

mtail start command  :-  mtail --progs /home/inframon/mtail --logs /prd/psft/gbl/interface/NAKISA/logs/*.log   --emit_metric_timestamp

**Comment by jaqx0r** [comment]
My guess is you passed *.log to the logs flag but didn't escape it from the
shell. Near the top of the log you posted you see it prints out the command
line you entered, and it doesn't have a glob in it.
