### ISSUE TITLE
No support for UNIX Socket

### ISSUE THREAD

**Issue by ArcticB** [google/mtail#336]
Hello!

I'm currently using Mtail as an exporter in a Prometheus environment and I need the endpoints to be accessible only though AF_UNIX to ensure security server side with permissions on the socket file. I did a [PR](https://github.com/google/mtail/pull/327) with the code I propose for this and I've been testing it for 2 month now, it's working great. Please consider my demand and add it to the release version in order to make it usable in the packaged versions.  

Thanks a lot!

**Comment by jaqx0r** [comment]
Hi! I'm on vacation so haven't had a chance to read the pr, sorry. If you
haven't yet, please make sure there's an end to end regression test in
internal/mtail, copy the basic tail test for an example.

I'm genuinely curious about your system design so could you write more
about it? Eg why you can't use http for Prometheus, and write some doc's in
the deployment markdown page to help others learn if they want to use it.

Thanks!

**Comment by jaqx0r** [comment]
Discussion is happening on #327
