### ISSUE TITLE
OpenCensus overhead in ProcessLogLine

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [google/mtail#337]
Hi,

We're using mtail extensively at @gitlab and were recently having issues with mtail not keeping up with the log volume. During a recent case, I took a CPU profile with perf record.

Here is the flamegraph from that profile:

<img width="1182" alt="Screenshot 2020-10-07 at 14 07 09" src="https://user-images.githubusercontent.com/11158255/95328874-68c0ef00-08a6-11eb-963b-d96fbcfbc8b3.png">

[flamegraph.svg.gz](https://github.com/google/mtail/files/5340397/flamegraph.svg.gz)

What you can see is that most time is spent in OpenCensus.

* 50% is spent in `go.opencensus.io/trace.StartSpan`, `go.opencensus.io/trace.(*Span).End`, and `go.opencensus.io/trace.(*Span).AddAttributes`, a lot of which is in allocations.
* 16% is spent in gc
* only ~10% is spent in VM execute

This suggests that the overhead of producing a span for each line carries too much overhead. Especially if those spans aren't actually being reported anywhere.

I would suggest removing the OpenCensus span from `ProcessLogLine` or finding a way of turning it into a noop when not in use.

**Comment by jaqx0r** [comment]
Wow, that's impressive! Thanks for the investigation!

I'll remove it for now until it is needed.
