### ISSUE TITLE
extract metrics from log file metadata (e.g. getfilename())

### ISSUE THREAD

**Issue by jaqx0r** [google/mtail#36]
https://groups.google.com/d/topic/mtail-users/7h1AVuY4YCE/discussion

The request is to annotate the exported metrics with some labels at a larger scope than just the log line.

The log filename could contain metadata about the log line, i.e. the hostname it arrived from, perhaps.  This also raises the question, should you be able to add labels at higher levels too: the whole program, and mtail itself?

(The short answer to the latter, I think, is no: if you want to export a whole program label, you can do that already with constant values; if you want to apply a label globally, you can do that with the collecting system, e.g. with Prometheus, use the labels syntax to annotate with static labels, or use relabel_config: https://prometheus.io/docs/operating/configuration/#<relabel_config>)

The mtail program currently does not get to see the metadata of the log, such as its filename.  The language assumes that a match is done solely against the log line.

This bug should figure out how to modify the language to pass the log filename to the program so that it can be matched upon, as well.  If we discover other log metadata that should be available to the program, let's add it here too.

**Comment by josetaira** [comment]
@jaqx0r this might be exactly what I was looking for in https://groups.google.com/forum/#!topic/mtail-users/gZBr4Pajiz4

I was also looking for how to add the present working directory so that it can be matched as well. I thought the log_rewriter.awk was being used for this, but apparently not.

**Comment by jaqx0r** [comment]
The next step here is to have some syntax that allows any string to be matched against.   Currently the // action only works on the log line input.

**Comment by jaqx0r** [comment]
The last comment here asks that we support doing matches against any input.  We do this now, so I think this is resolved.
