### ISSUE TITLE
Overload of CPU during reading huge log 4k inputs in second

### ISSUE THREAD

**Issue by GenJob** [google/mtail#360]
Hi, 
I getting overload of MTAIL on my srever.. reading around 250k lines per minute an tooks around 30% CPU. I was thinking to cut some funcions (please mention the change) like varz or json... or if you have any idea how to handle this. I would like to have it a really low running app. (of course in some fine funcional way)
unfortunately its not running on docker..... :( and using mtail_v3.0.0-rc38_linux_amd64 release. thank you for help I not soo good reader go code then pleaes apologize me ;)

![image](https://user-images.githubusercontent.com/73934430/101155026-e2672600-3626-11eb-8032-83e515ad4d58.png)

There I add the pic how it looks like. Number of lines during day is around 12 442 073. What you think about this. I am also thinking about parser which maybe can cause the huge load... but just thinking... 
almost forgot  version:
 _go version go1.13.8 linux/amd64_
_mtail version v3.0.0-rc38_

Thank you for help @jaqx0r 
I am listening.... :+1:

**Comment by GenJob** [comment]
![image](https://user-images.githubusercontent.com/73934430/101150899-29521d00-3621-11eb-945a-c0ea1c2e2816.png)

There I add the pic how it looks like. Number of lines during day is around 12 442 073. What you think about this. I am also thinking about parser which maybe can cause the huge load... but just thinking... 
Thank you for help @jaqx0r

**Comment by jaqx0r** [comment]
First thing I'll guess at is you should turn off fsnotify with the -disable_fsnotify flag and ensure -poll_interval is set reasonably.  I don't think varz or json would contribute at all to the load.    

I also want it to be low resource consumption so thankyou for the report!

Next things to try out are listed in the Troubleshooting guide at https://google.github.io/mtail/Troubleshooting.html#memory-or-performance-issues

Please try to capture a CPU profile for 30s and attach it to this issue!

**Comment by GenJob** [comment]
Hi, I used perf for that with local test and writing to the file. But What I am seeing is that there is not so big difference between these two options. The problem is maybe the amount of lines written to the log on our server. I just consuming really a lot... I tested 1000 inputs every 0.05s, took around 40s to finish and after I stop the test. there are screen shots but it seems to be almost same. I will try to test it more in some free time but now I dont see a benefit to disable fsnotify. What do you think? 
with fsnotify 
![fsnotify](https://user-images.githubusercontent.com/73934430/101492975-b967cd80-3965-11eb-86d1-c9d74bb61f86.png)

without pool set default 250ms
![disabled_fsnotify](https://user-images.githubusercontent.com/73934430/101492989-bc62be00-3965-11eb-996e-441f8b9a5666.png)

In option where I used 10 000 inputs the fsnotify just fail instantly... btw why are you not using inotify?
