### ISSUE TITLE
Please, expand the language docs

### ISSUE THREAD

**Issue by TheTincho** [google/mtail#38]
While reading the sample programs, I noticed that there were features not described in the wiki, most notably, decorators and function calling.

Decorators seem self-evident (except for the "next" action), but I have no clue which functions are available, or even what actions are allowed. I wonder -for example- if I can overwrite a match group, or use metrics in conditionals.

Thanks!

**Comment by jaqx0r** [comment]
Yep, no worries. The docs are too sparse.

**Comment by jaqx0r** [comment]
https://github.com/google/mtail/wiki/Language#builtin-functions and the next section on decorated actions now exists.
