### ISSUE TITLE
I want to make a program that counts a specific character string in the log read by mtail.

### ISSUE THREAD

**Issue by vdi-kakui** [google/mtail#385]
The program I made to create a program that counts a specific character string in the log read by mtail is as follows.

```
counter counter_a

/a/ {
counter_a++
}
```

But this does not start.
Does mtail have a string search function like grep?

**Comment by jaqx0r** [comment]
This program is straight out of the README, so it should work.  Can you provide how you're starting mtail?  The debugging information is all listed in the new bug template and in https://google.github.io/mtail/Troubleshooting.html#reporting-a-problem

**Comment by vdi-kakui** [comment]
thanks
