### ISSUE TITLE
I want to monitor multiple LOG files whose filenames change with mtail.

### ISSUE THREAD

**Issue by vdi-kakui** [google/mtail#392]
I want to monitor multiple LOG files whose filenames change with mtail.

The rules for multiple log files
/var/log/deploy-1qa2ws3ed.log
/var/log/deploy-3ed2ws1qa.log

It is possible to monitor log files with two file name patterns at the same time.
But trying to monitor these two logs,

/var/log/deploy-*.log

If you specify the log file path, the following error will occur.
How can I monitor the logs for two variable filenames?

```
Too many extra arguments specified:
(the logs flag can be repeated, or the filenames separated by commas.)
```

**Comment by jaqx0r** [comment]
Put the argument in single quotes so the shell doesn't expand the glob
before mtail gets a chance.

**Comment by vdi-kakui** [comment]
Thank you for pointing out the exact mistake.
