### ISSUE TITLE
Pre-defined label for prometheus

### ISSUE THREAD

**Issue by chocopowwwa** [google/mtail#40]
I posted an issue on prometheus https://github.com/prometheus/prometheus/issues/1853 , i got a problem with the counter metrics that doesnt count from 0, 

well, if i write mtail progs it would a long progs and the progs wouldn't be dynamic, any solution for this?

Thank You, :cupid:

**Comment by jaqx0r** [comment]
The problem is that the label sets being published don't exist until the log line is seen, unless you have all the labels at the start of the program, we can't export a zero counter.

But the first value you saw *is* 15 so I think both mtail and Prometheusare doing the correct thing here.

**Comment by jaqx0r** [comment]
Your irate function should only give you a nonzero answer when the value of he counter changes. If it says 15, then the rate is 0. I think this is working as intended.  If you have more requests is the counter not incrementing?
