### ISSUE TITLE
language: Unable to parse timestamp with underscore

### ISSUE THREAD

**Issue by lapawa** [google/mtail#424]
I'm using mtail to parse event logs from this home automation application (http://fhem.de) to feed prometheus with measured values.
The format of the timestamp in the logs contains an underscore.
Here's an example of an event:
2021-01-03_17:34:23 CUL_MAXCUBE_FRONT credit10ms: 3494
The format is quite simple and well structured.  TIMESTAMP DEVICE  EVENT: VALUE

The regular expression in my fhem.mtail program captures the field correctly:
/^/ +
/(?P<ts>\d{4}\-\d{2}\-\d{2}_\d{2}:\d{2}:\d{2}) /  {
           # set timestamp register to parsed result. Go takes the given reference date
        strptime($ts, "2006-01-02_15:04:05")
}

But strptime() is unable to handle the example timestamp string:  "2006-01-02_15:04:05"

For each line I receive this error message:
>Error occurred at instruction 6 {strptime, 2}, originating in fhem.mtail at line 38
>Full input text from "/logs/fhem-events-2021-01-03.log" was "2021-01-03_17:34:23 CUL_MAXCUBE_FRONT credit10ms: 3494"
>I0103 16:34:27.168811       1 vm.go:108] Set logging verbosity higher (-v1 or more) to see full VM state dump.
>I0103 16:34:27.168915       1 vm.go:106] fhem.mtail: Runtime error: strptime (2006-01-02 15:04:05, 2021-01-03_17:34:23, UTC) failed: parsing time "2021-01-03_17:34:23" as "2006-01-02 15:04:05": cannot parse "_17:34:23" as " "

It seems to be a known limitation of GOs time parse function. https://godoc.org/time#Parse
GO is not able to parse timestamps with '_'. As the underscore has a special meaning and can not be quoted!
I've found an old github issue for reference: https://github.com/golang/go/issues/11334

Are there any plans to fix this in mtail by replacning the timestamp Parser used by strptime()?
What can I do to get my timestamps accepted by mtail?
Many thanks and best regards
  Tim

**Comment by jaqx0r** [comment]
Ugh, this is annoying!  The issue golang/go#11334 looks like it was incompletely fixed!

As a workaround, can you break the timestamp into two parts, and then recombine the parts in the `strptime` call?

/(?P<date>\d{4}-\d{2}-\d{2})_(?P<time>\d{2}:\d{2}:\d{2})/ {
  strptime($date + " " + $time, "2006....")
}
