### ISSUE TITLE
Corrupt results when reading from named pipe

### ISSUE THREAD

**Issue by CoolDreamZ** [google/mtail#425]
### Problem
mtail is failing to parse correctly when reading from a named pipe (e.g. see line 291 in screenshot of pipe.out below)

### Environment
```
mtail version v3.0.0-rc38 git revision 0601c73197c5e314dcf3e27218de8f8ad5a83691 go version go1.15.5 go arch amd64 go os linux
ubuntu 20.04.1 LTS
```
### Steps to reproduce
```
mkfifo pipe
cat test.log > pipe &
mtail -progs journal.mtail -one_shot -logs pipe -log_dir logs > pipe.out
```

### Expected result
The output should be the same as produced by this invokation:

`mtail -progs journal.mtail -one_shot -logs test.log  -log_dir logs > file.out`

_Note: running mtail on the named pipe a second time produced a different result (see pipe2.out)_

### Snippet of pipe.out
<img width="413" alt="Screenshot 2021-01-03 at 21 35 36" src="https://user-images.githubusercontent.com/70951446/103491203-996ae300-4e19-11eb-9538-a6aeca89a443.png">

### Files used
[files.gz](https://github.com/google/mtail/files/5762435/files.gz)

**Comment by jaqx0r** [comment]
Thanks for the detailed report!

**Comment by CoolDreamZ** [comment]
yw, thanks for your quick response :-)
please let me know if you need any more info

**Comment by jaqx0r** [comment]
#433 changed how pipes work but looks like they're still broken in this test, though the failure looks different.

**Comment by jaqx0r** [comment]
OK this is a cool bug.  Thanks for finding it!  Part of the problem is that the pipe reader exited too early rather than trying to read to the end of the pipe.  Your reproduction information is now an integration test, which has found some other bugs.

By the way, you used `-log_dir`; did you make the logs directory to get `mtail`'s own logs out?

**Comment by CoolDreamZ** [comment]
Yes, this looks like a tricky one! Different results from two consecutive runs against the same data on the pipe could be a concurrency issue? Glad the test has flushed out a few more :-)

Other than errors while I was debugging the journal.mtail program I didn't see anything interesting in the logs. Here they are:
[logs.gz](https://github.com/google/mtail/files/5808558/logs.gz)

**Comment by jaqx0r** [comment]
Thanks again.
