### ISSUE TITLE
Occasional negative timestamps

### ISSUE THREAD

**Issue by tcolgate** [google/mtail#43]
I'm using the prometheus endpoint to collect metrics and have a rule with:

```
/^\w+\s+\d+\s+\d+:\d+:\d+\..+Retrieving pluginfacts$/ {
    puppet_last_run_timestamp = timestamp()
}
```

Sometimes this works, other times I'm getting a negative result:

```
root@bass00:/etc/mtail.d# curl http://localhost:3903/metrics
# TYPE puppet_last_run_timestamp gauge
puppet_last_run_timestamp{prog="puppet.mtail",instance="bass00"} -62135596800
```

**Comment by jaqx0r** [comment]
What's an example log line when this happens?

**Comment by tcolgate** [comment]
I've added an explicit strptime, I've not seen any negative numbers yet, will close this. For completeness, an example log line is:
```
Oct  6 07:37:24.000 bass00.stg.irl.aws.quborg.com puppet-agent[17343]: Retrieving pluginfacts
```

**Comment by tcolgate** [comment]
I'm afraid that's lost to frantic trial and error. I suspect it was because I had no strptime at one point, and was assuming timestamp() would default to whatever the current wall clock time was. I have a working strptime now, and have not been able to replicate the problem.

**Comment by jaqx0r** [comment]
Yeah, timestamp *should* be walltime at the start of the line match but
being negative at all indicates a bug.

**Comment by jaqx0r** [comment]
I figured it out, and indeed it's the lack of explicit strptime.  I lied about the timestamp being walltime at the start of the line match; the value you get is undefined at program start.
