### ISSUE TITLE
Switch back to upstream afero?

### ISSUE THREAD

**Issue by filippog** [google/mtail#48]
Hi,
AFAICS changes in github.com/jaqx0r/afero have been merged upstream into github.com/spf13/afero, mtail could be switched back to that repo now?
I'm asking mostly because of Debian packaging of mtail, Debian has spf13/afero ATM.

**Comment by jaqx0r** [comment]
OK, cool.  Thanks for the pointer.

PS I am also doing debian packaging and as I'm a maintainer was going to do
the downstream maintenance there, so you should send me some PRs with the
debian/ if you want to collab.

**Comment by TheTincho** [comment]
Hey, I only see this now when trying to update the debian version of mtail :-)

@jaqx0r I have already uploaded mtail to debian a few month ago, it is team-maintained, would you like to co-maintain it?

**Comment by TheTincho** [comment]
and about the original issue, I was not sure if all the changes from @jaqx0r 's fork were integrated. so I opened spf13/afero#105, not realising @jaqx0r maintains mtail too :-)

**Comment by jaqx0r** [comment]
Sure! Send me a PR for integrating your debian bits into this repo please.
