### ISSUE TITLE
Prometheus metrics return stale timestamps

### ISSUE THREAD

**Issue by bjk-soundcloud** [google/mtail#5]
When using /metrics, the server returns the timestamp for the last time a counter value was updated.  This is not the correct thing to respond with, as it causes stale metrics to vanish when doing evaluation.

Here's an example of the output:
```
# TYPE response counter
response{status_code="200",prog="TEST.mtail",instance="X"} 55948 1434722695891
response{status_code="503",prog="TEST.mtail",instance="X"} 1 1434722073677
```

The 503 counter is ~622 seconds behind the 200 counter.  This means if I look at the current rate over 5min of metrics, 503 will vanish from my dashboard.

The correct timestamp response should be the timestamp in which a counter is read from memory.  It's also recommended for simple read-from-memory counters to not return any timestamp and the server will assign one.

**Comment by juliusv** [comment]
Yeah, I'd just omit timestamps completely and let the server assign them unless you have a special power-user reason to set them yourself.

**Comment by SuperQ** [comment]
I created a PR to remove the timestamps. https://github.com/google/mtail/pull/6

**Comment by jaqx0r** [comment]
The original intent is to proxy the timestamp from the source event, i.e the log line that generated it.  The export code was modelled after an internal export format that doesn't expire in this data path.

I see how that doesnt' work with Prometheus' staleness.  As long as the latency between event, log flush, read, and processing is short, then this change is ok.

**Comment by jaqx0r** [comment]
PR merged.

**Comment by bjk-soundcloud** [comment]
Yup, the way Prometheus stores metrics this is totally fine.  Also, I'm familiar with mentioned "internal format" :smile:  Thanks for the review/merge.
