### ISSUE TITLE
mtail does not appear to handle Windows CRLF with just a $ in the pattern

### ISSUE THREAD

**Issue by jshank** [google/mtail#518]
Running mtail version 3.0.0-rc45 on Windows 10 Pro 20H2 (19042.928), the default regex line ending `$` does not appear to correctly satisfy the default CRLF (\r\n) for Windows logs. This maybe an issue with Go based on some other searches. Simply changing the end of the regex to `\r$` resolves the issue. Is this working as intended?

The following prog works in Linux but not in Windows. Simply modifying the regex line by changing 

...`Total (?P<total_plots>\d+) plots`**\r**`$/ {` 

resolves the issue.

```
# start with harvester logs, e.g.
# 2021-04-24T11:01:53.390 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 940b588c2a... Found 0 proofs. Time: 0.98087 s. Total 19 plots

counter number_of_challenges
gauge total_plots
counter eligible_plots
counter proofs_found
histogram check_duration buckets 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 10
/^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+) harvester chia.harvester.harvester: \w+\s+ (?P<eligible_plots>\d+) plots were eligible for farming \w+\.\.\. Found (?P<proofs>\d+) proofs\. Time: (?P<search_time>[\d\.]+) s\. Total (?P<total_plots>\d+) plots$/ {
    strptime($timestamp, "2006-01-02T15:04:05")
    number_of_challenges++
    total_plots = $total_plots
    eligible_plots += $eligible_plots
    proofs_found += $proofs
    check_duration = $search_time
}
```

**Comment by salsaly4** [comment]
Thanks for the solution, get the same and seems with the same program )))

**Comment by jaqx0r** [comment]
I think the problem is due to how the lines are parsed in the tailer.  We
read until a newline on all platforms, and send everything else to be
matched against, so this includes the \r character on WIndows.
