### ISSUE TITLE
mtail prometheus exporter should export counters that are currently zero

### ISSUE THREAD

**Issue by ferringb** [google/mtail#52]
This partially relates to #40, although the phrasing of that ticket makes me think that the author may be after something else.

As noted [here](https://github.com/google/mtail/issues/40#issuecomment-238049860), mtail doesn't export a zero'd counter until it's incremented- ie, it's non zero.  This is suboptimal for the following reasons:

1. the absence of a log line match *is* a metric.  We have a pattern watching for buffer IO errors for example- a counter that should be zero 99.9-whatever% of the time.  Via the metric not being fully exported to prometheus, the only way we can confirm that mtail is actually being scraped is checking other counters we collect via mtail.
2. Via not exporting zero'd counters, prometheus's rollover logic can misinterpret the value.  Say I've got a counter of 'io_errors_total' that is currently at 6, and we're scraping every minute.   We restart the mtail process (zero'ing the counter), 10 minutes later >6 matches come in- say 8.  Prometheus should interpret that as the counter incrementing by 8- instead, since prometheus never saw the intermediate zero's (which the rate() logic would account for as a rollover), prometheus thinks the counter has increased by 2, rather than by 8.

Offhand, I couldn't find the exact spot that needed adjustment to force zero'd counters to be exported.  What's a bit odd is that the type information *is* being exported, I just couldn't quickly spot where in EmitLabelSets that it was doing the filtering.

**Comment by jaqx0r** [comment]
If the full counter state is known at compile time, mtail can export zeros
at program start.  If the value of a label is only known once the program
encounters that value in a log file, then it cannot export the counter.

I'm away from keyboard at the moment so will investigate more when I am
back but if this explains the behaviour you see then I hope it helps.

**Comment by ferringb** [comment]
I'm assuming you're talking about counters/gauges that involve the 'by' syntax- if so, that makes sense- and is something I overlooked for at least a couple of my counters.

We've got some... maintenance shall we say... that's blocking me from verifying this, but I'm pretty sure that  counters that were /not/ utilizing 'by' syntax- counter names that should be known at compile time- weren't being exported.  This for example:

```
  counter kernel_edac_events
  /kernel: \[[\d.]+\] EDAC .*/ {
    kernel_edac_events++
  }
```

**Comment by jaqx0r** [comment]
Yeah ok, in that case we have a bug. Thanks for the report!

**Comment by ferringb** [comment]
I've just verified this locally, and can provide a repro (inlined).  This is as of a780a6342bd70a8fb8ffe187ef988d5417d43a96 .

```
# derived from https://phabricator.wikimedia.org/T147923
# Syslog decorator
def syslog {/(?P<date>(?P<legacy_date>\w+\s+\d+\s+\d+:\d+:\d+)|(?P<rfc3339_date>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+[+-]\d{2}:\d{2}))/ +
  /\s+(?:\w+@)?(?P<hostname>[\w\.-]+)\s+(?P<application>[\w\.-]+)(?:\[(?P<pid>\d+)\])?:\s+(?P<message>.*)/ {
    len($legacy_date) > 0 {
      strptime($2, "Jan _2 15:04:05")
    }
    len($rfc3339_date) > 0 {
      strptime($rfc3339_date, "2006-01-02T15:04:05-0700")
    }
    next
  }
}

@syslog {
  counter kernel_mce_events
  /kernel: \[[\d.]+\] mce: .*Machine check events logged/ {
    kernel_mce_events++
  }

  counter kernel_cpu_throttled
  /kernel: \[[\d.]+\] .* above threshold, cpu clock throttled/ {
    kernel_cpu_throttled++
  }

  counter kernel_edac_events
  /kernel: \[[\d.]+\] EDAC .*/ {
    kernel_edac_events++
  }

  counter kernel_oom_kill by binary
  /kernel: \[[\d.]+\] (?P<binary>[\S]+) invoked oom-killer:.*/ {
    kernel_oom_kill[$binary]++
  }

  counter kernel_segfault by binary
  /kernel: \[[\d.]+\] (?P<binary>[^\[]+)\[\d+\]: segfault at.*/ {
    kernel_segfault[$binary]++
  }

  counter kernel_hung_tasks_total by binary
  /kernel:.*task *(?P<binary>[\S]+):\d+ blocked for more than/ {
    kernel_hung_tasks_total[$binary]++
  }

  counter kernel_warnings_total
  /kernel: \[[0-9.]+\] WARNING/ {
    kernel_warnings_total++
  }

  counter kernel_drive_errors by drive
  /kernel: \[[0-9.]+\] Buffer I\/O error on dev (?P<drive>)/ {
    kernel_drive_errors[$drive]++
  }

  # https://www.kernel.org/doc/Documentation/RCU/stallwarn.txt
  counter kernel_rcu_stalls
  /kernel: \[[0-9.]+\] INFO: rcu_[^ ]+ detected stalls? on/ {
    kernel_rcu_stalls++
  }
}
```

^^^ that config reproducible results in the following output for /metrics upon mtail being started:
```
# TYPE kernel_mce_events counter
# TYPE kernel_cpu_throttled counter
# TYPE kernel_edac_events counter
# TYPE kernel_oom_kill counter
# TYPE kernel_segfault counter
# TYPE kernel_hung_tasks_total counter
# TYPE kernel_warnings_total counter
# TYPE kernel_drive_errors counter
# TYPE kernel_rcu_stalls counter
```

**Comment by jaqx0r** [comment]
Great, thanks!  I'm sure I refactored something and that behaviour
regressed.  The metric creation code is deep in the guts of the compiler
which is not pretty, and I've got another refactor underway (for floating
point numbers) so I'll try to work on correct initialisation after that.
