### ISSUE TITLE
compiler errors can cause a nil pointer error in the prog status page

### ISSUE THREAD

**Issue by DreamedSpace** [google/mtail#535]
![image](https://user-images.githubusercontent.com/25702274/120954368-989bfb80-c781-11eb-9462-72a4c06ba65b.png)

When I deploy mtail in sidecar mode, I encountered a nil pointer error. The code does not judge whether it is empty or not.
But I didn't encounter this error when I deployed in daemonset mode.

**Comment by DreamedSpace** [comment]
https://github.com/google/mtail/blob/20ba7656d387921a93e1b8d0537f04dfd3069bd1/internal/runtime/httpstatus.go#L76

**Comment by jaqx0r** [comment]
Thanks for the report.  Can you share the commandline you used?  I don't understand what the difference between Daemonset and sidecar modes are.

**Comment by hhanshe** [comment]
I have the same problem because the format of the  -progs   .mtail file is wrong, you should check if the format of the .mtail program is correct

> ![image](https://user-images.githubusercontent.com/25702274/120954368-989bfb80-c781-11eb-9462-72a4c06ba65b.png)
> 
> When I deploy mtail in sidecar mode, I encountered a nil pointer error. The code does not judge whether it is empty or not.
> But I didn't encounter this error when I deployed in daemonset mode.

**Comment by jaqx0r** [comment]
OK that makes sense then, it's a bug in the how the compiler errors are printed to the HTML status page.  I don't understand how "sidecar mode" affects that.
