### ISSUE TITLE
mtails

### ISSUE THREAD

**Issue by mrad00** [google/mtail#540]
Thanks for discovering a problem in `mtail`!

When reporting bugs in mtail behaviour, please be as detailed as possible; describe the problem, what you wanted to have happen, what you observed instead.

If your problem is with the way an `mtail` program is behaving, please attach or include inline any mtail programs that demonstrate the bug, any log files that mtail was processing, and the observed output.

If your problem is with `mtail`, please include the commandline you started it with, and the INFO log.

See also [Reporting a problem](https://github.com/google/mtail/blob/master/docs/Troubleshooting.md#reporting-a-problem).

Thanks!

**Comment by jaqx0r** [comment]
I'm going to close this issue as there's no problem reported but please feel free to open a new one and replace the text with the information it asks for!

Thanks!
