### ISSUE TITLE
Sending SIGHUP to mtail does not remove deleted programs

### ISSUE THREAD

**Issue by nralbers** [google/mtail#543]
# Description
In the current documentation, at https://github.com/google/mtail/blob/main/docs/Deploying.md#reloading-programmes
it is stated that sending a SIGHUP signal to mtail will reload the currently available progs in the progs directory.
However, doing this does nothing.

## Tested on:

mtail version 3.0.0-rc46 git revision 76fadc0d5ef06dd83ad5129f1f14fa46f95b31a9 

## Test:
progs directory contains 2 prog files.
* Step 1, run mtail

      mtail --logtostderr --progs ./progs/ --logs ./logs/*
      I0618 11:43:46.950958   14808 main.go:114] mtail version 3.0.0-rc46 git revision 76fadc0d5ef06dd83ad5129f1f14fa46f95b31a9 
      go version go1.16.4 go arch amd64 go os linux
      I0618 11:43:46.951061   14808 main.go:115] Commandline: ["mtail" "--logtostderr" "--progs" "./progs/" "--logs" "./logs/syslog"]
      I0618 11:43:46.952234   14808 store.go:178] Starting metric store expiry loop every 1h0m0s
      I0618 11:43:46.953308   14808 runtime.go:175] Loaded program errors.mtail
      I0618 11:43:46.953469   14808 runtime.go:175] Loaded program lines.mtail
      I0618 11:43:46.953533   14808 tail.go:259] Tailing /home/ELIDED/sources/test-mtail/tests/logs/syslog
      I0618 11:43:46.953963   14808 mtail.go:124] Listening on [::]:3903

* Check stats to see program loader is showing 2 progs loaded
* rename one prog file to <name>.mtail.disabled
* In other terminal

    kill -s SIGHUP 14808

* No change to log to indicate reload, and stats page still shows 2 progs loaded

## Request for fix

Either change behavior of mtail to match documentation, or remove this documentation item as it implies that a runtime configuration change is possible when it currently is not.

**Comment by nralbers** [comment]
Note that testing on the version of mtail in the current ubuntu repo (version 3.0.0-rc24), mtail wil exit entirely on receiving SIGHUP.

**Comment by nralbers** [comment]
Looks like a SIGHUP handler was added recently. https://github.com/google/mtail/commit/7353f824ac62819701e751cb4a1046972570ace4

**Comment by jaqx0r** [comment]
Thanks for the report.  I'm certain that program reloads work when the content has changed, but I never guessed anyone would remove a program from a running mtail.  I think we can add support for that in the program loader.
