### ISSUE TITLE
Filename as a variable

### ISSUE THREAD

**Issue by hynd** [google/mtail#55]
It would be super-userful (particularly in conjunction with #21) to have the filename the line came from available as a variable.
An example use case - a directory full of access logs named by virtualhost where i'd like the vhost as a label.  Being able to extract a substring from the filename would be a nice cherry on top.

Rather than as a builtin function, my initial thought was an option to have the filename prepended to the line - it could then be partially captured and used in the action?

**Comment by sircco** [comment]
Prepending filename to the line would change original file which would be a breaking change for most regexps used with mtail. As for your use case you can use virtualhost log description in most web servers (nginx, apache..) to provide vhost name in filename.
But, thumbs up for filename as variable, we could use it as well for use case which catches exceptions across multiple golang/python service log files.

**Comment by jaqx0r** [comment]
It should be easy to start providing the file metadata, like filename, as
immutable variables in the program.  Naming is the only tricky thing, as it
has the potential to break existing programs if the name is already in use.

Currently you can't match against the contents of variables though, only
the log line.  So if you are encoding the vhost in the filename only, then
you would only be able to export the whole filename using the currently
available functions.

Damir is right that the current best method of doing this is to change the
log format to insert the vhost into the log line itself, and then you won't
need any of these features added.

There's a bug already open about doing this:
https://github.com/google/mtail/issues/36 if you'd like to subscribe.

I suppose the plan, then, would be to add the filename as a variable into
the VM, relatively easy.  Doing matches on variable contents opens up a
whole new world of complexity in programs though, so I'm not sure I want to
add that.  Limiting it to just the log filename woul also require some new
language syntax to separate the log filename from the rest of the match
program.  I suppse though, that given the language is modelled on AWK, I
can copy AWK's BEGIN statement to run code only at VM start... I am not yet
sure if that upsets or excites me.

**Comment by jaqx0r** [comment]
This is implemented as a new builtin, `getfilename()`.
