### ISSUE TITLE
Metrics stop being updated after VM's Runtime error 

### ISSUE THREAD

**Issue by AlexRRR** [google/mtail#56]
Hello,

We are currently having problems similar #50 where mtails remains unresponsive, if we check out commit https://github.com/google/mtail/commit/39de9ddba7c6c7e337db19fbaeab36cc305d5d87  things fail but still mtail is able to keep working.

My questions is why: 

- https://github.com/google/mtail/commit/39de9ddba7c6c7e337db19fbaeab36cc305d5d87 fixes it 
- and immediately  https://github.com/google/mtail/commit/c6b320f9a3ee7476019403e5076fe91bdf4a17c3 reverts the change?

Am I missing something? The latest commit still fails for me making mtail unusable as it will run for only a minute or so and then die.

Cheers

**Comment by jaqx0r** [comment]
I got confused as to what the flag is for, and why the fix fixed, that's why I reverted it.  I'm reapplyiung the fix, with a comment explaining it to msyelf.

**Comment by jaqx0r** [comment]
Please try again now I've reverted the reversion.

I think the triggering event you are seeing is that the matching program is unable to parse the line of text, so please read the info logs (--logtostderr flag to enable to stderr) to see why your program is failing.
