### ISSUE TITLE
Support progs auto reload

### ISSUE THREAD

**Issue by saddays** [google/mtail#560]
Hello, i'm using mtail to monitor docker service logs.  We need to delivery the mtail config file in real time from remote server. We don't want to restart the mtail process, but seems that mtail doesn't support this feature currently,  how can i achieve that goals ? 
       
Looking forward to your reply.

**Comment by saddays** [comment]
I found out mtail support reload with sending -SIGHUP , please ignore this issue.

**Comment by jaqx0r** [comment]
Sorry I didn't get to this sooner. Glad you found the SIGHUP handler!

I was going to suggest if you need a reload signal, the program that is
delivering the config could also send the signal.

 Or, if you're using 'scp' then having an inotify_watch program running
next to mtail could send the SIGHUP when it sees a new config appear.
https://linux.die.net/man/1/inotifywatch

**Comment by saddays** [comment]
@jaqx0r   Thanks for your kindly explanation :)
