### ISSUE TITLE
Accepting windows disk path for logs argument

### ISSUE THREAD

**Issue by TheArturthur** [google/mtail#572]
Hello there! As specified in the guide, the issue I'm encountering is the following:

## Mtail version:
`mtail version 3.0.0-rc47 git revision 5e0099f843e4e4f2b7189c21019de18eb49181bf go version go1.16.5 go arch amd64 go os windows`

## Command run:
`PS C:\Exporters\Mtail_Exporter> .\mtail-exporter.exe -progs="C:\Exporters\Mtail_Exporter\Files" -logs="E:\SQLSERVER\full_diario.log"`

## Error returned:
`E0809 11:42:16.507262    6176 main.go:219] unsupported URL scheme: "e" in path pattern "E:\\SQLSERVER\\full_diario.log"`

## Problem:
It seems like the program doesn't accept specifying a Windows disk letter. I've tried different ways, but it appears as if it only accepts UNIX paths or Windows paths in the same drive.

Is there a workaround? Am I missing something?

**Comment by jaqx0r** [comment]
Thanks for the detailed report!  You're not missing anything -- `mtail` is developed on Linux and so the windows support is lacking and relies on users like you to tell me where I messed up.

**Comment by TheArturthur** [comment]
No problem! Glad to help! I also noticed that the labelling as explained here [Metrics/Labelling](https://github.com/google/mtail/blob/main/docs/Metrics.md#labelling), can't be done, as it doesn't show the metric at all. In Linux, I've tried it and works correctly. Should I create another issue for that?

**Comment by aRestless** [comment]
The original issue can be closed due to https://github.com/google/mtail/pull/620

The metric labeling not working is something I'm not aware of on Windows (and I use mtail on Windows), so I guess a new issue with a reproduction case would be warranted.

**Comment by lindhor** [comment]
Thanks for this, it saved my day to find this fix!
