### ISSUE TITLE
support reading from systemd's journal

### ISSUE THREAD

**Issue by ibotty** [google/mtail#58]
It would be great to be able to read from systemd's journal directly, instead of going through a regular log file.

The C functions one would use are:
 * `sd_journal_open(3)` or `sd_journal_open_directory(3)` (preferably make it configurable to specify the directory, for postfix running in containers),
 * `sd_journal_add_match(3)` to match for the right unit,
 * `sd_journal_seek_head(3)` (or `sd_journal_seek_cursor(3)` if you want to jump to a previous position),
 * `sd_journal_next(3)` and `sd_journal_get_data(3)` to get the raw data.

More complex filters are certainly possible, but I don't know whether they are needed.

**Comment by jaqx0r** [comment]
I don't want to add support for a specific external system like this.
 mtail already is able to read from a named pipe or unix socket, which was
added to support rsyslogd writing directly to mtail without the
intermediate file.  If journald can be configured to use the unix socket,
then you can use this feature tool

**Comment by slomo** [comment]
I understand that supporting specific protocols is annoying. Could it be an option to support calling scripts instead?

To give a little bit more detail: I am currently using journalctl to import into mtail like this:

```
/bin/bash -o pipefail -ec "/usr/bin/journalctl  -u myservice.service -o cat -f -n 0 | /opt/mtail/mtail_3.0.0-rc34 -progs progs -logs /dev/stdin -logtostderr"
```

Which works well, except for it getting stuck sometimes (very rarely, without any error message apparently).

Apart from the issues I also don't like that I have call a shell in between here. I have considered putting a named pipe in between, but I don't think that it would fix my particular problem above, also it would lead to buffering if mtail is down / restarting which screws up my Prometheus graphs.

Could it be an option to integrate into mtail, that it can call programs / executables by itself to read log from standard out. And maybe some very basic supervision logic of restarting if there wasn't a message for n-minutes or in case the log process prints something on stderr.

I understand that these are some what unusual requirements, but it would make mtail so much better for my use case and also more versatile for accepting logs in various different transport mechanisms.

I can try to provide a PR. I just wanted to make sure first, that this would be aligned with the project goals.

**Comment by jaqx0r** [comment]
It's a good idea. However I don't think mtail should become responsible for
executing commands.  I think that is already well covered by systemd and
init, and the maintenance of custom scripts by tools like puppet and chef.

However I think mtail should offer to listen on a TCP and/or UDP port for
syslog traffic so the integration is easier, and also fix the stdin bug you
pointed out.
