### ISSUE TITLE
Please help, I can't install this package

### ISSUE THREAD

**Issue by petarkozic** [google/mtail#60]
I try to make mtail on docker machine but after two days without success. Please, can somene help me with some step by step instruction or does it exist binary for mtail. 
Linux ubuntu is. I setup golang and all path. I was installed some Prometheus exporter in go and I don't have problem.
Please, help me.
Thank you.

**Comment by dannyk81** [comment]
Here's how I got it working on my environment (Debian).

My `.bashrc` includes this:
```
export GOROOT=$HOME/go
export GOPATH=$HOME/work
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

Golang package was extracted to `$GOROOT`

Next step is to clone mtail from guthub, I used `go get` for this:
```
# go get -d github.com/google/mtail
```

and now, just run make:
```
# cd $GOPATH/src/github.com/google/mtail/
# make
```

If all goes well, you should get it built and the `mtail` binary will land in `$GOPATH/bin`

Hope this helps :)

**Comment by dannyk81** [comment]
Great, I guess you can close the issue 👍

**Comment by jaqx0r** [comment]
Thanks again Danny!

The .travis.yml in the top directory shows the versions of Go that mtail is
tested against.  If it's not in the list, I don't expect it to work.

I seem to recall that Go 1.4 was removed recently, which might correlate
with the original problem reported.
