### ISSUE TITLE
Feature request: Allow decoration function with matching of rest of line in the decorated block

### ISSUE THREAD

**Issue by jchia** [google/mtail#606]
In the syslog example in the programming guide, the rest of the line not captured for syslog's use is captured in `message` so that the decorated block can use `message` to match the rest of the line.

What about a decoration syntax that allows the user express that the decorated block should see the rest of the line after the part matched by the decorator so that the explicit capturing (to `message`) is unnecessary? In this alternative decoration mode, the decorated block sees the rest of the line instead of the original line, in the decorator does not explicitly capture the "rest of the line".

There may be some semantic awkwardness when the decorator's pattern matches from after the first character on the line, so the beginning part of the line is neither matched by the decorator nor seen by the decorated block.

**Comment by jaqx0r** [comment]
Seems like a nice idea.  Can you provide some pseudocode on how you'd like to write code using this feature?
