### ISSUE TITLE
More test failures

### ISSUE THREAD

**Issue by NightTsarina** [google/mtail#614]
Hi, it's me again :-)

After increasing the test timeouts in #612, I got more issues from the Debian build daemons when building the mtail package, with tests timing out on `TestFileSocketStreamComparison` and `TestLogDeletion`. At first I thought it was a matter of the machines being too slow for the timeouts, but I think these are actual bugs in the test suite.

## First problem: `TestFileSocketStreamComparison`

([Log from Debian buildd](https://buildd.debian.org/status/fetch.php?pkg=mtail&arch=armel&ver=3.0.0%7Erc48-2&stamp=1640989103&raw=0))

I have spent many hours of trying to understand this problem, and I think I tracked down the failure to this message seen in the test output:
```
    examples_integration_test.go:318: write unixgram @->/tmp/mtail-test744856839/anonymised_dhcpd_log: write: resource temporarily unavailable
```

I don't really understand the complicated synchronization dances happening here, nor why the write operation fails in this way, but I think the writer goroutine is exiting without ever sending the empty message to signal the end of the stream, and so the test hangs.

I wrote a workaround which seems to fix the problem by retrying the `Write` call until it succeeds or a non-timeout error is returned, but I am not sure it is the correct solution. I had to add a `Sleep` call, as I saw hundreds of timeouts until the test finishes.

## Second problem: `TestLogDeletion`

([Log from Debian buildd](https://buildd.debian.org/status/fetch.php?pkg=mtail&arch=armhf&ver=3.0.0%7Erc48-2&stamp=1640989086&raw=0))

This one I can reproduce consistently if I run the test in a loop in a slow machine. It seems to be a race condition between mtail reaching EOF and the file being deleted, and the solution is simply to call `PollWatched` before removing the file.

**Comment by jaqx0r** [comment]
Thanks for figuring these out!  Does this mean we can reduce the timeout
from the last PR? Or do the debian machines still need the longer timeout?

**Comment by NightTsarina** [comment]
> Thanks for figuring these out! Does this mean we can reduce the timeout from the last PR? Or do the debian machines still need the longer timeout?

Sadly, no: these problems caused tests to never finish, I increased the timeouts based on the time it took to complete non-hanging tests.
