### ISSUE TITLE
Language: allow metric limit it's size

### ISSUE THREAD

**Issue by Loyilee** [google/mtail#617]
Hi @jaqx0r , could we support metric to limit the size?  

Such as:
```
// use some eviction strategies (e.g. LRU 、LFU)
counter pv by uri  limit 500
```

Thus we can ensure the uri wouldn't increase unlimitied, or else  we may need import  other variable to record the size of uri , it really increase the complexity of the mtail program.   

 Could you think about it ? Thanks!

**Comment by jaqx0r** [comment]
I love this idea.

**Comment by jaqx0r** [comment]
OK the tricky part is if you have a dimensioned metric of more than one
dimension, then is the limit across all those dimensions or do you want to
specify a limt per dimension?

e.g.

counter pv by uri limit 500 -> implies no more than 500 uris

counter pv by uri, code limit 500 -> is that 500 total uris,codes or 500
codes and unlimited uris?

**Comment by Loyilee** [comment]
Sorry for that i gave an unclear example, i want to limit all dimensions.

```
counter pv by uri,code limit 500
```
For your example,i want no more than 500 uri-code combinations.
