### ISSUE TITLE
Support for copytruncate

### ISSUE THREAD

**Issue by woojae** [google/mtail#63]
Support for copytruncate when log rotating would be nice.  

copytruncate
              Truncate  the  original log file in place after creating a copy,
              instead of moving the old log file and optionally creating a new
              one.   It  can be used when some program cannot be told to close
              its logfile and thus might continue writing (appending)  to  the
              previous log file forever.  Note that there is a very small time
              slice between copying the file and truncating it, so  some  log-
              ging  data  might be lost.  When this option is used, the create
              option will have no effect, as the old log file stays in  place.

**Comment by jaqx0r** [comment]
This is a weird behaviour.  If the inode hasn't changed then it will be difficult to know if log rotation has occurred.

I think seeing that the seek pointer is well past the size of the file could be a signal.  It sounds like it is not very robust though.

So that I can learn more about it, what log program's manual did you copy this text from?

**Comment by woojae** [comment]
The text was copied from the man of logrotate. 

[https://linux.die.net/man/8/logrotate](https://linux.die.net/man/8/logrotate)

**Comment by rjmcnamara** [comment]
I'd like to see a workaround for this as well.  How often would mtail be able to do the comparison that you suggest (current pointer vs. filesize) ?   What you suggest should be sufficient unless log writes are out of control and rotations are being triggered more quickly than mtail can do the comparison.

**Comment by jaqx0r** [comment]
@woojae, thanks.

I have to check my thinking but as soon as the truncate happens, mtail
should receive a fsnotify event about the file modification; normally this
leads to us trying to read from the last file seek pointer.  At that moment
we can check if that's a valid offset in the file, and reset to zero if it
is not.

The complication is that the dance between fsnotify and file open/seek is
tricky already and I don't have the state in my head as I write this to
reason about it :-)

Sounds like a totally reasonable feature to add though.

Thanks for the report!

**Comment by Savemech** [comment]
Would be also nice, if mtail able to handle HUP signals to start re-read log files, like mtail was restarted, but with compiled mtail.progs
kill -USR1 gives nothing
kill -1 mtail gracefully shutdown 
kill -HUP mtail gracefully shutdown
but would be cool if start reading logs over again
So i enforced to call mtail from my logrotate:
```
/path/to/some/java/app/logs/*log {
        copytruncate
        rotate 7
        missingok
        size 1
        create 644 app app
        compress
postrotate
		pidof mtail || there goes full mtail init command
endscript
}
```
Would be awesome if my logrotate.d/* behold none of this

**Comment by mjf** [comment]
@jaqx0r Normally I would suggest ``SIGHUP`` to re-read configuration and ``SIGUSR1`` or ``SIGUSR2`` to re-read the logs. This is well-known common practice for *daemons* (having no terminal to hang up). But ``mtail`` does not run as a *daemon*! Therefore I would rather suggest to use ``SIGUSR1`` to re-read configuration and ``SIGUSR2`` to re-read logs (sadly, leaving no spare user signal for future use).

**Comment by jaqx0r** [comment]
This is a good idea, but please open a new issue to track this.

**Comment by Savemech** [comment]
@mjf @jaqx0r guys i created this issue for supporting linux signals:
https://github.com/google/mtail/issues/92
