### ISSUE TITLE
is it possible to remove all labels of a metrics in a program?

### ISSUE THREAD

**Issue by godsarmy** [google/mtail#631]
Hi 

I know it is possible delete a data with label  for internal metrics like 'del metrics[$label]'. But is it possible to have a quick way to remove all the labels in a metrics immediately?

I have a scenario to count differnt item's' current value in a metrics but the system could be reset (generate some reset string pattern in log) so that i would like to reset all data in the metrics in this case.

I do not think "del metrics after" could help me because the metrics should not expire until reset. Also the lablel name is not determined. So i do not have explict label names to delete.

For metrics without label, i can reset metrics value to zero to work around reset. But i do not have a way to handle metrics with labels.. The ony method in my mind is to restart mtail.

**Comment by jaqx0r** [comment]
There is not such a way.  Only restarting the mail process will reset the
variable store.

**Comment by godsarmy** [comment]
But even if mtail restarted, it would still read logs before reset status to import as metrics. If we can not handle labels individually, is it possible to add a feature to reset mtail into clean slate status when matching a pattern in log?

**Comment by jaqx0r** [comment]
If mtail is restarted, it doesn't restore any state; it loads the programs
and creates brand new metrics, then starts reading the log files at the
current end of file position.  So any metrics created are from a "clean
slate".

Right now in #617 I'm implementing a size limit for metrics, though; can
you take a look at that bug and see if it suits your needs instead?
