### ISSUE TITLE
Getting a prometheus scraping error

### ISSUE THREAD

**Issue by lyda** [google/mtail#64]
Checking the prometheus logs, I see this error:
  `text format parsing error in line 1: expected '"' at start of label value, found '2'`

The first line is:

```
http_requests_total{code=200,content_type=application/vnd.google.protobuf,method=get,vhost=some.host,prog=nginx.mtail,instance=some.instance} 20
```

Is there a reason why mtail isn't quoting the values of labels?

**Comment by jaqx0r** [comment]
Yes, it's because I am not very good at reading specs.  How this worked at all is beyond me.

**Comment by jaqx0r** [comment]
Funny , the unit tests all check for quoted labelvalues.

**Comment by jaqx0r** [comment]
OK, can you give me a mtail program and example log input that reproduces this?  I cannot.

**Comment by jaqx0r** [comment]
I can't repro this, but I did fix a parse error in the # TYPE information just now.
