### ISSUE TITLE
Support for JSON logs

### ISSUE THREAD

**Issue by sporkmonger** [google/mtail#65]
Unfortunately regexp parsing doesn't work super-well for JSON logs. I'm trying to parse the Suricata eve.json logs and things work fine until you get to escaped characters. I don't think there's a workable way to unescape escaped characters. And regardless, I'd rather not use regular expressions to parse JSON logs in the first place. Something like JMESPath with be vastly preferable for extracting JSON values from a log encoded in that format.

**Comment by BangLy** [comment]
[README_windows.txt](https://github.com/google/mtail/files/1066198/README_windows.txt)

**Comment by jaqx0r** [comment]
If you need to parse structured event logs, then mtail is probably not for you.  mtail is very much about getting instrumentation out of programs that you don't have the ability to add metrics exports to, e.g. mature open source tools and proprietary software with logs.

How about logstash (https://www.elastic.co/products/logstash)? I believe it can read structured logs.  There's also Riemann (http://riemann.io) which I know can read JSON structured events and parse and filter them, and for commercial products I hear good things about Honeycomb: http://honeycomb.io

**Comment by sporkmonger** [comment]
In this case the program in question is a mature open source tool (Suricata) that has a JSON structured log format.

**Comment by jaqx0r** [comment]
OK sure, but mtail is glue between unstructured logs and timeseries data.
You already have structured logs, so you don't need to extract structure
from them.  Thus I recommend you use one of the alternatives.

Thanks for the interest, though!
