### ISSUE TITLE
Reading a Fifo file 

### ISSUE THREAD

**Issue by yeplaa** [google/mtail#651]
In the container environment i would like read from mtail a fifo file.

In first, i created  my fifo : 
 `# mkdir /logs/fluentd; mkfifo /logs/fluentd/pipe`

Then, mtail is started with this parameters :    
 `/usr/bin/mtail -progs /progs/mariadb.mtail -logs /logs/fluentd/pipe -alsologtostderr`

But i have this mtail errors : 

I0609 15:31:56.079179       1 cancel.go:21] cancelled, setting read deadline to interrupt read
I0609 15:31:56.079184       1 cancel.go:23] use of closed file

I don't understand exactly why. I don't have this problem if i create a standard file instead fifo.

Have you an idea? 

Thanks

**Comment by jaqx0r** [comment]
FIFOs are tricky.  Do you have a program writing to the FIFO `/logs/fluentd/pipe` before you start `mtail` ?
