### ISSUE TITLE
mtail stops sending metrics to graphite and answering prometheus metrics endpoint

### ISSUE THREAD

**Issue by filippog** [google/mtail#66]
Hi!
I thought initially this was similar to #50, though there are no logs from mtail itself this time.
We are running a simple mtail instance to tail three log files (ranging from 300 lines/s to 1.2k lines/s roughly) on a central syslog host. The three files are rotated by logrotate daily, we see this in mtail logs at rotation time:

```
Jun 05 06:34:27 lithium mtail[28177]: I0605 06:34:27.635592   28177 tail.go:144] read /srv/syslog/syslog.log: file already closed
Jun 05 06:34:27 lithium mtail[28177]: I0605 06:34:27.670146   28177 tail.go:144] read /srv/syslog/swift.log: file already closed
...
Jun 05 06:34:27 lithium mtail[28177]: I0605 06:34:27.704315   28177 tail.go:144] read /srv/syslog/syslog.log: file already closed
Jun 05 06:34:27 lithium mtail[28177]: I0605 06:34:27.707416   28177 tail.go:315] Tailing /srv/syslog/syslog.log
Jun 05 06:34:27 lithium mtail[28177]: I0605 06:34:27.708463   28177 tail.go:315] Tailing /srv/syslog/swift.log
Jun 05 06:34:27 lithium mtail[28177]: I0605 06:34:27.708490   28177 tail.go:315] Tailing /srv/syslog/apache2.log
```

Though after about a week of mtail running (from git 9ae83e2c) no more logs are emitted and mtail is effectively hung as far as metrics reporting is concerned (datapoints not pushed to graphite, asking prometheus metrics on `/metrics` just hangs)

I've dumped the goroutines while mtail is hanging at https://phabricator.wikimedia.org/P5569 and the respective heap at https://phabricator.wikimedia.org/P5568

Happy to do more testing if needed, hope this helps!

**Comment by jaqx0r** [comment]
If there's no logs indicating so, then the fix above is probably not going to fix this issue.  Sorry for the extra-wide distribution on that commit.

Do you know how much RAM is being used by mtail when it stops working?  Do you think this is similar to #61 ?

**Comment by jaqx0r** [comment]
Your goroutine dump is very interesting.

It looks like goroutine 12, 16, and 158187 are all waiting on the same mutex, a single metric lock -- 12 is the VM trying to update it, and 16 and 158187 are the exporters (graphite, and prometheus, respectively) trying to read it.)  None of them *have* the lock, though.

If you can reproduce this still on the current latest code, please can you capture localhost:3903/debug/pprof/mutex  as per https://rakyll.org/mutexprofile/ so we can see who might have the lock held still.

Thanks!

**Comment by jaqx0r** [comment]
Ah that will only work with Go 1.8 and with a code change.  Sorry.  I'm trying to use that on the regression test to identify the lock holder.

**Comment by filippog** [comment]
> Do you know how much RAM is being used by mtail when it stops working? Do you think this is similar to #61 ?

Around 700M RSS and 2G VSS `mtail    28177 10.3  4.2 1927576 703216 ?      Ssl  May26 4783:36 /usr/bin/mtail`

> If you can reproduce this still on the current latest code, please can you capture localhost:3903/debug/pprof/mutex as per https://rakyll.org/mutexprofile/ so we can see who might have the lock held still.

Ok!

> Ah that will only work with Go 1.8 and with a code change. Sorry. I'm trying to use that on the regression test to identify the lock holder.

Awesome, I'll restart mtail compiled with go 1.8 and 87a5c593c and leave it running, thanks!

**Comment by jaqx0r** [comment]
In main.go, just before the options struct is created, put in the call to
runtime.Set...collection(5) (what Rakyll writes in the blog) before
compile.  I haven't checked it in because I haven't got any results yet.

**Comment by jaqx0r** [comment]
I've just pushed a new version that inludes a --debug_mutex_profile_fraction flag; set it to 5 to get the same behaviour from the blog post.

**Comment by filippog** [comment]
> I've just pushed a new version that inludes a --debug_mutex_profile_fraction flag; set it to 5 to get the same behaviour from the blog post.

Thanks! I saw the message a little while after I started using my locally modified version, anyways I got mtail stuck again this time with mutex sampling enabled below and a goroutine dump at https://phabricator.wikimedia.org/P5664

```
$ curl -s 'localhost:3903/debug/pprof/mutex?debug=1'
--- mutex:
cycles/second=2499981698
sampling period=5
231651 2 @ 0x46ea81 0x6e10a4 0x6e09cc 0x6e1ae6 0x45b0a1
#	0x46ea80	sync.(*Mutex).Unlock+0x80						/usr/lib/go-1.8/src/sync/mutex.go:126
#	0x6e10a3	github.com/google/mtail/tailer.(*Tailer).startNewFile+0x4e3		/home/godog/.go/src/github.com/google/mtail/tailer/tail.go:299
#	0x6e09cb	github.com/google/mtail/tailer.(*Tailer).openLogPath+0x2cb		/home/godog/.go/src/github.com/google/mtail/tailer/tail.go:268
#	0x6e1ae5	github.com/google/mtail/tailer.(*Tailer).handleLogCreate.func1+0x155	/home/godog/.go/src/github.com/google/mtail/tailer/tail.go:220

26556 1 @ 0x46ea81 0x4ef9fe 0x4ef71f 0x4f1727 0x6e128c 0x6e09cc 0x6e1ae6 0x45b0a1
#	0x46ea80	sync.(*Mutex).Unlock+0x80						/usr/lib/go-1.8/src/sync/mutex.go:126
#	0x4ef9fd	github.com/golang/glog.(*loggingT).output+0x29d				/home/godog/.go/src/github.com/golang/glog/glog.go:735
#	0x4ef71e	github.com/golang/glog.(*loggingT).printf+0x14e				/home/godog/.go/src/github.com/golang/glog/glog.go:655
#	0x4f1726	github.com/golang/glog.Infof+0x66					/home/godog/.go/src/github.com/golang/glog/glog.go:1073
#	0x6e128b	github.com/google/mtail/tailer.(*Tailer).startNewFile+0x6cb		/home/godog/.go/src/github.com/google/mtail/tailer/tail.go:315
#	0x6e09cb	github.com/google/mtail/tailer.(*Tailer).openLogPath+0x2cb		/home/godog/.go/src/github.com/google/mtail/tailer/tail.go:268
#	0x6e1ae5	github.com/google/mtail/tailer.(*Tailer).handleLogCreate.func1+0x155	/home/godog/.go/src/github.com/google/mtail/tailer/tail.go:220
```

Hope that helps!

**Comment by jaqx0r** [comment]
Thanks!

How long was mtail running for when this happened, and do you know how long
since the last event when you discovered the hang?  (E.g. log line parse,
metric export, etc)

It looks like it's waiting on a logging lock, in the glog package, not
mtail, in this instance. Is there free disk space when it occurs?

**Comment by filippog** [comment]
> Thanks!
> 
> How long was mtail running for when this happened, and do you know how long
> since the last event when you discovered the hang?  (E.g. log line parse,
> metric export, etc)

Yeah, I looked at one metric pushed to graphite to find out, mtail started on 20170627-15:09 and the metric stopped showing up on graphite at 20170701-12:35 (UTC) (i.e. after logrotate rotation of the files mtail is tailing, which happens at 6:30 UTC)

> It looks like it's waiting on a logging lock, in the glog package, not
> mtail, in this instance. Is there free disk space when it occurs?

AFAICT yes there is disk space available afaict. mtail is running with `-logtostderr` though and under systemd. Now I'm curious to test what happens with `-log_dir` instead and ditch stderr logging. Anything else you think I should try? thanks!

**Comment by jaqx0r** [comment]
does mtail's log and the log being read live in the same directory?

What I'm seeing in your latest thread dump is the VM runnign your program waiting on a write lock for 1580 minutes, that's goroutine 38 from https://phabricator.wikimedia.org/P5664, after calling GetDatum.

The other semacquires are all read locks from the exprot to Prometheus (three threads, one 3 minutes old, one 5 minutes, and one just new), an export to graphite thread (blocked 1580 minutes).  These are all on the same metric.   What is your program doing?  Does it have a lot of dimensions, or a lot of variance on the keys and values in the dimensions?  (Maybe you can post it here.)

The program loader is blocked on chan send for 1580 minutes, because the VM is; the tailer is blocked on chan send for the same time because the loader is blocked, likewise the fsnotfy watcher is because the tailer is blocked (I actually don't know why the fsnotify select is blocked, but my bad read of the source is because there's a chan send in that select block to the watcher errors, which is blocked by the tailer not reading them.)

So the root of the issue is the lock on that one metric.  If we can find out what the metric is then we can maybe learn more about this.

I have a hunch that it's the linear search in findLabelValueOrNil and you have a very large keyspace on this metric.  If you had a cpu profile as well as the thread dump, then we might see evidence of that.  The CPU profile is on /debug/pprof/profile .

**Comment by filippog** [comment]
> does mtail's log and the log being read live in the same directory?

No, we're running mtail via systemd and mtail's previous invocation before the current test with `-log_dir` had its stdout/stderr attached to systemd' sockets and thus journald. journald output also is picked up by rsyslog and written to `/var/log/syslog`. The logs monitored by mtail live on a different filesystem under `/srv/syslog`

> 
> What I'm seeing in your latest thread dump is the VM runnign your program waiting on a write lock for 1580 minutes, that's goroutine 38 from https://phabricator.wikimedia.org/P5664, after calling GetDatum.
> 
> The other semacquires are all read locks from the exprot to Prometheus (three threads, one 3 minutes old, one 5 minutes, and one just new), an export to graphite thread (blocked 1580 minutes). These are all on the same metric. What is your program doing? Does it have a lot of dimensions, or a lot of variance on the keys and values in the dimensions? (Maybe you can post it here.)

Mostly incrementing simple metrics, nothing too complex I'd say. I've included the program at the end here. In terms of cardinality, each metric is repeated about 8-10 times with different `service` or `binary` key.

> The program loader is blocked on chan send for 1580 minutes, because the VM is; the tailer is blocked on chan send for the same time because the loader is blocked, likewise the fsnotfy watcher is because the tailer is blocked (I actually don't know why the fsnotify select is blocked, but my bad read of the source is because there's a chan send in that select block to the watcher errors, which is blocked by the tailer not reading them.)
> 
> So the root of the issue is the lock on that one metric. If we can find out what the metric is then we can maybe learn more about this.
> 
> I have a hunch that it's the linear search in findLabelValueOrNil and you have a very large keyspace on this metric. If you had a cpu profile as well as the thread dump, then we might see evidence of that. The CPU profile is on /debug/pprof/profile .

Makes sense, thanks a lot for investigating! I'll leave mtail running now with `-log_dir` and report back if it still blocks, it has been running for a week now without issues. When and if mtail blocks again I'll capture the cpu profile as well as the rest.

```
# Syslog decorator
def syslog {/(?P<date>(?P<legacy_date>\w+\s+\d+\s+\d+:\d+:\d+)|(?P<rfc3339_date>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+[+-]\d{2}:\d{2}))/ +
    /\s+(?:\w+@)?(?P<hostname>[\w\.-]+)\s+(?P<application>[\w\.-]+)(?:\[(?P<pid>\d+)\])?:\s+(?P<message>.*)/ {
        len($legacy_date) > 0 {
            strptime($2, "Jan _2 15:04:05")
        }
        len($rfc3339_date) > 0 {
            strptime($rfc3339_date, "2006-01-02T03:04:05-0700")
        }
        next
    }
}

@syslog {
counter mce_events
counter cpu_throttled
counter edac_correctable_errors
counter edac_uncorrectable_errors
counter edac_events

counter upstart_respawn by service
counter oom_kill by binary
counter segfault by binary

/kernel: \[[\d.]+\] mce: .*Machine check events logged/ {
  mce_events++
}

/kernel: \[[\d.]+\] .* above threshold, cpu clock throttled/ {
  cpu_throttled++
}

/kernel: \[[\d.]+\] EDAC / {
  edac_events++
}

# See also https://github.com/google/mtail/issues/50
#/kernel: \[[\d.]+\] EDAC MC\d+: (\d+) CE/ {
#  edac_correctable_errors += $1
#}
#
#/kernel: \[[\d.]+\] EDAC MC\d+: (\d+) UE/ {
#  edac_uncorrectable_errors += $1
#}

/kernel: \[[\d.]+\] init: (?P<service>[\S]+) .*process ended, respawning/ {
  upstart_respawn[$service]++
}

/kernel: \[[\d.]+\] (?P<binary>[\S]+) invoked oom-killer:.*/ {
  oom_kill[$binary]++
}

/kernel: \[[\d.]+\] (?P<binary>[^\[]+)\[\d+\]: segfault at.*/ {
  segfault[$binary]++
}

}
```

**Comment by jaqx0r** [comment]
Huh, with only one label on the metrics, the search-time hypothesis is probably invalid.

Is it still OK at the moment? :)

**Comment by filippog** [comment]
> Huh, with only one label on the metrics, the search-time hypothesis is probably invalid.
> 
> Is it still OK at the moment? :)

Sadly not :( I've collected more debug but skipped the cpu profile (let me know if you'd like it!)

`$ curl -s 'localhost:3903/debug/pprof/mutex?debug=1'`
https://phabricator.wikimedia.org/P5808
`$ curl -s localhost:3903/debug/pprof/goroutine?debug=2`
https://phabricator.wikimedia.org/P5809
`$ curl -s http://localhost:3903/debug/pprof/heap?debug=1`
https://phabricator.wikimedia.org/P5810
`$ cat /var/log/mtail/mtail.lithium.mtail.log.INFO.20170706-122337.1195` (the last log file written)
https://phabricator.wikimedia.org/P5811

The log file seems interesting, that's an awful lot more `Tailing` log files than I was expecting, around the time logrotate comes around of course

**Comment by jaqx0r** [comment]
I'm always interested in the CPU profile, I am still lost as to why this is
happening and can't rule anything out, maybe that profile will have the
clue to unblock this investigation.

Do you know when the metrics stop relative to the log file you shared?

**Comment by jaqx0r** [comment]
Notes to self:
Tail.go:144 needs more debugging output, such as the FD that is being read,
and the FD mapping should be logged too.

Fillipo: what is at 10.64.32.155:2003? I think I have a new theory about
the failure... The push export may still be holding the lock.

**Comment by filippog** [comment]
> Notes to self:
> Tail.go:144 needs more debugging output, such as the FD that is being read,
> and the FD mapping should be logged too.
> 
> Fillipo: what is at 10.64.32.155:2003? I think I have a new theory about
> the failure... The push export may still be holding the lock.

That's our graphite server where mtail is pushing metrics with `-graphite_host_port graphite-in.eqiad.wmnet:2003`

> I'm always interested in the CPU profile, I am still lost as to why this is
> happening and can't rule anything out, maybe that profile will have the
> clue to unblock this investigation.

good idea! I tried capturing the cpu profile now and it is empty :( I'm assuming because very little or nothing is running? (localhost:3903 is ssh-forwarded to the machine running mtail)

```
$ go tool pprof -top http://localhost:3903/debug/pprof/profile 
Fetching profile from http://localhost:3903/debug/pprof/profile
Please wait... (30s)
Saved profile in /Users/godog/pprof/pprof.mtail.localhost:3903.samples.cpu.003.pb.gz
profile is empty
```

> Do you know when the metrics stop relative to the log file you shared?

Interesting theory re: push export locking, I checked graphite (prometheus isn't scraping mtail yet) and the last data points came it on July 20th at around 5:45-6:00 UTC.

**Comment by jaqx0r** [comment]
I'm still not convinced I understand what is happening, but try out this latest version and let's see what changes.  Thanks again for your patience.

**Comment by jaqx0r** [comment]
Thanks for trying to get the CPU profile.  Next time mtail locks up can you resend all the same informatoin you did last time, without the CPU profile if it's empty.

One more think I just learned about is a trace -- if you can fetch /debug/pprof/trace?seconds=5 and yoou'll get a binary file to be read by go tool trace, that would be very useful too.

**Comment by jaqx0r** [comment]
If mtail locked up in the 5:45-6:00 window on the 20th, then that's about half an hour before the next log rotation would have occurred at 06:28.  So I don't thikn the log rotation itself is triggerring this.

I would like to find out how to debug who is currently holding the lock that the others are waiting on.

**Comment by jaqx0r** [comment]
Oh no.

I think I have figured it out.

Your last goroutine dump has goroutine 16 blocking on semaquire, this is export/graphite.go:25 in which we take the lock before reading the name, etc of the mertric inorder to print it.

AT the same time, EmitLabelSets is blocking on chan send:

```
goroutine 217452 [chan send, 10262 minutes]:
212	​github.com/google/mtail/metrics.(*Metric).EmitLabelSets(0xc4201d2280, 0xc42db79380)
213	​	/home/godog/.go/src/github.com/google/mtail/metrics/metric.go:177 +0x115
214	
```

It's blocking because the channel is 0 sized.  The channel is read by writeSocketMetrics in export.go:102 (current HEAD) as it iterates over the channel range; it's not iteratin at the momebt because line 102 inyour dump (103 at head) is the function call to the function that is blocking on the same mutex that EmitLabelSets probably has open.

I am shocked that this bug manifests after a long period of time.

I can fix it by making that channel have a buffer the size of the labelset it needs to iterate over, which defeats the purpose of it being a channel IMHO, it was supposed to be a generator pattern, and pregenerating the list means we may as well just return a slice from EmitLabelSets instead.

Or, note that in export.go:99 we already hold the lock.  The lock taken in writeMetricToGraphite is in error because the lock should already be held.

There's another bug in that the lock is not released when I thought it was: the defer m.RUnlock() on line 100 (again, at HEAD) doesn't cause the lock to be released until the whole function is returned from, not at the end of the loop scope.

:emoji facepalm:

**Comment by jaqx0r** [comment]
Thanks @filippog for your patience and the bug report.  I learned a lot about the go debugging tools in this adventure and I think as a side effect some tangential debugging problems have been addressed.

In hindsight my initial theory was correct but I hadn't figured out where the rest of the goroutines were at that time to see how they were linked.

**Comment by filippog** [comment]
Thanks a lot @jaqx0r for your patience too with this bug report! :) I'm running mtail at 1f87b2be4 and will report back in a couple of weeks to see if the behaviour is still there.

re: pprof reports it could be useful to add the relevant commands to e.g. contribution guidelines and/or github issue template so it isn't missed when reporting problems like this

**Comment by filippog** [comment]
@jaqx0r I wanted to report that the latest mtail at `5e6d389` running since Aug 29th is still chugging logs away!

**Comment by jaqx0r** [comment]
Good news, thanks!
