### ISSUE TITLE
Can i count string in my mtail program?  

### ISSUE THREAD

**Issue by kumaresh0102** [google/mtail#668]
counter abc_total by log_level

/^(?P<time>\d{4}-\d{2}-\d{2} d{2}:\d{2}:\d{2},\d{3}) / +
/(?P<log_type>(\[\w+\] )+)/ +
/\[(?P<log_level>(INFO |WARN |ERROR))\]/ +
/$/ {
    strptime($time, "2022-02-18 11:04:17,803") #for tests
    abc_total[$log_level]++
}

Thanks!

**Comment by kumaresh0102** [comment]
My logs are like this : 
2022-02-18 11:04:17,803 [INFO ]
2022-02-18 11:04:20,414 [INFO ]
2022-02-18 11:04:16,056  [WARN ]
2022-02-18 11:04:05,669  [ERROR]

**Comment by li35619081** [comment]
yes.you can.
