### ISSUE TITLE
regex  ..Redeclaration of capture group `0' previously declared

### ISSUE THREAD

**Issue by li35619081** [google/mtail#693]
filename=/20221117/com.test.api.ApiService/queryList/10.1.3.4/10.1.5.4/consumer.success

classname=com.test.api.ApiService
ip1=10.1.3.4
ip2=10.1.5.4
I want to get this information from the filename

==================
gauge filename1_success by method
gauge filename2_success by method

hidden text filename0
hidden text filename1
hidden text filename2

#/20221117/com.test.api.ApiService/queryList/10.1.3.4/10.1.5.4/consumer.success
/(?P<date>\d+) (?P<count>\d+)/ {
	filename0=getfilename()
	#20221117
	filename1=subst(/\/\d+/, "",filename0)   
	filename2=subst(/(([a-zA-Z_][a-zA-Z0-9_]*[.])*([a-zA-Z_][a-zA-Z0-9_]*))/, "",filename0)  
	filename1_success[filename1] += int($count)
	filename2_success[filename2] += int($count)
	 
}

================

`Redeclaration of capture group `0' previously declared at test.mtail:14:18-24`

**Comment by jaqx0r** [comment]
Can you highlight what's at line 14?  I can't tell from your report.

**Comment by EconomicTouristsArmLate** [comment]
Also ran into this just now. The issue here is the second `subst()`.
Apparently, having 2 `subst` calls within a scope breaks with the above error message.

This example works fine:
```
gauge foo by asdf
gauge bar by asdf
/(?P<asdf>.+)/ {
  foo[subst(/\d/, "", $asdf)]++
  /.+/ {
    bar[subst(/\d/, "", $asdf)]++
  }
}
```

while this throws the `Redeclaration of capture group 0` error:
```
gauge foo by asdf
gauge bar by asdf
/(?P<asdf>.+)/ {
  foo[subst(/\d/, "", $asdf)]++
  bar[subst(/\d/, "", $asdf)]++
}
```
