### ISSUE TITLE
Support for timers

### ISSUE THREAD

**Issue by davidreuss** [google/mtail#7]
Hello,

I really like the simplicity of `mtail`, but for my usecase i need to report timings from log-files, and i saw this in the code

https://github.com/google/mtail/blob/764e4b16d2419e123bbb847e6b87b5ad003875d3/exporter/export_statsd.go#L23

Is there any plans for adding explicit timer metrics, or is there some workaround that's usable?

**Comment by jaqx0r** [comment]
I'll be honest, I don't remember what I meant with that comment. :)

What sort of timing do you want? The rsync program shows how you can
measure the time between log messages based on their timestamps, if you're
looking for inter event latency.

If you want to extract just single values from one line for timing, I.e.
the log already tells you the time spent for something, then that's a
simple assignment.

But I feel that you figured that out and you mean something different.

Can you explain what you want to do?

Also note that the statsd code has never been tested in amget, and I barely
know how statsd works so I will need some help understanding what statsd
does with the timing values to know how to plumb that through mtail.

Thanks!

**Comment by jaqx0r** [comment]
Tested in *anger*.

If you can give an example of the log content, and the output you want to achieve, that would be very helpful.

**Comment by davidreuss** [comment]
Well basically i'd like the calculated/derived metrics you get from statsd with timers, for logs which contain timing info like access logs, or similar.

https://github.com/etsy/statsd/blob/master/docs/metric_types.md

Dies that help? .. Basically i'd like to be able to get the upper/mean/average and percentiles of a metric seen over time.

**Comment by jaqx0r** [comment]
Ah I think I understand.  If we could annotate some variables with their
units, statsd would build a distribution of latency for those units in the
time dimension.  Cool.  I was worried that you wanted mtail to support
distribution types too which I've been deliberately avoiding.

I think this would look like:
1/ add a clause to the variable declaration to indicate units as part of
the variable  e.g.
'gauge foo in ms'
2/ for those exporters that support it, set the units when the variable is
converted
... so not too difficult.

Any thoughts on the syntax for how this units declaration should look?

**Comment by jaqx0r** [comment]
Statsd treats "timers" as a separate type from gauges and counters, so using units to mark them in mtail creates an opportunity for confusing behaviour.  mtail doesn't care that the gauge contains time.  So you can make a buggy program by setting your unit to any string so statsd will probably reject it, or worse set your units in seconds and have statsd do something totally different (set types.)

So I could make timers a mtail type to solve this and downcast them to regular gauges for all other exports.

**Comment by davidreuss** [comment]
Yes, i think that makes more sense, to actually have a "timer" metric type, although at first glance the unit sounded like a simpler solution, but i agree about the confusion it would cause, when looking at the bigger picture.

**Comment by jaqx0r** [comment]
So then the syntax would be "timer foo, counter bar, gauge qux" and timer would be equivalent to gauge for all behaviours except statsd export.  Additionally it would implicitly know that the units are in time, but there would have to be conversions between s, ms, ns for example, depending on the log being read.

**Comment by jaqx0r** [comment]
Try this, let me know how it goes for you!

**Comment by davidreuss** [comment]
That was fast. Thanks, i tried just go get'ing it, and got this

$ go get github.com/google/mtail
# github.com/google/mtail/vm
vm/lexer.go:46: undefined: TIMER
vm/lexer.go:73: undefined: TIMER

**Comment by jaqx0r** [comment]
Use make to rebuild the parser first.

**Comment by davidreuss** [comment]
Ah of course .. Thanks again!

**Comment by jaqx0r** [comment]
No problem. Let me know how it goes.

**Comment by davidreuss** [comment]
It seems to be working, but i have two issues. 

The statsd exporter seems to crash if there hasn't been any metrics since the last push. And also, i'm a bit confused of how much you can do with the mtail language, but i think i might need to turn it upside down, to maybe see if mtail can already do what i'm trying to accomplish. It's basically just gathering some metrics from something like an access log, where i have multiple fields, where one of them is an identifier and another is time elapsed (already in miliseconds).

Now what i would like is to graph/extract different percentiles/averages and so on for each timer (for each identifier), so i can get a simple "average time elapsed for this identifier". I tried screwing around with doing the calculations myself, but i'm not sure if mtail supports division? .. Can't find any examples of it, and when i try a simple $var / $total (or similar), it doesn't export any metrics at all (but doens't seem to fail either).

But maybe there's a whole other way of going about this?

**Comment by jaqx0r** [comment]
For the crash, I'm not surprised. Can you open a new issue with the crash
dump?

The other problem sounds easy, but its likely parts of the VM are missing
because I've only implemented the parts I need as they crop up. I checked
the VM code and div isn't implemented... Yet :). Can you open another issue
with an example log line and the program you expected to be able to write
to act on it?

Thanks!

**Comment by davidreuss** [comment]
Thanks for quick feedback, i've opened #9 and #8
