### ISSUE TITLE
no oneshot?

### ISSUE THREAD

**Issue by TomDunham** [google/mtail#70]
Hi,
Happy to accept I might be missing something here, but this commit https://github.com/google/mtail/commit/bac6bb400f96a6d60aeb1ad0dcd48708d8f9c3d6#diff-7ddfb3e035b42cd70649cc33393fe32cR76 seems to have broken `-oneshot`.

`mtail -one_shot  -one_shot_metrics -logtostderr  --progs ./progs/ --logs ./logs/else.log`
Gives output like this:
```
I0705 03:01:07.568566    5802 main.go:54] mtail version  git revision  go version go1.7.4
I0705 03:01:07.584662    5802 loader.go:122] Loaded program else.mtail
I0705 03:01:07.584698    5802 loader.go:133] Program else.mtail has thread ID 656c7365
I0705 03:01:07.584819    5802 loader.go:122] Loaded program linecount.mtail
I0705 03:01:07.584830    5802 loader.go:133] Program linecount.mtail has thread ID 6c696e65
```

Removing the `if !*oneShot {` in `main.go` gives the expected output:

```
Oneshot results:
I0705 03:03:15.773862    5836 mtail.go:47] Oneshot "./logs/else.log"
./logs/else.log: 2 MAXPROCS, 2 CPUs, I0705 03:03:15.774151    5836 vm.go:576] Starting program linecount.mtail
I0705 03:03:15.774239    5836 vm.go:576] Starting program else.mtail
5 lines, 1.515613ms total time, 303.123 µs/line
Metrics store:{
  "line_count": [
    {
      "Name": "line_count",
 ...
```

**Comment by SuperQ** [comment]
Yup, I was just wanting to test something, and the latest master build breaks oneshot.

**Comment by jaqx0r** [comment]
Curses!  I was using it myself about a month ago, but have been messing
with the startup code as Tom points out.  This needs an integration test as
well.
