### ISSUE TITLE
Mtail does not count the amount of lines correctely

### ISSUE THREAD

**Issue by dbaudat** [google/mtail#768]
Hi,

I am new in using mtail and hope not making a mistake creating this bad behavior.

I am using the following version:
mtail version 3.0.0-rc52 git revision 6c1f19c1f95ccf1afe2708e41d188bd656db3aa1 go version go1.20.5 go arch amd64 go os linux with 4 log files, the peak amount of lines is app. 30 000 per minute.

The following command is used to start the mtail process:
/opt/CoMo/mtail_exporter/mtail -address 10.223.86.12 -progs /opt/CoMo/mtail_exporter/config_mtail.mtail -logs  /var/log/MAAA/maaa_syslog.log -logs...

I use in example such filter:
counter MAAA_PPEAPSIM_Accounting_Start_counter
/pw-maaa.*?Type=Accounting-Start.*?LoginType=POSTPAIDEAPSIM/ {
  MAAA_PPEAPSIM_Accounting_Start_counter++
}

The machine is not overloaded (CPU / memory or disk), but the results presented in mtail do not match the amount of filterd lines in the log files.

Am I doing somthing wrong? Am I reaching some limits?

Thank you in advance.
Denis

**Comment by jaqx0r** [comment]
Can you share an example of a log line?

Please follow the https://github.com/google/mtail/blob/main/docs/Testing.md guide.
