### ISSUE TITLE
Unable to access from public network

### ISSUE THREAD

**Issue by happy-Z** [google/mtail#775]
./mtail   --progs /usr/local/matil/error_count.mtail --log_dir /usr/local/matil   Run on latest version

Only ipv6 ports can be bound,so unable to access from ipv4 public network

---
INFO:
I1017 17:23:08.063335 3452227 store.go:189] Starting metric store expiry loop every 1h0m0s
I1017 17:23:08.063603 3452227 runtime.go:187] Loaded program error_count.mtail
I1017 17:23:08.063671 3452227 mtail.go:136] Listening on [::]:3904

**Comment by jaqx0r** [comment]
I'm not sure what you're trying to achieve from your description, but try the `--address` flag to set the specific IP to bind the listener on.

**Comment by happy-Z** [comment]
![image](https://github.com/google/mtail/assets/58432632/90068b40-a1ab-4736-90cc-a22e570a6135)
It cannot be accessed by public IP because it is only bound to the ipv6 port. My public IP is ipv4.

**Comment by jaqx0r** [comment]
I think you want `mtail` to listen on your IPv4 address.  Would you try `--address <ipv4>` then?
