### ISSUE TITLE
export.go:123 Crashes with segmentation fault when running prometheus one shot.

### ISSUE THREAD

**Issue by bebtio** [google/mtail#783]
Here is a summary of the error:

`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47f1e2]

goroutine 1 [running]:
sync.(*WaitGroup).state(...)
        /usr/lib/golang/src/sync/waitgroup.go:40
sync.(*WaitGroup).Add(0x0?, 0x0?)
        /usr/lib/golang/src/sync/waitgroup.go:63 +0x22
github.com/google/mtail/internal/exporter.New({0xb55cd8?, 0xc00043c380}, 0x0, 0xc0001a8fc0, {0xc00060fb20, 0x0, 0x7fc447000000?})
        ./mtail/internal/exporter/export.go:123 +0x7a5
main.main()
        ./mtail/cmd/mtail/main.go:251 +0x1e70
`
And the command that generated it:

`./bin/mtail -progs my_rules --one_shot --one_shot_format prometheus --logs test.log`

my_rules contains a file called testrule.mtail with contents:

The test.log file just contains 5 lines:

`
a

a

a

a

a
`

`
counter lines_total
/$/ {
  lines_total++
}
`

It appears that in cmd/mtail/main.go:251

nil is passed as the second parameter into the exporter.New(). This eventually gets passed all the way down to 
export.go:123 where the waitGroug, which is nil, attempts to call wg.Add(1) and crashes.

One way to possibly fix this is to wrap the portions of code that access the wg variable in a 

` if wg != nil `

Statement.

**Comment by jaqx0r** [comment]
Thanks for the report!  Looks like I missed this part during a refactoring.
