### ISSUE TITLE
Add string support for storing intermittent values

### ISSUE THREAD

**Issue by rcjverhoef** [google/mtail#81]
As discussed on https://groups.google.com/forum/#!topic/mtail-users/72_-p1wiPsY, would like to request support for being able to store key-value pairs for later use with the key being a string value.

The problem is that I'm trying to translate the log of an ftp service to metrics. The logs from the used 3rd software logs data at various intervals like below:

	2017-04-28 12:00:00 123 127.0.0.1 Ftp session opened
	2017-04-28 12:00:01 123 127.0.0.1 User 'A' logged in 
	2017-04-28 12:00:02 123 127.0.0.1 12 bytes downloaded
	2017-04-28 12:00:04 123 127.0.0.1 8 bytes downloaded
	2017-04-28 12:00:05 123 127.0.0.1 Ftp session closed
	....
	2017-04-28 12:00:09 123 0.0.0.0 Ftp session opened
	2017-04-28 12:00:10 123 0.0.0.0 User 'B' logged in 

Would like to expose metrics based on how long a user session lasted, as well as how many bytes were downloaded in total by a user. The log above is in the format 

       <timestamp> <pid> <ip> <message>

Some pseudocode in mtail I would be looking to use:

        counter bytes_downloaded by user,ip
	hidden counter tmp_bytes_downloaded by pid
	map pid_to_user pid int->user string

	/<timestamp> <pid> <ip>/ {
	  strptime(<timestamp>)

		/FTP session opened/ {
			...
		}

		/<user> logged in / {
			len($user) > 0 {
				map[$pid] = $user
			}
		}

		/<bytes> downloaded/ {
			bytes_downloaded[$pid] += bytes
		}
	 
		/FTP session closed/ {
			len(map[$pid]) > 0 {
				bytes_downloaded[map[$pid]][$ip] = bytes_downloaded[$pid]
			}
			del map[$pid]
			del tmp_bytes_downloaded[$pid]
		}
	}

**Comment by jaqx0r** [comment]
I think we can achieve this by supporting String alongside Int and Float for the value type of a metric, so that you can assign a string to a hidden metric, e.g.:

hidden counter tmp_bytes_downloaded by pid
hidden pid_to_user by pid

and later the assignment

map[$pid] = $user

would infer the type as String.

**Comment by jaqx0r** [comment]
Working on this now; we can't expose the string's values on a prometheus /metrics endpoint but they can be exposed to the others.  I could imagine doing a transposition of a string metric to export the value as a label, though.

**Comment by jnovack** [comment]
I see there's some psuedo-code, unfortunately, I'm blanking on how to actually implement this.

`mtail version v3.0.0-rc16 git revision 77eeba903db0ffd90e29c1ee778fdefb0112bfab go version go1.11`

`map[$pid] = $user` is not working for me.  Where is `pid_to_user` actually being called??

`hidden pid_to_user by pid` also fails.  `unexpected ID, expecting COUNTER or GAUGE or TIMER or TEXT`

Given the following `.mtail` program
```
counter incoming by ipaddr, country
hidden text icid_to_ip by icid
hidden text icid_to_country by icid

/ICID (?P<icid>\d+) address (?P<ipaddr>\d+(\.\d+){3})/ {
     icid_to_ip[$icid] = $ipaddr
}

/ICID (?P<icid>.+) country (?P<country>.+)/ {
     icid_to_country[$icid] = $country
}

/ICID (?P<icid>\d+) close/ {
    incoming[icid_to_ip[$icid]][icid_to_country[$icid]]++
}
```

and input
```
ICID 1234 address 1.1.1.1
ICID 1234 country Fake
ICID 1234 close
```

I'm expecting:
```
incoming(ipaddr="1.1.1.1", country="Fake") 1
```

What am I doing wrong?

**Comment by jnovack** [comment]
If I change

```
/ICID (?P<icid>\d+) address (?P<ipaddr>\d+(\.\d+){3})/ {
     icid_to_ip[$icid] = "this-is-a-string"
}

/ICID (?P<icid>.+) country (?P<country>.+)/ {
     icid_to_country[$icid] = "this-is-also-a-string"
}
```

I get
```
incoming{country="21569178",ipaddr="21569178",prog="maillogs.mtail"} 1
```

It seems to be converting strings to floats.
