### ISSUE TITLE
option should be added to allow explicitly setting interface on which to bind

### ISSUE THREAD

**Issue by drawks** [google/mtail#82]
the singe `-port` option is implemented in such a way as to make it impossible to selectively bind a specific interface.

It takes a string as an argument, but then that string is passed to `http.ListenAndServe` with a bare colon prepended to cause a default `0.0.0.0` binding. 

https://github.com/google/mtail/blob/master/mtail/mtail.go#L288

I propose that either the code be modified to allow for a full `address:port` being passed from the `-port` flag OR adding an additional `interface/address` flag.

The use case is for exporting metrics on a multihomed machine where it is undesirable to have an http listener on every interface.

**Comment by jaqx0r** [comment]
As mentioned on the PR review, I think this is a good idea, and prefer the "add additional `address` flag" option.

**Comment by drawks** [comment]
@jaqx0r latest push conforms with the PR request
