### ISSUE TITLE
What’s up with the tags?

### ISSUE THREAD

**Issue by ruuda** [google/mtail#847]
Thank you for building Mtail. I am working on build automation that automatically detects new releases, and yesterday it picked up a large number of new tags:

![2024-04-25-mtail-tags](https://github.com/google/mtail/assets/506953/51346e2f-0a8d-4eed-9be3-a8d02c9b486d)

Just to double check, was this intentional, or might it be a bug in your release automation? Releasing 14 new release candidates in one day seems a bit excessive to me.

**Comment by jaqx0r** [comment]
I'm trying to test release signature verification, and it's a massive pain
to debug. I don't like it either

**Comment by jaqx0r** [comment]
What's your release automation? It sounds interesting.

**Comment by ruuda** [comment]
> I'm trying to test release signature verification

I see, thank you for the clarification and the quick response. Maybe it is possible to test with a testing fork of this repository to not pollute this one? I can imagine it’s difficult to get approval for it and get everything set up though.

> What's your release automation? It sounds interesting.

We have an internal build/package registry that builds a few dozen packages from source, `mtail` is one of them. (Most packages in there are ones where we really want to run the latest version. For `mtail` that is not a concern, we just added it because it’s not packaged for Ubuntu and this is the easiest way for us to get it running on our infrastructure.) It tracks in a database what tags we have binaries for, and then periodically it runs `git ls-remote --tags` to see if there are any new tags upstream. If there are and they match a selector, it builds them and sends a notification. Usually we have a selector that ignores release candidates, but for `mtail` the only releases in the past few years have been `-rc` versions, so here we do build them.

**Comment by jaqx0r** [comment]
I'll add the word 'test' at the end of the tag name.

Once this is working I plan on stopping the RC versions.

Hopefully that helps your automation.

**Comment by ruuda** [comment]
Yes that would be very useful, then we can ignore tags that contain `test`. Thanks! :heart:

**Comment by jaqx0r** [comment]
If you ignore mtails rc tags as well you'll get the builds again soon!

**Comment by jaqx0r** [comment]
My testing is now complete.  There won't be any more tag explosion (for a while...)
