### ISSUE TITLE
Allow matching regexes against variables

### ISSUE THREAD

**Issue by TheTincho** [google/mtail#88]
Hi,

While writing the Postfix rules (#87), something that would have helped coding and making the rules more solid is to allow to match regexes against variables.

For example, the syslog decorator leaves all interesting text in a $description variable, but then all regexes forcefully have to match against the whole line. Having a perl like binding operator ($var ~ /regex/) would solve this.

Thanks.

**Comment by TheTincho** [comment]
When I said variables, I meant variables and/or capture groups.

**Comment by jaqx0r** [comment]
This came up in issue #36 as well.  I don't have a good answer to that yet,
the match implicitly assumes its on the current line input only.

I like the perl option; its $_ is a lot like the implicit line in mtail.
Thanks for the suggestion!

**Comment by jaqx0r** [comment]
I've tested this in the latest commit and I think it's working as described now.
