### ISSUE TITLE
Capture groups can't be used in decorated blocks

### ISSUE THREAD

**Issue by TheTincho** [google/mtail#89]
Related to #88, I noticed that if I use the decorator syntax, I can't reuse the captured groups created inside the decorator. This would be specially useful for things like the syslog decorator.

For example, this works:
```
/(...).*/ {
    counter test
    $1 == "Dec" {
        test++
    }
}
```

But this does not (and also it is silently discarded, as I reported in #86):

```
def decorator {
    /(...).*/ {
        next
    }
}

@decorator {
    counter test
    $1 == "Dec" {
        test++
    }
}
```

**Comment by jaqx0r** [comment]
Yeah, the caprefs in the decorator are only in the scope of the decorator.
Leaking them out into the decorated block was never intended -- decorators
were designed only for the purpose of sharing timestamp parsing code!

As the caprefs are not visible at the point of use of a decorator, I am
hesitant to let them show up in the decorated block in case strange
variable name conflicts occur.  Especially with the numbered references,
which are easy to overload with nested matches.

But that makes me think that explicitly declaring which names are allowed
to appear in scope as part of the decorator syntax would mitigate that, for
example:

@syslog using $description {
   foo[$description]++
}

(not sure about the word 'using' yet though.)

Thanks for the report, good idea, I'll think about this some more!

**Comment by mjf** [comment]
@jaqx0r 

What about:

    @syslog with $foo, $bar {
        baz[$foo][$bar]++
    }

or

    @syslog with($foo,$bar) {
        baz[$foo][$bar]++
    }

or (little weird):

    @syslog($foo, $bar) {
       baz[$foo][$bar]++
    }

or even just:

    @syslog $foo, $bar {
         baz[$foo][$bar]++
    }

It depends... IMHO, either the first or the second variant with the explicit keyword would be the best as it allows for adding more extensions in the future easily if needed.

**Comment by jaqx0r** [comment]
I think I prefer the "with" or "using" keywords because it makes the
meaning more obvious (to me). And I think I prefer "using" over "with"
because it reminds me of C++ "using"

**Comment by mjf** [comment]
@jaqx0r Well, `using` sounds OK. 😄
