### ISSUE TITLE
Is the release of version 3.0.4 cancelled?

### ISSUE THREAD

**Issue by nudgegoonies** [google/mtail#892]
The v3.0.4 tag is there for several days but there is no release.

**Comment by jaqx0r** [comment]
I think there's a bug in the automatic release script. I also thought I'd disabled it but apparently not.

Unless there's a release, consider the tag failed.

**Comment by nudgegoonies** [comment]
Thank you for your answer.
Our update check watches tags so i stumbled on the missing release.

**Comment by jaqx0r** [comment]
It's a fair expectation... Sorry for the inconvenience.

**Comment by jaqx0r** [comment]
3.0.5 is now out

**Comment by nudgegoonies** [comment]
Thank you!
