### ISSUE TITLE
User defined labels for mtail specific metrics

### ISSUE THREAD

**Issue by Nilesh-Shastri** [google/mtail#905]
I am looking for adding user defined labels to mtail specific metrics.

For example, the user must be able to add a custom label (eg, server="srv1") to any mtail specific metric (eg, mtail_log_lines_total).

I understand that this is achievable by updating scrape config on Prometheus. I'm still interested to have that done using mtail.

Thanks in advance!

**Comment by jaqx0r** [comment]
You gave the answer already, it's part of the scrape config in Prometheus.

**Comment by Nilesh-Shastri** [comment]
Thanks for your response, Jamie!

Is it OK to presume that there is no possibility of achieving that using mtail, and there are no plans to implement any such feature?

**Comment by jaqx0r** [comment]
I have no plans to implement this.

There is of course no technical barrier to adding it, but I don't want to maintain more code when less will do, and when this is possible with other tools in the ecosystem.
