### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by imlit** [google/mtail#91]
Hi, 
I can't seem to compile it.  Error message below.  The "github.com/google/mtail/mtail" package does not get fetched.  Tested on a Debian, and Ubuntu system with same error.  Go Version 1.8

go install -ldflags "-X main.Version=v3.0.0-rc1-149-gd02b85c -X main.Revision=d02b85c17c57549a9f3841b0ae7b3d4ed729bf01"
main.go:15:2: cannot find package "github.com/google/mtail/mtail" in any of:
        /usr/lib/go-1.8/src/github.com/google/mtail/mtail (from $GOROOT)
        /home/xxx/go/src/github.com/google/mtail/mtail (from $GOPATH)
Makefile:72: recipe for target 'mtail' failed

Thanks,
David

**Comment by jaqx0r** [comment]
I need to know where you fetched it and what your GOROOT environment
variable is set to.

**Comment by imlit** [comment]
Hi Jamie,
Below is the info, and the make log.  Thanks


GOROOT="/usr/lib/go-1.8" 
git clone https://github.com/google/mtail.git







-go env

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/airable/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build972098904=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"



- git clone https://github.com/google/mtail.git
Cloning into 'mtail'...
remote: Counting objects: 5452, done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 5452 (delta 142), reused 195 (delta 114), pack-reused 5207
Receiving objects: 100% (5452/5452), 2.30 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3717/3717), done.
Checking connectivity... done.

- cd mtail
- make

go get golang.org/x/tools/cmd/goyacc
touch .gen-dep-stamp
go generate -x ./vm
/home/airable/go/bin/goyacc -v y.output -o parser.go -p mtail parser.y
# Install all dependencies, ensuring they're updated
go get -u -v bufio bytes crypto/rand encoding/json errors expvar flag fmt github.com/fsnotify/fsnotify github.com/golang/glog github.com/spf13/afero html/template io io/ioutil math math/big math/rand net net/http net/http/pprof os os/signal path path/filepath reflect regexp regexp/syntax runtime runtime/debug sort strconv strings sync sync/atomic syscall text/tabwriter time unicode unicode/utf8
github.com/fsnotify/fsnotify (download)
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag main.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
github.com/golang/glog (download)
github.com/spf13/afero (download)
Fetching https://golang.org/x/text/transform?go-get=1
Parsing meta tags from https://golang.org/x/text/transform?go-get=1 (status code 200)
get "golang.org/x/text/transform": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
Fetching https://golang.org/x/text/unicode/norm?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/norm?go-get=1 (status code 200)
get "golang.org/x/text/unicode/norm": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
github.com/spf13/afero/mem
golang.org/x/sys/unix
golang.org/x/text/transform
github.com/golang/glog
golang.org/x/text/unicode/norm
github.com/spf13/afero
github.com/fsnotify/fsnotify
go get -u -v encoding/json errors expvar flag fmt github.com/golang/glog github.com/go-test/deep github.com/spf13/afero io io/ioutil math/rand net/http net/http/httptest os path path/filepath reflect regexp regexp/syntax runtime sort strconv strings sync syscall testing testing/quick time
github.com/golang/glog (download)
github.com/go-test/deep (download)
github.com/spf13/afero (download)
Fetching https://golang.org/x/text/transform?go-get=1
Parsing meta tags from https://golang.org/x/text/transform?go-get=1 (status code 200)
get "golang.org/x/text/transform": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
Fetching https://golang.org/x/text/unicode/norm?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/norm?go-get=1 (status code 200)
get "golang.org/x/text/unicode/norm": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
github.com/go-test/deep
touch .dep-stamp
go install -ldflags "-X main.Version=v3.0.0-rc1-149-gd02b85c -X main.Revision=d02b85c17c57549a9f3841b0ae7b3d4ed729bf01"
main.go:15:2: cannot find package "github.com/google/mtail/mtail" in any of:
        /usr/lib/go-1.8/src/github.com/google/mtail/mtail (from $GOROOT)
        /home/airable/go/src/github.com/google/mtail/mtail (from $GOPATH)
Makefile:72: recipe for target 'mtail' failed
make: *** [mtail] Error 1

**Comment by jaqx0r** [comment]
It looks like you didn't git clone into your GOPATH. This is a shortcoming
of the go tools IMO and maybe I can work around it in the makefile.
