### ISSUE TITLE
print matching regex lines

### ISSUE THREAD

**Issue by rohitnagpal88** [google/mtail#93]
Is their a switch which i can use to print out the lines as well which match the regex ? I cant seem to find one :( . This way i wouldn't have to run a separate program to extract those in some other file which is my requirement .

**Comment by jaqx0r** [comment]
I am not sure I understand what you need.  There is grep or awk or perl which do this.  Can you tell me more about your requirement?

**Comment by rohitnagpal88** [comment]
My requirement is that i also want to see which lines match the given regex (probably have them redirected to a separate file) , so rather than running a separate program like grep or awk wouldn't it be nice if mtail can also print out the line which matched by perhaps giving an option like this ?

**Comment by jaqx0r** [comment]
Yes you've said that already, but you haven't really explained what the
problem is.   I don't think it would be nice to print the line which
matched; in many mtail programs every lines matches some rule, so you just
print the whole file again.  Some matching rules may only get a partial
line, and if we get a solution to #36 or #88 then we might not even be
matching against an input line anymore.  mtail is a non-detaching daemon,
so it expects to run forever but it doesn't read from stdin and it doesn't
expect anything to be reading stdout.

So, I want to know more about your use case so I can help you figure out
how best to address it.  Right now, I don't think mtail is a good fit for
your requirements.

For example, what sort of log files are you tailing?  What does the current
program look like?  Why do you want to print just those matching lines, and
why isn't grep suitable?  What if another program was doing the filtering
before mtail got the log lines, so you could perhaps tail -f log | grep |
mtail -log_fd 0 ?

mtail is a metric extractor, not a filter, so I don't think emitting log
lines is a feature that should be added.  But I want you to help me
understand why you think it should, and convince me I'm wrong.

**Comment by rohitnagpal88** [comment]
Ok , i understand that mtail was not really made for the purpose of filtering and should only be used as a metric extractor. 
My use case is rather a very simple one. I am not expecting every other line to be matched to some rule. Infact, any no. of lines that matches a rule in a given interval should lead to an alert (using prometheus). So my program with a few counters would look something like below. Basically i am expecting these to be slow moving counters. 

counter counter_a
counter counter_b
...
...

/(.*regex_a.*)/ {
    counter_a++
}
/(.*regex_b.*)/ {
    counter_a++
}
...
...

So, all i was trying to look for is if there was a specific option with mtail itself which would allow me to also capture and redirect the matching lines to some other file for investigation later on. But doesn't look like there is one so i will probably have a separate program running to also capture the matching lines.

**Comment by jwalzer** [comment]
Maybe as a dirty workaround, a small tip, that I use when creating new programs and debugging them:

When I find myself in a situation where I'd like to do a printf-debugging and see the value of a variable or a match or a pattern, I found myself declaring a metric I can use for debugging:
`counter debug by label`

Whenever I need to see a value for troubleshooting I do an:
`debug["variable: $variable"]++`

So I can see counter get created/increase when a rule hits

not nice - and of course not for production - but sometimes writing regexes is hard.

**Comment by jaqx0r** [comment]
That's very cool.  Thanks :)

**Comment by hubt** [comment]
I actually would like to see a printf type of feature. It would be possible to use grep or something else to pre-filter and pipe into mtail. But there are features that mtail provides that makes a grep pre-filter not that great, for example, managing multiple concurrent rolling log files.

My current use is that I want to do both metrics and alerting based on log files. So I'd like to have a single program which lets me define regexes and that tails log files and can generate metrics and send alerts to something else. For starters, sending an alert could be just writing to a file where I could pick it up and generate a real alert, but later sending alerts to graphite via the Events endpoint or collectd via the PUTNOTIF command.

It is of course possible to use metrics with labels and alert from those, but imagine I create a metric for each ERROR log line. Doing this, either I'd collapse all types of ERRORS together and not see enough detail in the ERROR message. Or not coalescing ERRORS together, I'd have a very large number of random labels.

I understand it might go against how mtail is designed and typically used. But right now my solution is to run both filebeat for alerts and mtail for metrics on every log file, which seems inefficient. ( I may move to using filebeat as a pre-filter for mtail). Other ideas are welcome too.

**Comment by mattpr** [comment]
Here is a concrete problem/use-case... in general I only use mtail for tailing logs and generating counters.  I will often have a specific format log generated for mtail (for instance to extract nginx counters by the label/dimensions I want).  In order to catch log format issues I also count the number of lines that do not match.  Something like this:

```
/^/ +
/(?P<msec>\d+)\.\d+\t/ +
/(?P<host>\S+)\t/ +
/(?P<server_port>\S+)\t/ +
/(?P<request_method>\S+)\t/ +
/(?P<uri>\S+)\t/ +
/(?P<content_type>\S+)\t/ +
/(?P<status>\S+)\t/ +
/(?P<request_length>\d+)\t/ +
/(?P<bytes_sent>\d+)\t/ +
/(?P<body_bytes_sent>\d+)\t/ +
/(?P<request_time>\d+\.\d+)\t/ +
/(?P<upstream_connect_time>\S+)\t/ +
/(?P<upstream_header_time>\S+)\t/ +
/(?P<upstream_response_time>\S+)/ +
/$/ {
    # increment all the counters
} else {
    # no match...weird
    nginx_log_nomatch_count++
    del nginx_log_nomatch_count after 10m
}
```

Some percentage of those log lines won't match the pattern for some reason.  I have a prometheus alert if it is more than X within a given period.  However I can't really troubleshoot to see if anything is wrong because I don't know which of the many log lines were the ones that didn't match. 

So in my use case, I would use a print statement of some sort in the else block in order to route lines to some other file.  This would be useful for developing mtail programs and for troubleshooting issues in production...alerts go off, mtail is having a lot of log lines that don't match...what do those log lines look like?  Perhaps nginx got updated and my nginx log format config is no longer valid.

Would be very happy for suggestions on other ways to approach this particular use case.  Always looking for "the better way."  Thanks.
