### ISSUE TITLE
Specify default time zone/location for strptime

### ISSUE THREAD

**Issue by mbode** [google/mtail#94]
In some legacy log files of ours there is a timestamp in some format without an explicitly set time zone but the (non-UTC) time zone of the log event is known. If I understand correctly, in cases like this one would like to use [ParseInLocation](https://golang.org/pkg/time/#ParseInLocation) instead of Parse. Is there an easy way to enhance strptime to accept as input a location or default timezone to apply to timestamps or is there already another way to achieve this behavior?

**Comment by jaqx0r** [comment]
Good suggestion, thanks!

We already pass in a flag to set a default year if none is in the parsed
timestamp. It would be possible to use the same mechanism to pass in a
timezone, but it would be the same for all programs in the same mtail
instance at the moment.

**Comment by mbode** [comment]
For our case case this would be sufficient for now.
