### ISSUE TITLE
Create a new release, because the latest release candidate does not expand wildcards in -logs flag

### ISSUE THREAD

**Issue by dkyrkou** [google/mtail#95]
Hi,

I tried to use the latest v3.0.0-rc1 to parse some logs, but it doesn't perform log file globbing aka expansion of wildcards at all (no matter what I tried).

However, the current master works perfectly for me and does expand wildcards.

Can you make a new release/tag from the current master? I don't feel comfortable building from master everytime, so it would be great if a release of the current master existed. A plain git tag would be enough.

Thank you for reading this, and I hope my request is considered.

**Comment by jaqx0r** [comment]
No problem.

**Comment by jaqx0r** [comment]
github can't read Issue tags in tag descriptions it seems!

I've just added tag  v3.0.0-rc2
