### ISSUE TITLE
Log file names containing date?

### ISSUE THREAD

**Issue by PaulWalkerUK** [google/mtail#96]
I have an application that generates log files that contain the date as part of the filename, in the format, e.g. the file that's being written to today is called `log_2017-09-01.txt`. Tonight, at midnight, it will leave that file where it is and start writing to `log_2017-09-02.txt`, etc.

From my understanding, it looks like when I start mtail, I either have to specify the full filename either as a literal or as a pattern it can match. Since a new file is started at midnight, mtail will carry on looking at "yesterday's" file when it switches. Any ideas about how I can get mtail to 'track' the current file?

(It's a third party application that I have no control over unfortunately!)

**Comment by jaqx0r** [comment]
If you pass a glob pattern to mtail, it should work.  When you pass, say,
/logs/log_*.txt then mtail adds a directory watch on /logs and any file
creation event causes it to match against log_*.txt to see if the new file
should be tailed.

Please try with --logtostderr --vmodule=log_watcher=2 on the command line
for extra log output if that isn't working.

**Comment by PaulWalkerUK** [comment]
Thanks @jaqx0r, I'll take a look at that
