### ISSUE TITLE
Support for HELP comment directive

### ISSUE THREAD

**Issue by mjf** [google/mtail#98]
Hello,

please add support for the `HELP` comment directive to produce help for metrices (as described in the [documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details)).

I would suggest to the *mtail*'s syntax by the following one (just symbolically written in core *ABNF*):

    "help" 1*WSP MetricName 1*WSP DQUOTE MetricHelp DQUOTE [1*WSP ProgramComment]

Example:

    counter foo
    help foo "Some useful information"   # add simple help

Sample result:

    # HELP foo Some useful information
    # TYPE foo counter
    foo 1.234+e5

**Additional suggestions**

In case no help was provided then the help can contain the currently produced `<metric> defined at <filename>:<line>:<begin>-<end>` information for the metric. Also the information *should* be reachable by the `MetricHelp` literal too (i.e. by using some *escape sequences* or other way of choice).

Example:

    counter foo
    help foo "Some useful information (see \"\F\":\L:\B-\E)"   # add rich help

Sample result:

    # HELP foo Some useful information (see "filename.mtail":100:10-20)
    # TYPE foo counter
    foo 1.234+e5

**Sidenotes**

Once `summary` and `histogram` types are added (I am not sure but I think feature request to support `summary` already exists) the `MetricName` can be related to their "base name".

**Comment by jaqx0r** [comment]
Does Prometheus do something with HELP now?

Why isn't putting a comment next to the definition that the HELP filename:line points to sufficient?  This is a lot of functionality for a feature that, when I implemented it two months ago, Prometheus didn't even make available to users.  So as far as I can see, it's a useful debugging tool, and the existing functionality is more than sufficient for finding the source of a metric in the current environment.

**Comment by mjf** [comment]
@jaqx0r *Prometheus* does not do anything special with the `HELP` as far as I know. But people just use `curl(1)` from command line to read the help information. Also some metric browser exposing the information to users is pretty imaginable. Some exporters provide nice and useful descriptions of the metrices, including *Prometheus* itself. Sometimes it's simply not clear enough what a metric represents without some further description of it. And that's exactly what the `HELP` is considered to be, I think. It is very useful feature from my point of view. Consider for example this example from *Prometheus*:

    # HELP prometheus_evaluator_iterations_missed_total The total number of rule group evaluations missed due to slow rule group evaluation.
    # TYPE prometheus_evaluator_iterations_missed_total counter
    prometheus_evaluator_iterations_missed_total 10

I do not think for a user who does not know the internals the name of the metric is clear-enough. The `HELP` makes it somehow more clear.

-----

By the way, the `HELP` keyword is missing at the beginnig of the line with the `filename:line` in my version of `mtail` I use right now:

    mtail version v3.0.0-rc1-164-g1f87b2b git revision 1f87b2be462d80e212dda09eba4e684b372e1391 go version go1.8.3

**Comment by filippog** [comment]
AFAIK Prometheus doesn't use `HELP`. Though I ran into a case where ingestion was refused, namely when two metrics with the same name came with different `HELP` descriptions. Something worth considering if it might happen in mtail too.

**Comment by jaqx0r** [comment]
I'm inclined to not implement this; it's a nice idea but if mtail is already exporting the source file location of the metric then one can follow the breadcrumbs.

I get mjf's reasoning in both the first and third updates here, but neither are more compelling than a comment in the program, IMHO.
